package anyparse.grammar.haxe;

import anyparse.format.BodyPolicy;
import anyparse.format.IndentChar;

/**
 * Loads a haxe-formatter `hxformat.json` config and maps the subset of
 * fields the `HxModule` writer understands into `HxModuleWriteOptions`.
 *
 * The mapping is strictly additive: anything the loader does not
 * recognise is silently ignored (forward-compatible), and every field
 * it does not find falls back to `HaxeFormat.instance.defaultWriteOptions`.
 * This makes round-tripping `HaxeFormatConfigLoader.loadHxFormatJson('{}')`
 * byte-identical to using the defaults directly.
 *
 * Recognised key paths (all optional):
 *
 * - `indentation.character`: string — `"tab"` → `indentChar = Tab, indentSize = 1`;
 *   any string composed entirely of spaces → `indentChar = Space, indentSize = length`.
 *   Every other value is ignored.
 * - `indentation.tabWidth`: int → `tabWidth`.
 * - `wrapping.maxLineLength`: int → `lineWidth`.
 * - `sameLine.ifElse` / `sameLine.tryCatch` / `sameLine.doWhile`: enum
 *   string — `"same"` maps to `true`, every other value (`"next"`,
 *   `"keep"`, `"fitLine"`) maps to `false`. `keep` / `fitLine` would
 *   need per-site source-shape tracking the Haxe writer does not yet
 *   carry; treating them as `next` (false) matches the nearest layout
 *   we can currently render.
 * - `trailingCommas.arrayLiteralDefault` / `trailingCommas.callArgumentDefault`
 *   / `trailingCommas.functionParameterDefault`: enum string — `"yes"`
 *   maps to `true`, every other value (`"no"`, `"keep"`, `"ignore"`) to
 *   `false`. `keep` requires an AST that remembers whether the source
 *   had a trailing comma — a debt to address once the parser records
 *   that detail; for now the writer only knows "always" or "never".
 *
 * Deliberately NOT supported in this slice (no corresponding
 * `HxModuleWriteOptions` field yet): `wrapping.*`, `lineEnds.*`,
 * `emptyLines.*`, `whitespace.*`, `indentation.conditionalPolicy`,
 * `indentation.trailingWhitespace`, `baseTypeHints`, `disableFormatting`,
 * `excludes`. They will land with the slices that introduce the
 * matching knobs.
 *
 * Two-stage pipeline: `HxFormatConfigParser` (macro-generated ByName
 * struct parser) reads the JSON into a typed `HxFormatConfig`, then
 * this class maps that struct onto `HxModuleWriteOptions` with no
 * `JValue` walks, no field-name strings, no runtime-typed switches.
 * Adding a new recognised key means extending the schema in
 * `HxFormatConfig.hx` and adding one line here.
 *
 * All-static utility: the loader holds no state.
 */
@:nullSafety(Strict)
final class HaxeFormatConfigLoader {

	/**
	 * Parses a `hxformat.json` document and returns the equivalent
	 * `HxModuleWriteOptions`, starting from the Haxe format defaults
	 * and overwriting only the fields the config explicitly sets.
	 */
	public static function loadHxFormatJson(json:String):HxModuleWriteOptions {
		final cfg:HxFormatConfig = HxFormatConfigParser.parse(json);
		final base:HxModuleWriteOptions = HaxeFormat.instance.defaultWriteOptions;
		final result:HxModuleWriteOptions = {
			indentChar: base.indentChar,
			indentSize: base.indentSize,
			tabWidth: base.tabWidth,
			lineWidth: base.lineWidth,
			lineEnd: base.lineEnd,
			finalNewline: base.finalNewline,
			sameLineElse: base.sameLineElse,
			sameLineCatch: base.sameLineCatch,
			sameLineDoWhile: base.sameLineDoWhile,
			trailingCommaArrays: base.trailingCommaArrays,
			trailingCommaArgs: base.trailingCommaArgs,
			trailingCommaParams: base.trailingCommaParams,
			ifBody: base.ifBody,
			elseBody: base.elseBody,
			forBody: base.forBody,
			whileBody: base.whileBody,
			doBody: base.doBody,
		};
		if (cfg.indentation != null) applyIndentation(cfg.indentation, result);
		if (cfg.wrapping != null) applyWrapping(cfg.wrapping, result);
		if (cfg.sameLine != null) applySameLine(cfg.sameLine, result);
		if (cfg.trailingCommas != null) applyTrailingCommas(cfg.trailingCommas, result);
		return result;
	}

	private function new() {}

	private static function applyIndentation(section:HxFormatIndentationSection, opt:HxModuleWriteOptions):Void {
		final character:Null<String> = section.character;
		if (character != null) {
			if (character == 'tab') {
				opt.indentChar = Tab;
				opt.indentSize = 1;
			} else if (isAllSpaces(character) && character.length > 0) {
				opt.indentChar = Space;
				opt.indentSize = character.length;
			}
		}
		if (section.tabWidth != null) opt.tabWidth = section.tabWidth;
	}

	private static function applyWrapping(section:HxFormatWrappingSection, opt:HxModuleWriteOptions):Void {
		if (section.maxLineLength != null) opt.lineWidth = section.maxLineLength;
	}

	private static function applySameLine(section:HxFormatSameLineSection, opt:HxModuleWriteOptions):Void {
		if (section.ifElse != null) opt.sameLineElse = sameLineToBool(section.ifElse);
		if (section.tryCatch != null) opt.sameLineCatch = sameLineToBool(section.tryCatch);
		if (section.doWhile != null) opt.sameLineDoWhile = sameLineToBool(section.doWhile);
		if (section.ifBody != null) opt.ifBody = bodyPolicyToRuntime(section.ifBody);
		if (section.elseBody != null) opt.elseBody = bodyPolicyToRuntime(section.elseBody);
		if (section.forBody != null) opt.forBody = bodyPolicyToRuntime(section.forBody);
		if (section.whileBody != null) opt.whileBody = bodyPolicyToRuntime(section.whileBody);
		if (section.doWhileBody != null) opt.doBody = bodyPolicyToRuntime(section.doWhileBody);
	}

	private static function applyTrailingCommas(section:HxFormatTrailingCommasSection, opt:HxModuleWriteOptions):Void {
		if (section.arrayLiteralDefault != null)
			opt.trailingCommaArrays = trailingCommaToBool(section.arrayLiteralDefault);
		if (section.callArgumentDefault != null)
			opt.trailingCommaArgs = trailingCommaToBool(section.callArgumentDefault);
		if (section.functionParameterDefault != null)
			opt.trailingCommaParams = trailingCommaToBool(section.functionParameterDefault);
	}

	private static inline function sameLineToBool(policy:HxFormatSameLinePolicy):Bool {
		return policy == HxFormatSameLinePolicy.Same;
	}

	private static inline function trailingCommaToBool(policy:HxFormatTrailingCommaPolicy):Bool {
		return policy == HxFormatTrailingCommaPolicy.Yes;
	}

	private static function bodyPolicyToRuntime(policy:HxFormatBodyPolicy):BodyPolicy {
		return switch policy {
			case HxFormatBodyPolicy.Same: BodyPolicy.Same;
			case HxFormatBodyPolicy.Next: BodyPolicy.Next;
			case HxFormatBodyPolicy.FitLine: BodyPolicy.FitLine;
			case HxFormatBodyPolicy.Keep: BodyPolicy.Same;
			case _: BodyPolicy.Same;
		};
	}

	private static function isAllSpaces(s:String):Bool {
		for (i in 0...s.length) if (s.charCodeAt(i) != ' '.code) return false;
		return true;
	}
}
