package anyparse.grammar.haxe;

import anyparse.format.CommentStyle;
import anyparse.format.IndentChar;
import anyparse.format.WriteOptions;

/**
 * Plugin-level AST transformation for captured block-comment bodies.
 *
 * Lives in the Haxe format plugin package — NOT in the macro core or
 * the generic runtime. Parser and writer are 100% auto-generated by
 * `Build.buildParser` / `Build.buildWriter` and know nothing about
 * Haxe comment conventions; this normalizer is where those
 * conventions live. It runs between parse and write:
 *
 *  raw `/*…*\/` string
 *    → `BlockCommentParser.parse`
 *    → `BlockComment` AST (verbatim, variants distinguished by
 *      source wrap literals; each line is `StarredLine` or `PlainLine`)
 *    → `HaxeCommentNormalizer.normalize` (AST → AST: pick target
 *      variant + per-line variant, normalize ws, fabricate markers)
 *    → `BlockComment` AST (canonical, target variants)
 *    → `BlockCommentWriter.writeDoc`
 *    → `Doc` embedded in the enclosing writer's stream
 *
 * What this class decides (the Haxe-specific rendering policy):
 *
 *  - **Wrap variant**: `opt.commentStyle == Plain` → `BlockComment.Plain`;
 *    `Javadoc` or `JavadocNoStars` → `BlockComment.DoubleStars`.
 *    Wrap literals (`/*` / `*\/` / `/**` / `**\/`) come from the
 *    enum's `@:lead` / `@:trail` metas — this class never hardcodes
 *    them.
 *  - **Line variant**: for `Javadoc` output → `StarredLine` (canonical
 *    marker fabricated); for `JavadocNoStars` / `Plain` → `PlainLine`.
 *  - **Indent canonicalization**: source leading ws is reduced via
 *    common-prefix across non-blank lines; remainder becomes the
 *    relative offset carried into the canonical `ws`. Absolute
 *    indent comes from the writer's `indentChar` / `indentSize`.
 *  - **Inline-first-line exclusion**: `lines[0]` is excluded from
 *    the common-prefix compute when it has non-blank content
 *    (source had `/** foo` inline).
 *  - **Blank-edge skip**: fully-blank first/last captured line
 *    dropped so wrap delimiters sit on their own lines.
 */
class HaxeCommentNormalizer {

	// Canonical Javadoc line prefixes. These are Haxe-plugin canonical
	// forms — the one place in the plugin that decides "a starred
	// content line is written as ` * <content>`, a starred blank
	// line as ` *`". Parser-side capture is permissive (any ws +
	// star + optional sep); this is the write-side canonical.
	private static inline final JAVADOC_MARKER_SPACED:String = '* ';
	private static inline final JAVADOC_MARKER_BLANK:String = '*';
	private static inline final JAVADOC_WS:String = ' ';

	public static function normalize(source:BlockComment, opt:WriteOptions):BlockComment {
		final sourceLines:Array<BlockCommentLine> = switch source {
			case DoubleStars(ls): ls;
			case Plain(ls): ls;
		};
		final canonicalLines:Array<BlockCommentLine> = normalizeLines(sourceLines, opt);
		return switch opt.commentStyle {
			case Plain: BlockComment.Plain(canonicalLines);
			case Javadoc, JavadocNoStars: BlockComment.DoubleStars(canonicalLines);
		};
	}

	private static function normalizeLines(source:Array<BlockCommentLine>, opt:WriteOptions):Array<BlockCommentLine> {
		final withStars:Bool = opt.commentStyle == CommentStyle.Javadoc;
		final indentUnit:String = opt.indentChar == IndentChar.Tab
			? '\t'
			: StringTools.rpad('', ' ', opt.indentSize);

		final firstInline:Bool = source.length > 0
			&& getLineContent(source[0]).length > 0;

		// Common-prefix reduce across non-blank lines' leading ws,
		// excluding line 0 when it's inline with the opening delimiter.
		var commonPrefix:String = '';
		var havePrefix:Bool = false;
		for (i in 0...source.length) {
			if (i == 0 && firstInline) continue;
			if (getLineContent(source[i]).length == 0) continue;
			final ws:String = getLineWs(source[i]);
			if (!havePrefix) {
				commonPrefix = ws;
				havePrefix = true;
			} else {
				final lim:Int = commonPrefix.length < ws.length ? commonPrefix.length : ws.length;
				var j:Int = 0;
				while (j < lim && StringTools.fastCodeAt(commonPrefix, j) == StringTools.fastCodeAt(ws, j)) j++;
				commonPrefix = commonPrefix.substr(0, j);
			}
		}
		final commonLen:Int = commonPrefix.length;

		final result:Array<BlockCommentLine> = [];
		final last:Int = source.length - 1;
		for (i in 0...source.length) {
			final ln:BlockCommentLine = source[i];
			final content:String = getLineContent(ln);
			if ((i == 0 || i == last) && content.length == 0) continue;
			final sourceWs:String = getLineWs(ln);
			final relWs:String = sourceWs.length > commonLen ? sourceWs.substr(commonLen) : '';
			if (withStars) {
				if (content.length > 0) {
					result.push(BlockCommentLine.StarredLine({
						ws: JAVADOC_WS,
						marker: JAVADOC_MARKER_SPACED,
						content: relWs + content,
					}));
				} else {
					result.push(BlockCommentLine.StarredLine({
						ws: JAVADOC_WS,
						marker: JAVADOC_MARKER_BLANK,
						content: '',
					}));
				}
			} else {
				result.push(BlockCommentLine.PlainLine({
					ws: indentUnit + relWs,
					content: content,
				}));
			}
		}
		return result;
	}

	private static function getLineWs(ln:BlockCommentLine):String {
		return switch ln {
			case StarredLine(body): body.ws;
			case PlainLine(body): body.ws;
		};
	}

	private static function getLineContent(ln:BlockCommentLine):String {
		return switch ln {
			case StarredLine(body): StringTools.rtrim(body.content);
			case PlainLine(body): StringTools.rtrim(body.content);
		};
	}
}
