package anyparse.grammar.haxe;

using Lambda;

/**
 * Per-element complexity classification of a delimited list, as the writer's
 * `WrapListOptions.complexItemKinds` axis expects it.
 *
 * "Complex" has ONE definition across both consumers (the `complexItemCount >= n`
 * wrap condition and the `callParameter` chunk policy): a `new` expression, a
 * call, or a CONTAINER literal (object or array) carrying a call / `new` anywhere
 * in its subtree. A container WITHOUT one — `[{x: 1, y: 2}, {x: 3, y: 4}]` — is
 * NOT complex and keeps whatever layout width alone gives it.
 *
 * The classification is deliberately SEMANTIC. The same `arrayWrap` cascade also
 * governs array PATTERNS in `case` arms and switch-subject arrays, whose elements
 * are identifiers, wildcards and literals; a width proxy (`anyItemLength >= n`)
 * mangles those, while nothing in this counter can reach them. The one shape that
 * DOES look like a call there is an enum-constructor pattern (`case [Some(a),
 * Some(b)]`), which the writer excludes through its own `_suppressComplexItems`
 * context flag rather than by guessing here.
 *
 * Untyped input for the same reason as `HaxeFormat.isComprehensionGenerator`: the
 * callers are generated by the grammar-agnostic writer lowering, which holds
 * elements untyped, and both the bare node and the trivia-synth `{node: …}`
 * wrapper arrive here. Anything unrecognised answers `NONE`.
 */
final class HxComplexItems {

	/** Code for an element that is neither a call/new nor a call-bearing container. */
	public static inline final NONE: Int = 0;

	/** Code for an element that IS a function call or a `new` constructor call. */
	public static inline final CALL: Int = 1;

	/** Code for a container literal (object / array) carrying a call or `new` in its subtree. */
	public static inline final CONTAINER: Int = 2;

	/**
	 * Depth ceiling of the subtree walk. The Haxe AST is a finite tree with no
	 * back-pointers (`Trivial<T>` carries only the node and its comment slots), so
	 * the cap is not a cycle guard — it bounds the cost of a pathologically nested
	 * container and answers "not complex" past it, which is the layout-preserving
	 * direction.
	 */
	private static inline final MAX_DEPTH: Int = 64;

	/** One `NONE` / `CALL` / `CONTAINER` code per element, length-aligned with the writer's item Docs. */
	public static function kinds(elements: Array<Any>): Array<Int> {
		final out: Array<Int> = [];
		for (element in elements) {
			var node: Null<Any> = element;
			if (node != null && !Reflect.isEnumValue(node)) node = Reflect.field(node, 'node');
			if (node == null || !Reflect.isEnumValue(node)) {
				out.push(NONE);
				continue;
			}
			final kind: Int = switch Type.enumConstructor(node) {
				case 'Call', 'NewExpr': CALL;
				case 'ArrayExpr', 'ObjectLit': subtreeHasCallOrNew(node, 0) ? CONTAINER : NONE;
				case _: NONE;
			};
			out.push(kind);
		}
		return out;
	}

	/**
	 * True iff `v`'s subtree holds an `HxExpr.Call` or `HxExpr.NewExpr`. A
	 * structure walk rather than a per-ctor table: the question is "is there a call
	 * ANYWHERE below", so every child of every node has to be visited, and a table
	 * would only enumerate the same thing by hand and then go stale the next time
	 * the grammar grows an expression constructor. Enum values recurse through their
	 * parameters, arrays through their elements, anonymous structures (grammar
	 * `typedef`s and the `Trivial<T>` wrapper) through their fields; leaves answer
	 * `false`.
	 */
	private static function subtreeHasCallOrNew(v: Null<Any>, depth: Int): Bool {
		if (v == null || depth > MAX_DEPTH) return false;
		if (Reflect.isEnumValue(v)) {
			final ctor: String = Type.enumConstructor(v);
			if (ctor == 'Call' || ctor == 'NewExpr') return true;
			for (param in Type.enumParameters(v)) if (subtreeHasCallOrNew(param, depth + 1)) return true;
			return false;
		}
		if (Std.isOfType(v, Array)) {
			final arr: Array<Any> = cast v;
			return arr.exists(item -> subtreeHasCallOrNew(item, depth + 1));
		}
		// `Reflect.isObject` answers true for String on several targets, and a
		// string's "fields" are its methods — walking them is pure cost.
		if (Std.isOfType(v, String) || !Reflect.isObject(v)) return false;
		return Reflect.fields(v).exists(name -> subtreeHasCallOrNew(Reflect.field(v, name), depth + 1));
	}

}
