package anyparse.grammar.haxe;

/**
 * Marker class for the macro-generated ByName parser of
 * `HxFormatConfig`. Populated entirely by the τ₄ ByName lowering
 * codepath — the class body stays empty, as with every other
 * `@:build(buildParser(...))` marker in the project.
 *
 * Used by `HaxeFormatConfigLoader.loadHxFormatJson` as the first
 * stage of the two-stage `hxformat.json` pipeline: this parser
 * builds a typed `HxFormatConfig`, the loader maps it onto
 * `HxModuleWriteOptions`.
 */
@:build(anyparse.macro.Build.buildParser(anyparse.grammar.haxe.HxFormatConfig))
@:nullSafety(Strict)
class HxFormatConfigParser {}
