package testkit;

/**
 * The suite's registration layer — every member here is GENERATED by
 * `testkit.TestDiscovery.build`, which walks the test tree and asks utest's
 * own two questions of each class it finds.
 *
 * The class body is empty on purpose: a hand-written member here would be a
 * second source of truth for the very thing the macro exists to derive.
 * What the macro adds:
 *
 *  - `addAll(add)` — hands every discovered case to `add`, which is the
 *    `APQ_TEST`-filtering closure in `RunTests.main`.
 *  - `classNames()` — their fully-qualified names, the spelling an
 *    `APQ_TEST` filter and `apq shard-plan` both match on.
 *  - `deadTests()` — fixture-named methods utest will never run.
 *  - `baseClasses()` — `utest.Test` subclasses that carry no fixture.
 *  - `pins()` — every `@:pin`ned fixture with its role and killing arms.
 *  - `arms()` — every mutation arm `mutation-arms.json` declares, with the
 *    member it cuts and how.
 *
 * `unit.TestDiscoveryParityTest` pins all six.
 */
@:build(testkit.TestDiscovery.build())
final class TestRegistry {}
