package anyparse.grammar.haxe.checkstyle;

/**
 * Marker class for the macro-generated ByName parser of `CheckstyleConfig`.
 * Populated entirely by the ByName lowering codepath — the class body stays
 * empty, as with every other `@:build(buildParser(...))` marker in the
 * project.
 *
 * Used by `CheckstyleConfigLoader` as the first stage of every one of its
 * three entry points: this parser builds a typed `CheckstyleConfig`, the
 * loader maps it onto the neutral `NamingPolicy` / `CheckOverrides` /
 * complexity onset the checks read. `parse` throws on malformed or
 * wrong-shaped input; the loader lets that propagate to its callers, which
 * fall back to their defaults.
 */
@:build(anyparse.macro.Build.buildParser(anyparse.grammar.haxe.checkstyle.CheckstyleConfig))
@:nullSafety(Strict)
class CheckstyleConfigParser {}
