package anyparse.check;

import anyparse.check.Check.DefaultOff;
import anyparse.check.Check.Violation;
import anyparse.check.MemberOrder.MemberRank;
import anyparse.query.CanonicalEdit;
import anyparse.query.CtorFieldFold;
import anyparse.query.CtorFieldWrite;
import anyparse.query.GrammarPlugin;
import anyparse.query.LexicalRegions.LexRegion;
import anyparse.query.NamingPolicy.HoistedConstant;
import anyparse.query.NamingPolicy.NamingRule;
import anyparse.query.NamingPolicy.NamingSupport;
import anyparse.query.OccurrenceScan;
import anyparse.query.QueryNode;
import anyparse.query.RefactorSupport;
import anyparse.query.SourceText;
import anyparse.query.SymbolIndex;
import anyparse.runtime.Span;

using Lambda;
using StringTools;

/**
 * Flags a private instance field whose CONSTANT declaration default is overwritten by exactly
 * one CONDITIONAL constructor write, and folds the pair into a single unconditional assignment
 * of a conditional value:
 *
 * ```haxe
 * private var _cellsX:Int = 20;
 * // ...
 * public function new(?palette:Array<Int>) {
 *     if (palette != null) _cellsX = palette.length;
 * }
 * // ->
 * private var _cellsX:Int;
 * // ...
 * public function new(?palette:Array<Int>) {
 *     _cellsX = palette != null ? palette.length : 20;
 * }
 * ```
 *
 * The MIRROR of `field-init-at-declaration`, which moves a context-free constructor init UP onto
 * the declaration. This one moves a declaration default DOWN into the constructor, and it is the
 * one direction that pays off precisely when the constructor already writes the field on some
 * paths: the two spellings of the same value stop being two writes, which is what lets
 * `prefer-final-field` finish the job (see the chain below). `Info`, and `DefaultOff` — the fold
 * trades a declaration-site default for a constructor-site ternary, which not every project reads
 * as an improvement; opt in with `"field-init-in-constructor": { "enabled": true }`.
 *
 * ## Why ONE assignment with a CONDITIONAL VALUE, and not "assign on every branch"
 *
 * The obvious alternative — leave the `if` and add an `else` assigning the default — is the shape
 * a language with definite-assignment analysis would let the compiler check. Haxe does NOT run
 * that analysis for a `final` FIELD. Measured on 4.3.7 with
 * `class V { final _d:Int; public function new(c:Bool) if (c) _d = 1; }`, which compiles
 * SILENTLY on EVERY target tried - `--interp`, `-js`, `--jvm` and `-cpp` (a full hxcpp build
 * and run, not just a typecheck) - and `_d` then reads as that target's ZERO value on the path
 * that skipped the write: `null` on `--interp`, `undefined` on `-js`, `0` on `--jvm` and `-cpp`. The
 * only net is the `@:nullSafety` meta, and in EITHER mode: the bare / `Loose` form diagnoses the
 * shape exactly as `Strict` does (two errors - the field is used before initialization, and a
 * non-nullable field wants an initial value or a constructor assignment). It stays a per-file
 * opt-in all the same. Of the 805 files in the tree that motivated this rule, 53 carry
 * `@:nullSafety(Strict)` and 415 the bare form - leaving 337 with no net at all, the motivating
 * file among them. So a fix emitting
 * branch-per-arm assignments would have its COMPLETENESS checked by nothing at all. The
 * conditional-value form proves completeness structurally: there is exactly one assignment and it
 * always runs.
 *
 * ## The chain this closes
 *
 * The full cleanup of a CAPS-named mutable field holding a conditional default takes four steps,
 * and this rule is the one that was missing:
 *
 *  1. `naming` renames the UPPER_SNAKE instance field to the project's field convention;
 *  2. THIS rule folds `default + conditional write` into one unconditional conditional-valued
 *     assignment, leaving the field with exactly ONE write;
 *  3. `prefer-final-field` now sees that single unconditional constructor assignment and rewrites
 *     `var` to `final` — it is CORRECTLY silent before the fold, whose two writes (initializer plus
 *     constructor) fail its sole-write gate;
 *  4. `magic-number` reports the literal, which the fold has just moved INSIDE a function and hence
 *     into that rule's scope for the first time, so a human can name it as a `static inline final`.
 *     That last step stays human: `magic-number` is report-only by design.
 *
 * ## What is flagged
 *
 * Every gate is `RefactorSupport.ctorConditionalDefaultTernaryEdits`'s, so `run` and `fix` cannot
 * disagree about a candidate: the non-null edit list IS the finding. In outline — a plain
 * non-static `var` with a MOVE-SAFE constant default, a single constructor, exactly one top-level
 * `else`-less `if` whose then-branch OPENS with the field's assignment, a side-effect-free
 * condition whenever that `if` survives the fold, no early exit and no mention of the field before
 * the `if`, every `super(...)` after it, no `#if` region on the path, no self-referencing value, no
 * comment in a regenerated byte range, and no other write to the field name anywhere in the file.
 *
 * An assignment sitting DEEPER in the branch is refused rather than reordered — and reaches the
 * same end state one `--fix` pass later, once the assignment ahead of it has moved out. That is how
 * the motivating shape (two fields written under one `if`) converges: two passes, one field each,
 * and the `if` disappears with the second.
 *
 * ## Scope
 *
 * PUBLIC fields are out of scope: the fold widens the window in which the field holds its
 * type's zero value rather than its default, and outside code cannot be proven not to read it
 * there. STATIC fields are out of scope for the same reason `field-init-at-declaration` skips
 * them — a static's init timing is unrelated to instance construction. Cross-file soundness
 * (an `@:access` grantee, a subtype writer) is not proven here beyond the conservative
 * whole-file write scan; the shape's other writes would have to precede the constructor to
 * matter, which no writer of an instance field can do.
 */
@:nullSafety(Strict)
final class FieldInitInConstructor implements Check implements DefaultOff {

	private static inline final MESSAGE: String =
		'this field default is overwritten by one conditional constructor write - fold the pair into a single unconditional assignment of a conditional value';

	/**
	 * The suffix a derived constant name carries. Fixed rather than inferred from the file: the only
	 * available signal for "this file spells its defaults some other way" is a constant whose name
	 * EXTENDS a field's name, and that fires on ordinary compound names — a type holding
	 * `HEADER_HEIGHT` next to a `_header` field would teach the derivation to emit `..._HEIGHT`. A
	 * wrong suffix is a name nobody asked for, so the derivation stays the one everybody can predict.
	 */
	private static inline final DEFAULT_SUFFIX: String = '_DEFAULT';

	/**
	 * The constant names this `--fix` PASS has already minted, so a second field of the same type
	 * deriving the SAME name defers instead of landing a redefinition — see `RenameClaims`, whose
	 * hierarchy test answers "defer" for two claims on one type and "land" for two provably
	 * unrelated ones.
	 */
	private final _runClaims: RenameClaims = new RenameClaims();

	public function new() {}

	public function id(): String {
		return 'field-init-in-constructor';
	}

	public function description(): String {
		return 'a field default overwritten by one conditional constructor write - foldable into one assignment of a conditional value';
	}

	public function run(files: Array<{ file: String, source: String }>, plugin: GrammarPlugin): Array<Violation> {
		final violations: Array<Violation> = [];
		CtorFieldWrite.eachFieldMember(files, plugin, (owner, field, source, file, exported) -> {
			final span: Null<Span> = field.span;
			if (
				!exported && span != null && CtorFieldFold.ctorConditionalDefaultTernaryEdits(source, span, plugin) != null
			) violations.push({
				file: file,
				span: span,
				rule: id(),
				severity: Severity.Info,
				message: MESSAGE
			});
		});
		return violations;
	}

	/**
	 * Re-derive each flagged field's fold from its violation span and emit its edits. The
	 * producer is the same predicate `run` reported on, so a finding either fixes exactly as it
	 * was reported or (its source having changed under it) yields nothing.
	 */
	public function fix(
		source: String, violations: Array<Violation>, plugin: GrammarPlugin, ?index: SymbolIndex
	): Array<{ span: Span, text: String }> {
		final edits: Array<{ span: Span, text: String }> = [];
		// One insertion PER OFFSET, not per constant: two zero-width edits sharing an offset are
		// contained in one another, so `dropContainedEdits` would keep exactly one of them.
		final inserts: Array<{ at: Int, text: String }> = [];
		final tree: Null<QueryNode> = CheckScan.parseOrNull(plugin, source);
		final file: String = violations.length == 0 ? '' : violations[0].file;
		// The inherited-member proof walks the FULL supertype closure, so it resolves against the
		// plugin's resolution scope (report files UNION the configured libraries) when there is one —
		// the same index `naming` asks the same question of.
		final resolution: Null<SymbolIndex> = RefactorSupport.resolutionIndexOf(plugin) ?? index;
		for (v in violations) {
			final span: Null<Span> = v.span;
			if (span == null) continue;
			final fold: Null<Array<{ span: Span, text: String }>> = CtorFieldFold.ctorConditionalDefaultTernaryEdits(
				source, span, plugin,
				site -> tree == null ? null : extractedConstant(site, source, file, tree, plugin, resolution, inserts)
			);
			if (fold != null) for (edit in fold) edits.push(edit);
		}
		for (slot in inserts) edits.push({ span: new Span(slot.at, slot.at), text: slot.text });
		return CanonicalEdit.dropContainedEdits(edits);
	}

	/**
	 * The reference to write in the ternary's ELSE arm instead of the literal the fold is moving, or
	 * null to keep the literal — the `extract` seam of `ctorConditionalDefaultTernaryEdits`.
	 *
	 * A default that is a BARE literal is not an anonymous number in an expression: it is the default
	 * OF A NAMED FIELD, so its constant name is DERIVED (`_cellsNumX` -> `CELLS_NUM_X_DEFAULT`) rather
	 * than invented. That is the whole difference from `magic-number`, which meets the same literal one
	 * step later with no field to derive from and therefore stays report-only. Emitting it HERE rather
	 * than there is the same argument: this rule is what moves the literal out of the declaration, so it
	 * is the one that knows the field, and the one that would otherwise leave a half-finished state
	 * nobody else is equipped to recognise.
	 *
	 * Every gate fails CLOSED to the literal — the fold itself is unaffected either way:
	 *
	 *  - the default is a bare numeric / boolean / string literal. A negation (`-5`) or a dotted
	 *    constant chain (`Defaults.CELLS`) is refused: the first is computed, the second is ALREADY a
	 *    named constant and extracting it would mint a second name for one value. A string carries no
	 *    interpolation — the fold's own move-safety whitelist proved that before this is asked;
	 *  - the declaration states a type. The constant transcribes it, and a head that states none gives
	 *    it nothing to transcribe (and nothing to match a reuse candidate against). No fixture pins
	 *    this one and none can: the fold's own `initializerDropSpan` already refuses an unannotated
	 *    declaration (the ` = <default>` region it would delete runs back into the name), so the
	 *    annotation is a null-safety guard on a reader that can fail, not a discriminating gate;
	 *  - an index is available. Haxe rejects a static whose name matches an INHERITED INSTANCE field
	 *    ("Same field name can't be used for both static and instance"), and without a resolvable
	 *    supertype closure that cannot be ruled out — the same refusal `ConstantHoist` makes;
	 *  - the type may hold a static at all (`ConstantHoist.staticsForbidden` — Haxe's `@:generic`
	 *    forbids it) and is a CLASS declared in this file;
	 *  - the derived name occurs NOWHERE in the file. A brand-new name has no declaration to resolve,
	 *    so the question is genuinely textual: any occurrence at all is a member it would redefine, a
	 *    binding it would shadow, or a mention that would start reading as a reference to it;
	 *  - the policy governing the member the grammar renders accepts the name — emitting one `naming`
	 *    would immediately re-flag is worse than leaving the literal;
	 *  - no OTHER field of the same type claimed the name earlier in this pass (`RenameClaims`);
	 *  - the constants rank of the type has a splice point.
	 *
	 * The field's PRIVACY is not re-checked here: `run` reports only a non-exported field, and `fix`
	 * re-derives every fold from a span `run` produced.
	 */
	private function extractedConstant(
		site: CtorDefaultSite, source: String, file: String, tree: QueryNode, plugin: GrammarPlugin, index: Null<SymbolIndex>,
		inserts: Array<{ at: Int, text: String }>
	): Null<String> {
		final shape: RefShape = plugin.refShape();
		final owner: Null<String> = site.container.name;
		final annotation: Null<String> = site.typeAnnotation;
		if (owner == null || annotation == null || index == null || !isBareLiteral(site.defaultNode, shape)) return null;
		final reused: Null<String> = constantHoldingTheDefault(site, source, shape, annotation, plugin.lexicalRegions(source));
		if (reused != null) return reused;
		final ownerName: String = owner;
		final idx: SymbolIndex = index;
		final name: Null<String> = derivedConstantName(site.fieldName);
		final decl: Null<TypeDeclMatch> = RefactorSupport.uniqueTypeDeclNamed(tree, ownerName, shape.classDeclKinds ?? []);
		final support: Null<NamingSupport> = plugin.namingSupport();
		if (name == null || decl == null || support == null) return null;
		final newName: String = name;
		final member: Null<HoistedConstant> = support.hoistedConstant('final $newName:$annotation = ${site.defaultText};', true);
		if (member == null) return null;
		final emitted: HoistedConstant = member;
		final rule: Null<NamingRule> = ConstantHoist.constantRule(support.policyFor(file), emitted.mods);
		if (rule == null || !rule.format.match(newName)) return null;
		if (ConstantHoist.staticsForbidden(tree, decl, plugin)) return null;
		if (OccurrenceScan.referencedInRange(source, newName, 0, source.length, [])) return null;
		if (!idx.members.typeProvablyLacksMember(ownerName, newName, file)) return null;
		if (_runClaims.defers(ownerName, newName, idx)) return null;
		final at: Null<Int> = constantsRankSplice(site.container, decl, source, shape, ownerName, plugin.lexicalRegions(source));
		if (at == null) return null;
		_runClaims.claim(ownerName, newName, idx);
		stage(inserts, at, '\n\t${emitted.text}');
		return newName;
	}

	/** Whether `rank` is a STATIC IMMUTABLE field — the rank a reusable constant occupies, in either visibility. */
	private static inline function isConstantRank(rank: MemberRank): Bool {
		return rank == MemberRank.StaticPublicImmutableField || rank == MemberRank.StaticPrivateImmutableField;
	}

	/**
	 * The name of a constant the type ALREADY declares for this exact default — same verbatim
	 * initializer text AND same written type — or null when it declares none. Reusing it is what keeps
	 * one value from acquiring a second name; the TYPE has to match too, since a `Float` constant read
	 * where an `Int` is declared does not compile.
	 *
	 * Only an UNCONDITIONAL static immutable field qualifies: one declared inside a `#if` region exists
	 * in some builds and not others, and a reference to it would be a build-configuration error rather
	 * than a reuse.
	 */
	private static function constantHoldingTheDefault(
		site: CtorDefaultSite, source: String, shape: RefShape, annotation: String, regions: Array<LexRegion>
	): Null<String> {
		for (m in MemberSlots.collectMembers(site.container, source, shape, [], regions)) {
			final init: Null<QueryNode> = m.initNode;
			final name: Null<String> = m.node.name;
			final declSpan: Null<Span> = m.node.span;
			final initSpan: Null<Span> = init?.span;
			if (m.condition != null || !isConstantRank(m.rank) || init == null || name == null || declSpan == null || initSpan == null)
				continue;
			if (!isBareLiteral(init, shape) || source.substring(initSpan.from, initSpan.to) != site.defaultText) continue;
			if (CtorFieldFold.declaredTypeAnnotation(source, declSpan, initSpan, name) == annotation) return name;
		}
		return null;
	}

	/**
	 * Where a `private static` constant goes in `container` so `member-order` stays satisfied: just
	 * after the LAST unconditional member that outranks it, and at the top of the body when there is
	 * none. Splicing before the FIRST member — what `extract-constant` does — would put it ahead of a
	 * `public static` one, which is a member-order violation the emitting rule would be creating.
	 *
	 * A member inside a `#if` region is no anchor: the splice must land in every build.
	 */
	private static function constantsRankSplice(
		container: QueryNode, decl: TypeDeclMatch, source: String, shape: RefShape, ownerName: String, regions: Array<LexRegion>
	): Null<Int> {
		var at: Int = -1;
		for (m in MemberSlots.collectMembers(container, source, shape, [], regions)) if (
			m.condition == null && m.rank - MemberRank.StaticPrivateImmutableField <= 0
		)
			at = m.span.to;
		if (at >= 0) return at;
		final brace: Null<Int> = RefactorSupport.typeBodyBraceOffset(source, decl, ownerName, regions);
		return brace == null ? null : brace + 1;
	}

	/**
	 * Whether `node` is a BARE literal — a number, a boolean, or a string. Deliberately narrower than
	 * the fold's own move-safety whitelist, which also admits a negation and a dotted constant chain:
	 * naming those two is either wrong (`-5` is computed) or redundant (a chain is already a name).
	 */
	private static function isBareLiteral(node: QueryNode, shape: RefShape): Bool {
		return (shape.numericLiteralKinds ?? []).contains(node.kind) || node.kind == shape.boolLitKind
			|| (shape.stringLiteralKinds ?? []).contains(node.kind);
	}

	/** The constant name derived from a field name (`_cellsNumX` -> `CELLS_NUM_X_DEFAULT`), or null when nothing survives. */
	private static function derivedConstantName(fieldName: String): Null<String> {
		final core: String = SourceText.upperSnake(fieldName);
		final name: String = '$core$DEFAULT_SUFFIX';
		return core == '' || !SourceText.isIdentifier(name) ? null : name;
	}

	/** Record one member to splice at `at`, merging it into the insertion already pending there. */
	private static function stage(inserts: Array<{ at: Int, text: String }>, at: Int, text: String): Void {
		final slot: Null<{ at: Int, text: String }> = inserts.find(pending -> pending.at == at);
		if (slot == null)
			inserts.push({ at: at, text: text });
		else
			slot.text += text;
	}

}
