package anyparse.check;

import anyparse.check.Check.DefaultOff;
import anyparse.check.Check.Violation;
import anyparse.query.GrammarPlugin;
import anyparse.query.RefactorSupport;
import anyparse.query.SymbolIndex;
import anyparse.runtime.Span;

/**
 * Flags a private instance field whose CONSTANT declaration default is overwritten by exactly
 * one CONDITIONAL constructor write, and folds the pair into a single unconditional assignment
 * of a conditional value:
 *
 * ```haxe
 * private var _cellsX:Int = 20;
 * // ...
 * public function new(?palette:Array<Int>) {
 *     if (palette != null) _cellsX = palette.length;
 * }
 * // ->
 * private var _cellsX:Int;
 * // ...
 * public function new(?palette:Array<Int>) {
 *     _cellsX = palette != null ? palette.length : 20;
 * }
 * ```
 *
 * The MIRROR of `field-init-at-declaration`, which moves a context-free constructor init UP onto
 * the declaration. This one moves a declaration default DOWN into the constructor, and it is the
 * one direction that pays off precisely when the constructor already writes the field on some
 * paths: the two spellings of the same value stop being two writes, which is what lets
 * `prefer-final-field` finish the job (see the chain below). `Info`, and `DefaultOff` — the fold
 * trades a declaration-site default for a constructor-site ternary, which not every project reads
 * as an improvement; opt in with `"field-init-in-constructor": { "enabled": true }`.
 *
 * ## Why ONE assignment with a CONDITIONAL VALUE, and not "assign on every branch"
 *
 * The obvious alternative — leave the `if` and add an `else` assigning the default — is the shape
 * a language with definite-assignment analysis would let the compiler check. Haxe does NOT run
 * that analysis for a `final` FIELD. Measured on 4.3.7 with
 * `class V { final _d:Int; public function new(c:Bool) if (c) _d = 1; }`, which compiles
 * SILENTLY on EVERY target tried - `--interp`, `-js`, `--jvm` and `-cpp` (a full hxcpp build
 * and run, not just a typecheck) - and `_d` then reads as that target's ZERO value on the path
 * that skipped the write: `null` on `--interp`, `undefined` on `-js`, `0` on `--jvm` and `-cpp`. The
 * only net is the `@:nullSafety` meta, and in EITHER mode: the bare / `Loose` form diagnoses the
 * shape exactly as `Strict` does (two errors - the field is used before initialization, and a
 * non-nullable field wants an initial value or a constructor assignment). It stays a per-file
 * opt-in all the same. Of the 805 files in the tree that motivated this rule, 53 carry
 * `@:nullSafety(Strict)` and 415 the bare form - leaving 337 with no net at all, the motivating
 * file among them. So a fix emitting
 * branch-per-arm assignments would have its COMPLETENESS checked by nothing at all. The
 * conditional-value form proves completeness structurally: there is exactly one assignment and it
 * always runs.
 *
 * ## The chain this closes
 *
 * The full cleanup of a CAPS-named mutable field holding a conditional default takes four steps,
 * and this rule is the one that was missing:
 *
 *  1. `naming` renames the UPPER_SNAKE instance field to the project's field convention;
 *  2. THIS rule folds `default + conditional write` into one unconditional conditional-valued
 *     assignment, leaving the field with exactly ONE write;
 *  3. `prefer-final-field` now sees that single unconditional constructor assignment and rewrites
 *     `var` to `final` — it is CORRECTLY silent before the fold, whose two writes (initializer plus
 *     constructor) fail its sole-write gate;
 *  4. `magic-number` reports the literal, which the fold has just moved INSIDE a function and hence
 *     into that rule's scope for the first time, so a human can name it as a `static inline final`.
 *     That last step stays human: `magic-number` is report-only by design.
 *
 * ## What is flagged
 *
 * Every gate is `RefactorSupport.ctorConditionalDefaultTernaryEdits`'s, so `run` and `fix` cannot
 * disagree about a candidate: the non-null edit list IS the finding. In outline — a plain
 * non-static `var` with a MOVE-SAFE constant default, a single constructor, exactly one top-level
 * `else`-less `if` whose then-branch OPENS with the field's assignment, a side-effect-free
 * condition whenever that `if` survives the fold, no early exit and no mention of the field before
 * the `if`, every `super(...)` after it, no `#if` region on the path, no self-referencing value, no
 * comment in a regenerated byte range, and no other write to the field name anywhere in the file.
 *
 * An assignment sitting DEEPER in the branch is refused rather than reordered — and reaches the
 * same end state one `--fix` pass later, once the assignment ahead of it has moved out. That is how
 * the motivating shape (two fields written under one `if`) converges: two passes, one field each,
 * and the `if` disappears with the second.
 *
 * ## Scope
 *
 * PUBLIC fields are out of scope: the fold widens the window in which the field holds its
 * type's zero value rather than its default, and outside code cannot be proven not to read it
 * there. STATIC fields are out of scope for the same reason `field-init-at-declaration` skips
 * them — a static's init timing is unrelated to instance construction. Cross-file soundness
 * (an `@:access` grantee, a subtype writer) is not proven here beyond the conservative
 * whole-file write scan; the shape's other writes would have to precede the constructor to
 * matter, which no writer of an instance field can do.
 */
@:nullSafety(Strict)
final class FieldInitInConstructor implements Check implements DefaultOff {

	private static inline final MESSAGE: String =
		'this field default is overwritten by one conditional constructor write - fold the pair into a single unconditional assignment of a conditional value';

	public function new() {}

	public function id(): String {
		return 'field-init-in-constructor';
	}

	public function description(): String {
		return 'a field default overwritten by one conditional constructor write - foldable into one assignment of a conditional value';
	}

	public function run(files: Array<{ file: String, source: String }>, plugin: GrammarPlugin): Array<Violation> {
		final violations: Array<Violation> = [];
		RefactorSupport.eachFieldMember(files, plugin, (owner, field, source, file, exported) -> {
			final span: Null<Span> = field.span;
			if (
				!exported && span != null && RefactorSupport.ctorConditionalDefaultTernaryEdits(source, span, plugin) != null
			) violations.push({
				file: file,
				span: span,
				rule: id(),
				severity: Severity.Info,
				message: MESSAGE
			});
		});
		return violations;
	}

	/**
	 * Re-derive each flagged field's fold from its violation span and emit its edits. The
	 * producer is the same predicate `run` reported on, so a finding either fixes exactly as it
	 * was reported or (its source having changed under it) yields nothing.
	 */
	public function fix(
		source: String, violations: Array<Violation>, plugin: GrammarPlugin, ?index: SymbolIndex
	): Array<{ span: Span, text: String }> {
		final edits: Array<{ span: Span, text: String }> = [];
		for (v in violations) {
			final span: Null<Span> = v.span;
			if (span == null) continue;
			final fold: Null<Array<{ span: Span, text: String }>> =
				RefactorSupport.ctorConditionalDefaultTernaryEdits(source, span, plugin);
			if (fold != null) for (edit in fold) edits.push(edit);
		}
		return RefactorSupport.dropContainedEdits(edits);
	}

}
