package anyparse.query.format.json;

/**
 * Marker class for the macro-generated ByName parser of `HaxelibJson`.
 * Populated entirely by the ByName lowering codepath — the class body
 * stays empty, as with every other `@:build(buildParser(...))` marker in
 * the project.
 *
 * Used by `HaxelibResolver.sourceDirFrom` to parse a library's
 * `haxelib.json` content into the single `classPath` key it needs.
 * `parse` throws on malformed or non-object JSON; the caller catches and
 * returns null (the library is skipped).
 */
@:build(anyparse.macro.Build.buildParser(anyparse.query.format.json.HaxelibJson))
@:nullSafety(Strict)
class HaxelibJsonParser {}
