package anyparse.query.format.json;

/**
 * Marker class for the macro-generated ByName parser of `LintReportJson`.
 * Populated entirely by the ByName lowering codepath — the class body stays
 * empty, as with every other `@:build(buildParser(...))` marker in the
 * project.
 *
 * Used by `anyparse.query.LintDiff.parseReport` to read an
 * `apq lint --format json --all` snapshot. `parse` throws on malformed JSON,
 * on a wrong-typed modelled key and on a record missing one of the four keys
 * `LintFindingJson` models; `apq lint-diff` catches that and exits with a
 * runtime error naming the file, since a half-read baseline would understate
 * the blast radius.
 */
@:build(anyparse.macro.Build.buildParser(anyparse.query.format.json.LintReportJson))
@:nullSafety(Strict)
class LintReportJsonParser {}
