package anyparse.query.format.json;

/**
 * Marker class for the macro-generated ByName parser of `LintTruthJson`, the ground truth `apq lint-score` reads.
 * `parse` throws on malformed JSON, a wrong-typed key or a missing required one; `LintScore.validate` then refuses
 * what the schema cannot say (an unknown verdict, a `dup-of` naming nothing, a key labelled twice).
 */
@:build(anyparse.macro.Build.buildParser(anyparse.query.format.json.LintTruthJson))
@:nullSafety(Strict)
class LintTruthJsonParser {}
