package anyparse.query.format.json;

/**
 * Marker class for the macro-generated ByName parser of `SweepSnapshot`.
 * Populated entirely by the ByName lowering codepath — the class body
 * stays empty, as with every other `@:build(buildParser(...))` marker in
 * the project.
 *
 * Used by `Cli.loadSweepJson` and `Cli.loadSweepFixtureStatus` to parse
 * `bin/.last-sweep.json` / `.prev-sweep.json`. `parse` throws on malformed
 * JSON or a wrong-typed modelled key; both callers catch that and fail
 * soft to their "no baseline" degradation.
 */
@:build(anyparse.macro.Build.buildParser(anyparse.query.format.json.SweepSnapshot))
@:nullSafety(Strict)
class SweepSnapshotParser {}
