package anyparse.runtime;

import anyparse.runtime.MemoEntry.MemoExit;

/**
 * Runtime parser context threaded through generated parsers as the
 * first argument to every helper. Owns everything that
 * is mutable during a parse — input, position, error accumulator,
 * cache, indent stack, named captures, cancellation callback.
 *
 * Thread safety by construction: there is zero global mutable state in
 * the runtime. Concurrent parses use independent `Parser` instances and
 * never touch each other's fields.
 *
 * Phase 1 uses only `input` and `pos`. `errors`, `cache`, `indentStack`,
 * `captures`, and `cancelled` are declared so that generated code in
 * Phase 2 and beyond has a stable target; their behaviour is stubbed
 * (empty collections, `NoOpCache`, always-false cancellation) until the
 * corresponding strategies land.
 */
@:nullSafety(Strict)
final class Parser {

	/**
	 * Farthest-failure tracker (PEG "max position" heuristic). Every
	 * failed terminal match records its attempt position here; the
	 * deepest one survives backtracking and is almost always the real
	 * syntax-error locus. The public entry point re-surfaces a
	 * top-level `ParseError` at `maxFailPos` instead of the
	 * outermost-rule position (which collapses to the file head), so
	 * recon tooling sees the innermost blocker, not "expected <root>".
	 *
	 * `-1` means no terminal was ever attempted (degenerate input).
	 */
	public var maxFailPos(default, null): Int = -1;

	public var maxFailExpected(default, null): Null<String> = null;

	/** How many times a `@:memo` rule actually ran — a replay does not count. */
	public var memoRuns(default, null): Int = 0;

	public final errors: Array<ParseError> = [];
	public final indentStack: Array<Int> = [];
	public final captures: Map<String, String> = [];

	/**
	 * Input keys the schema had no field for, in document order.
	 * Filled by generated ByName parsers whose format declares
	 * `onUnknown = Skip` — the value is still consumed and discarded,
	 * so parse behaviour is unchanged; the record is what lets the
	 * boundary that knows where the input came from say "you wrote a
	 * key I do not know" instead of silently ignoring it.
	 * Empty for every other codepath.
	 *
	 * Append-only, like `errors` and `maxFailPos`: a record made inside a
	 * PEG alternative that later backtracks is NOT unwound. No ByName
	 * struct sits under a backtracking alternative today (every recording
	 * schema is a JSON config whose struct is the root or an array
	 * element), so nothing observes it — a reader that changes that owes
	 * itself a rollback.
	 */
	public final unknownFields: Array<UnknownField> = [];

	public final input: Input;

	public var pos: Int = 0;

	// Deliberately mutable: the injection point for the planned cache
	// layer (swap NoOpCache for a real ParseCache per parse session).
	public var cache: ParseCache = NoOpCache.instance; // noqa: prefer-final-public-field
	public var cancelled: () -> Bool = alwaysFalse;

	/**
	 * Trivia carry-over slot (slice ω₆b). Generated Trivia-mode parsers
	 * stash a leading run captured between an `@:optional @:kw` commit
	 * point and its sub-rule call here; the next `collectTrivia` drains
	 * it as a prefix. Null outside Trivia-mode builds and between drains.
	 */
	public var pendingTrivia: Null<PendingTrivia> = null;

	/**
	 * Packrat memo of the `@:memo` grammar rules: generated rule key plus the
	 * pending-trivia content (`memoKey`), then start position. Scoped to this
	 * parse like every other field here: an entry is valid only for this
	 * `input`.
	 */
	private final _memo: Map<String, Map<Int, MemoEntry>> = [];

	public function new(input: Input) {
		this.input = input;
	}

	/**
	 * The memo key of rule `rule` under the current `pendingTrivia`. A rule's
	 * run reads the stash (it drains it, and operator commits read its flags),
	 * so the stash's content is part of the input the key must name.
	 */
	public function memoKey(rule: String): String {
		final pending: Null<PendingTrivia> = pendingTrivia;
		if (pending == null) return rule;
		final buf: StringBuf = new StringBuf();
		buf.add(rule);
		buf.add(pending.blankBefore ? '|b' : '|-');
		buf.add(pending.blankAfterLeadingComments ? 'a' : '-');
		buf.add(pending.newlineBefore ? 'n' : '-');
		for (comment in pending.leadingComments) {
			buf.add('|');
			buf.add(comment.length);
			buf.add(':');
			buf.add(comment);
		}
		return buf.toString();
	}

	/**
	 * Replay the recorded run of `key` from `start`, or return null when there
	 * is none. A replay leaves `pos` and `pendingTrivia` exactly as the run did,
	 * and hands back the entry so the caller returns its value or rethrows its
	 * error.
	 */
	public function memoReplay(key: String, start: Int): Null<MemoEntry> {
		final byPos: Null<Map<Int, MemoEntry>> = _memo[key];
		final entry: Null<MemoEntry> = byPos == null ? null : byPos[start];
		if (entry == null) return null;
		pos = entry.end;
		final handed: Null<PendingTrivia> = pendingTrivia;
		final after: Null<PendingTrivia> = entry.handedAfter;
		if (handed != null && after != null) {
			handed.blankBefore = after.blankBefore;
			handed.blankAfterLeadingComments = after.blankAfterLeadingComments;
			handed.newlineBefore = after.newlineBefore;
			for (comment in after.leadingComments) handed.leadingComments.push(comment);
		}
		final own: Null<PendingTrivia> = entry.own;
		pendingTrivia = if (entry.exit == Handed)
			handed
		else if (own != null)
			copyTrivia(own, 0)
		else
			null;
		return entry;
	}

	/**
	 * Record the run of `key` from `start` that was handed the stash `handed`
	 * (holding `handedComments` comments then) and just returned `value` or
	 * threw `error`. A run whose trivia effect a replay could not reproduce —
	 * the handed stash lost comments — is not recorded.
	 */
	public function memoRecord(
		key: String, start: Int, handed: Null<PendingTrivia>, handedComments: Int, value: Null<Dynamic>, error: Null<ParseError>
	): Void {
		memoRuns++;
		if (handed != null && handed.leadingComments.length < handedComments) return;
		final left: Null<PendingTrivia> = pendingTrivia;
		final exit: MemoExit = if (left == null)
			Nothing
		else if (left == handed)
			Handed
		else
			Own;
		final entry: MemoEntry = new MemoEntry(
			pos, value, error, handed == null ? null : copyTrivia(handed, handedComments), exit,
			left == null || exit == Handed ? null : copyTrivia(left, 0)
		);
		var byPos: Null<Map<Int, MemoEntry>> = _memo[key];
		if (byPos == null) {
			byPos = [];
			_memo[key] = byPos;
		}
		byPos[start] = entry;
	}

	/**
	 * Record a failed terminal match at `pos` expecting `expected`,
	 * keeping only the deepest position seen. Called from the generated
	 * `matchLit` failure paths; cheap (one compare on the failure path,
	 * success path untouched).
	 */
	public function recordFail(failPos: Int, expected: String): Void {
		if (failPos <= maxFailPos) return;
		maxFailPos = failPos;
		maxFailExpected = expected;
	}

	/**
	 * Record an input key at `keyPos` that matched no schema field,
	 * carrying the `known` field names so a consumer can suggest the
	 * one that was probably meant. Called from the generated ByName
	 * dispatch's unknown-key arm; never on a success path.
	 */
	public function recordUnknownField(key: String, keyPos: Int, known: Array<String>): Void {
		unknownFields.push(new UnknownField(key, keyPos, known));
	}

	private static function alwaysFalse(): Bool {
		return false;
	}

	/** A detached copy of `t`, keeping its comments from index `from` on. */
	private static function copyTrivia(t: PendingTrivia, from: Int): PendingTrivia {
		return {
			blankBefore: t.blankBefore,
			blankAfterLeadingComments: t.blankAfterLeadingComments,
			newlineBefore: t.newlineBefore,
			leadingComments: t.leadingComments.slice(from)
		};
	}

}
