package anyparse.runtime;

/**
 * One input key that the schema has no field for, recorded by the
 * generated ByName parser instead of being dropped without trace.
 *
 * Format-neutral: any `@:schema` whose format declares
 * `fieldLookup = ByName` and `onUnknown = Skip` collects these on the
 * `Parser` context, and the boundary that knows where the input came
 * from decides whether to report them (see
 * `HaxeFormatConfigDiagnostics` for the `hxformat.json` consumer).
 * Collecting is not reporting: a parser stays a pure function of its
 * input, and a consumer that does not look at `unknownFields` behaves
 * exactly as before.
 *
 * `known` is the schema's own field list at the point the key was
 * rejected — the vocabulary a suggestion can be drawn from, which the
 * consumer has no other way to obtain at runtime.
 */
@:nullSafety(Strict)
final class UnknownField {

	/** Largest edit distance still worth suggesting — past two, a near-miss stops being distinguishable from an unrelated name. */
	private static inline final MAX_DISTANCE: Int = 2;

	public final key: String;

	/** Offset where the key TOKEN begins in the parsed input — the opening quote, in a quoted-key format. */
	public final pos: Int;

	public final known: Array<String>;

	public function new(key: String, pos: Int, known: Array<String>) {
		this.key = key;
		this.pos = pos;
		this.known = known;
	}

	/**
	 * The schema field this key most plausibly meant, or `null` when
	 * nothing is close enough. A case-only difference wins outright;
	 * otherwise the nearest name within `MAX_DISTANCE` edits is taken,
	 * so an unimplemented-but-real key (`mapWrap` next to `arrayWrap`)
	 * draws no suggestion while a transposition (`arrayWarp`) does.
	 */
	public function suggestion(): Null<String> {
		final lower: String = key.toLowerCase();
		var best: Null<String> = null;
		var bestDistance: Int = MAX_DISTANCE + 1;
		for (candidate in known) {
			final d: Int = EditDistance.between(lower, candidate.toLowerCase(), bestDistance);
			// Distance 0 is a case-only difference, which is never a
			// closer call than itself — take it and stop scanning.
			if (d == 0) return candidate;
			if (d < bestDistance) {
				bestDistance = d;
				best = candidate;
			}
		}
		return best;
	}

}
