package anyparse.check.config;

/**
 * Marker class for the macro-generated ByName parser of `ApqLintConfig`.
 * Populated entirely by the ByName lowering codepath — the class body stays
 * empty, as with every other `@:build(buildParser(...))` marker in the
 * project.
 *
 * Used by `LintConfig.parse` as the single reader of an `apqlint.json`: this
 * parser builds the typed `ApqLintConfig`, `LintConfig` maps it onto the
 * per-rule toggles / severity overrides / option bags the checks read.
 * `parse` throws on malformed or wrong-shaped input; `LintConfig.parse`
 * catches and degrades to an empty (no-op) config, so a broken file never
 * fails the lint.
 */
@:build(anyparse.macro.Build.buildParser(anyparse.check.config.ApqLintConfig))
@:nullSafety(Strict)
class ApqLintConfigParser {}
