# fixture-cache.sh — sourced, never run: the `haxe` shim that puts
# `testkit.FixtureCompileCache` in front of the probe compiles of a suite run.
#
# Two callers, one store, kept ACROSS runs under
#     ${APQ_SUITE_FIXTURE_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/anyparse/fixture-cache}:
#   - tools/mutation-check.sh, every track of a run sharing it: a mutation
#     changes what the engine does with the compiler's answer, not the answer
#     (a mutated probe macro is a different key).
#   - tools/suite-shard.sh: the fixture
#     compiles are most of the suite's CPU (MemberReachFactsTest alone ran 1007
#     of them, 265 of its 271 s) and an engine edit that leaves the probe
#     macros alone leaves every key alone. An entry no run has hit for
#     FC_MAX_AGE_DAYS days is deleted at the next run's start.
#
# Why a kept cache is still sound is the class doc of FixtureCompileCache: the
# key is every input by content — the probe macros' own source included, so an
# edit of the facts macro is a different key — and only a whitelisted compile
# whose every path stays inside its roots is ever replayed. What a kept cache
# adds is the compiler install outliving a run, so the stamp names the binary
# by its resolved path, `-version`, size and mtime: an upgrade, or a rebuild in
# place, is a different stamp.
#
# fc_shim <repo> <entries-dir> <bin-dir> [<tally-file>]
#   builds the replay program (once per content of FixtureCompileCache.hx, kept
#   beside the entries), writes <bin-dir>/haxe and returns 0, or prints why not
#   on stderr and returns 1 — the caller then runs every compile for real.

FC_MAX_AGE_DAYS=${FC_MAX_AGE_DAYS:-7}

fc_real_haxe() {
    local real link
    real=$(command -v haxe || true)
    [ -n "$real" ] || return 1
    real=$(cd -P "$(dirname "$real")" && pwd)/$(basename "$real")
    # Follow a symlinked compiler to the binary it names: the stamp is the
    # INSTALL, not a PATH entry that may later point elsewhere.
    while [ -L "$real" ]; do
        link=$(readlink "$real")
        case "$link" in
            /*) real=$link ;;
            *) real=$(cd -P "$(dirname "$real")/$(dirname "$link")" && pwd)/$(basename "$link") ;;
        esac
    done
    printf '%s\n' "$real"
}

fc_shim() {
    local repo=$1 entries=$2 bindir=$3 tally=${4:-}
    local real stamp source sum js tmp
    real=$(fc_real_haxe) || { echo "fixture-cache: no haxe on PATH" >&2; return 1; }
    mkdir -p "$entries" "$bindir" || return 1
    source="$repo/test/testkit/FixtureCompileCache.hx"
    sum=$(shasum -a 256 "$source" | cut -c1-16)
    js="$entries/fixture-cache-$sum.js"
    if [ ! -f "$js" ]; then
        tmp="$js.$$.tmp"
        if ! ( cd "$repo" && haxe -cp test -main testkit.FixtureCompileCache -lib hxnodejs -D js-es=6 -js "$tmp" ) \
                > "$entries/build-$sum.log" 2>&1; then
            rm -f "$tmp"
            echo "fixture-cache: the replay program could not be built ($entries/build-$sum.log)" >&2
            return 1
        fi
        mv -f "$tmp" "$js"
    fi
    # in use: a concurrent run's fc_prune must not take it away mid-run
    touch "$js"
    stamp="$real $("$real" -version 2>&1) $(stat -f '%z %m' "$real" 2> /dev/null || stat -c '%s %Y' "$real")"
    # Paths are baked in rather than exported: a test that spawns the compiler
    # under an environment of its own must still reach the cache.
    {
        printf '#!/bin/bash\n'
        printf '# Generated by tools/fixture-cache.sh: probe compiles go through the fixture cache.\n'
        # fc_std_injection's variable is for the engine's StdResolver alone: the compiler,
        # and the cache's key, see the environment the run had without the shim.
        printf 'if [ -n "${APQ_FC_STD_INJECTED:-}" ]; then unset HAXE_STD_PATH APQ_FC_STD_INJECTED; fi\n'
        printf 'case "$*" in\n'
        printf '    *anyparse.check.TypedFactsMacro.run\\(*|*AnyparseReachDefinesProbe.*)\n'
        printf '        APQ_FIXTURE_CACHE_HAXE=%q APQ_FIXTURE_CACHE_STAMP=%q APQ_FIXTURE_CACHE_DIR=%q APQ_FIXTURE_CACHE_TALLY=%q exec node %q "$@" ;;\n' \
            "$real" "$stamp" "$entries" "${tally:-$entries/tally}" "$js"
        printf 'esac\n'
        printf 'exec %q "$@"\n' "$real"
    } > "$bindir/haxe"
    chmod +x "$bindir/haxe"
}

# fc_std_injection: the std directory to hand the test processes as
# HAXE_STD_PATH (with APQ_FC_STD_INJECTED=1, which the shim strips again before
# the compiler or the cache sees either), or nothing when no injection is needed.
#
# Why: the engine's StdResolver finds the std BESIDE `which haxe`, symlinks
# resolved — and with the shim first on the PATH, `which haxe` is the shim,
# which has no std beside it. Discovery then falls to its fixed list, whose
# first entry is /usr/local/lib/haxe/std: on a machine carrying a second Haxe
# install there, every run under the shim indexed ANOTHER compiler's std than a
# plain run, and tests whose answer turns on the std read differently (seen as
# FactsFixGateE2ETest collateral on every TypedFactsWalk arm, with the cache on
# and off alike — any `haxe` wrapper on the PATH did it). So the runner computes
# the std a plain run's StdResolver would find, by the same rule, and names it
# through HAXE_STD_PATH, the resolver's first candidate. Nothing is injected
# when HAXE_STD_PATH is already set (the resolver and the compiler then share it
# either way) or when the compiler has no std beside it (both runs fall to the
# fixed list alike).
fc_std_injection() {
    local real dir parent
    [ -z "${HAXE_STD_PATH:-}" ] || return 0
    real=$(fc_real_haxe) || return 0
    dir=$(dirname "$real")
    parent=$(dirname "$dir")
    # StdResolver.siblingStdOf: `<bin>/../std`, else Homebrew's `<bin>/../lib/haxe/std`,
    # both spelled as Path.normalize spells them (textually, no symlink resolved)
    if [ -d "$parent/std" ]; then
        printf '%s\n' "$parent/std"
    elif [ -d "$parent/lib/haxe/std" ]; then
        printf '%s\n' "$parent/lib/haxe/std"
    fi
}

# fc_prune <entries-dir>: drop the entries no run has hit for FC_MAX_AGE_DAYS
# days, and replay programs built from a FixtureCompileCache.hx that old.
fc_prune() {
    [ -d "$1" ] || return 0
    find "$1" -maxdepth 1 -type f \( -name '*.json.gz' -o -name 'fixture-cache-*.js' -o -name 'build-*.log' -o -name '*.tmp' \) \
        -mtime +"$FC_MAX_AGE_DAYS" -delete 2> /dev/null || true
}

# fc_tally <tally-file>: "N hit, M miss, K pass" — what one run's compiles did.
fc_tally() {
    [ -f "$1" ] || return 0
    sort "$1" | uniq -c | awk '{ printf "%s%s %s", sep, $1, $2; sep = ", " } END { if (NR) print "" }'
}
