package unit;

import testkit.TestRegistry;
import utest.Assert;
import utest.Test;

using Lambda;

/**
 * Pins the GENERATED registration layer — `testkit.TestRegistry`, built by
 * `testkit.TestDiscovery`.
 *
 * `test/RunTests.hx` used to carry 758 hand-written `addCase(new X())` lines
 * and their 758 imports. The cost was never the typing: a class whose line
 * was never added ran nowhere and said nothing, and no gate had an artifact
 * to compare against. This class is that artifact.
 *
 * THE SHAPE IS T130's — the shrinkage IS the acceptance test. The registered
 * NAMES are pinned, so narrowing the discovery predicate by one class turns the
 * suite red instead of quietly running one fewer, and the failure names the
 * class that vanished. That trades one silent failure for one loud chore:
 * adding a test class now needs its name written into `REGISTERED_CLASSES`,
 * and the failure message says so.
 *
 * What is deliberately NOT pinned here is per-METHOD parity. utest decides
 * what a fixture is (`!isStatic` and a `test`/`spec` name prefix) and
 * `TestDiscovery` asks utest's own question, so the two cannot disagree by
 * construction; the per-class per-method census that proved it across the
 * switch-over is in the slice report, not in a fixture that would have to be
 * regenerated on every test added.
 */
@:nullSafety(Strict)
class TestDiscoveryParityTest extends Test {

	/**
	 * `utest.Test` subclasses carrying no fixture of their own or inherited.
	 *
	 * Registering one would be a no-op — `Runner.addITest` builds no fixture
	 * for it either and stores no entry — so discovery reports them instead
	 * of registering them, and this pin is what keeps "reports" from decaying
	 * into "silently drops".
	 *
	 * Five are shared bases for one check's tests. The sixth,
	 * `unit.grammar.haxe.HxTestHelpers`, reads like the surprise and is not
	 * one: 127 `Hx*` test classes extend it, so its `extends utest.Test` is
	 * what makes each of THEM a `utest.ITest`. It carries parse / round-trip
	 * helpers and no fixture of its own, which is exactly why discovery
	 * reports it rather than registering it.
	 */
	private static final EXPECTED_BASE_CLASSES: Array<String> = [
		'unit.check.ExplicitLocalTypeCheckTestBase',
		'unit.check.FoldStringLiteralsCheckTestBase',
		'unit.check.NamingCheckTestBase',
		'unit.check.RedundantParensOperandArmsTestBase',
		'unit.check.TrivialGetterCheckTestBase',
		'unit.grammar.haxe.HxTestHelpers'
	];

	/**
	 * The fully-qualified name of every class discovery must register, sorted.
	 *
	 * A COUNT was the obvious shape and it is the one representation that merges
	 * silently and wrongly. Measured on 2026-09-04: the base was 768, two slices
	 * each added ONE test class, and each wrote 769. Git took the second 769 as
	 * text already applied — no conflict, both merges clean — and the tree then
	 * claimed 769 while registering 770. A scalar cannot do better: every branch
	 * that increments writes the same token, so a merge has nothing to disagree
	 * about. A floor (`>= N`) merges harmlessly too, but it cannot name what
	 * vanished and does not notice a class removed without a bump; the user chose
	 * the list.
	 *
	 * Two branches that each add a class either merge BOTH lines or conflict
	 * loudly, and the failure message names the missing or surplus class instead
	 * of subtracting two integers. The cost is one line in the diff of every
	 * test-adding slice, which is the point.
	 *
	 * REGENERATE with `node bin/test.js --list-classes | LC_ALL=C sort` — and
	 * REBUILD `bin/test.js` first. The probe reads the binary, not the tree: right
	 * after a merge it answered 769 for a tree that registers 770, so the
	 * verification step itself lied until `haxe test-js.hxml` had run. `LC_ALL=C`
	 * is not decoration either: the assertion sorts the registry with
	 * `Reflect.compare`, which is code-unit order, while a default macOS `sort`
	 * collates by locale and puts a different list in front of you.
	 */
	private static final REGISTERED_CLASSES: Array<String> = [
		'unit.DeadTestGuardTest',
		'unit.DiscoveryOnlyProbeTest',
		'unit.ExtensionMethodsExtractionTest',
		'unit.LexicalRegionAgreementTest',
		'unit.SpanModeProbe',
		'unit.TestDiscoveryParityTest',
		'unit.check.AlwaysNullComparisonTest',
		'unit.check.AnonTypeDupCheckTest',
		'unit.check.AssignmentInConditionCheckTest',
		'unit.check.AsymmetricBranchBracesCheckTest',
		'unit.check.AvoidDynamicBagCheckTest',
		'unit.check.AvoidDynamicBagFixTest',
		'unit.check.AvoidDynamicBagOracleE2ETest',
		'unit.check.AvoidDynamicCheckTest',
		'unit.check.AvoidDynamicNarrowFixTest',
		'unit.check.AvoidDynamicRiskyFixE2ETest',
		'unit.check.BuildMacroMetaSeamTest',
		'unit.check.BuiltinFixClassCensusTest',
		'unit.check.CasePatternSeparatorCheckTest',
		'unit.check.CatchDynamicCheckTest',
		'unit.check.CollapseNestedSwitchCheckTest',
		'unit.check.CollapsibleElseIfCheckTest',
		'unit.check.CollapsibleIfCheckTest',
		'unit.check.ComparisonToBooleanCheckTest',
		'unit.check.CompilerOracleE2ETest',
		'unit.check.ComplexityCheckTest',
		'unit.check.CondAssignMergeCheckTest',
		'unit.check.CondRegionLivenessTest',
		'unit.check.CondRegionMergeCheckTest',
		'unit.check.ConstantConditionCheckTest',
		'unit.check.CoreApiConformanceGateTest',
		'unit.check.DeadBinderCounterLoopCheckTest',
		'unit.check.DeadCodeCheckTest',
		'unit.check.DeadNullCoalescingTest',
		'unit.check.DeadNullGuardTest',
		'unit.check.DeadSafeNavTest',
		'unit.check.DeadStoreTest',
		'unit.check.DefaultRepeatedArgumentCheckTest',
		'unit.check.DefiniteAssignmentGuardTest',
		'unit.check.DocCommentContinuationCheckTest',
		'unit.check.DocCoverageCheckTest',
		'unit.check.DoubleNegationCheckTest',
		'unit.check.DuplicateCaseCheckTest',
		'unit.check.DuplicateCaseCondBranchTest',
		'unit.check.DuplicateCodeCheckTest',
		'unit.check.DuplicateCodeCrossFileCheckTest',
		'unit.check.DuplicateTernaryBranchesCheckTest',
		'unit.check.EmptyBlockCheckTest',
		'unit.check.EmptyCaseArmCheckTest',
		'unit.check.EmptyCommentCheckTest',
		'unit.check.EmptyDocTagCheckTest',
		'unit.check.EmptyStatementCheckTest',
		'unit.check.EnglishCommentsCheckTest',
		'unit.check.ExplicitLocalTypeCheckTest',
		'unit.check.ExplicitLocalTypeIndexAccessTest',
		'unit.check.ExplicitLocalTypeOracleAbstainTest',
		'unit.check.ExplicitLocalTypeOracleE2ETest',
		'unit.check.ExplicitLocalTypeOracleTest',
		'unit.check.ExplicitLocalTypeParenInitTest',
		'unit.check.ExplicitLocalTypePrinterTest',
		'unit.check.ExplicitLocalTypeReadFixTest',
		'unit.check.ExplicitTypeCheckTest',
		'unit.check.ExplicitTypeReturnOracleTest',
		'unit.check.ExtractRepeatedExpressionTest',
		'unit.check.FieldInitAtDeclarationCheckTest',
		'unit.check.FieldInitInConstructorCheckTest',
		'unit.check.FieldMutabilityMacroGateTest',
		'unit.check.FixVerifierBisectTest',
		'unit.check.FixVerifierCoverageE2ETest',
		'unit.check.FixVerifierGroupE2ETest',
		'unit.check.FixVerifierGroupTest',
		'unit.check.FixVerifierProbeRefusalE2ETest',
		'unit.check.FixVerifierScopeE2ETest',
		'unit.check.FoldStringLiteralsCandidateGateTest',
		'unit.check.FoldStringLiteralsCheckTest',
		'unit.check.FoldStringLiteralsCondRegionTest',
		'unit.check.FoldStringLiteralsWidthCheckTest',
		'unit.check.FragmentedDocCommentCheckTest',
		'unit.check.FrameworkContractTest',
		'unit.check.GuardContinueCheckTest',
		'unit.check.GuardReturnCheckTest',
		'unit.check.HaxeSpawnTest',
		'unit.check.HoistBranchStringAffixCheckTest',
		'unit.check.HoistEmbeddedAssignmentCheckTest',
		'unit.check.IdenticalOperandsCheckTest',
		'unit.check.IfFalseDeadCodeCheckTest',
		'unit.check.ImportBlockOrderCheckTest',
		'unit.check.ImportOutsideGuardCheckTest',
		'unit.check.ImpossibleCastTest',
		'unit.check.ImpossibleIsCheckTest',
		'unit.check.InlineConstantCheckTest',
		'unit.check.InvertNegatedIfElseCheckTest',
		'unit.check.JoinArrayPushesCheckTest',
		'unit.check.JoinBranchCallCheckTest',
		'unit.check.JoinDeclarationAssignmentCheckTest',
		'unit.check.JoinOverrideChainCheckTest',
		'unit.check.JoinReturnCheckTest',
		'unit.check.JoinSingleUseLocalCheckTest',
		'unit.check.JoinStringAppendCheckTest',
		'unit.check.LambdaBranchingBodyBlockCheckTest',
		'unit.check.LintConfigInheritanceTest',
		'unit.check.LintConfigTest',
		'unit.check.LintFixDeclineWiringSliceTest',
		'unit.check.LintFixFollowUpRoundTest',
		'unit.check.LintLanguageVersionGateTest',
		'unit.check.LintModuleSecondaryTypeSliceTest',
		'unit.check.LintReportChannelSliceTest',
		'unit.check.LintScopeGateTest',
		'unit.check.LintSliceTest',
		'unit.check.LintUnusedImportDottedSliceTest',
		'unit.check.LintUnusedImportResolutionScopeTest',
		'unit.check.LintUsingSubmoduleExtensionTest',
		'unit.check.ListenerSymmetryCheckTest',
		'unit.check.LoopGuardCheckTest',
		'unit.check.MagicNumberCheckTest',
		'unit.check.MapKeysLookupCheckTest',
		'unit.check.MemberOrderCheckTest',
		'unit.check.MemberOrderMessageTest',
		'unit.check.MemberOrderModifierSpanSliceTest',
		'unit.check.MessageMaskTest',
		'unit.check.MisplacedTypeDocCheckTest',
		'unit.check.MisplacedTypeDocGuardedMetaTest',
		'unit.check.MissingVisibilityCheckTest',
		'unit.check.ModifierOrderCheckTest',
		'unit.check.NamingCheckAltSpellingFixTest',
		'unit.check.NamingCheckBranchTwinFixTest',
		'unit.check.NamingCheckCrossFileFixTest',
		'unit.check.NamingCheckHoistFixTest',
		'unit.check.NamingCheckLocalFixTest',
		'unit.check.NamingCheckMemberFixTest',
		'unit.check.NamingCheckTest',
		'unit.check.NarrowLocalScopeCheckTest',
		'unit.check.NoUnderscorePrefixCheckTest',
		'unit.check.NullDereferenceTest',
		'unit.check.NullableSwitchMissingNullCheckTest',
		'unit.check.OperatorOverloadGateTest',
		'unit.check.OptionalParamShorthandCheckTest',
		'unit.check.OracleBatchRevertReasonTest',
		'unit.check.OracleCacheTest',
		'unit.check.OracleCoverageTest',
		'unit.check.OracleFixImportLeakTest',
		'unit.check.OrphanAccessorCheckTest',
		'unit.check.OversizedTypeCheckTest',
		'unit.check.PossibleNullDereferenceTest',
		'unit.check.PreferArrayLiteralCheckTest',
		'unit.check.PreferArrowCallbackCheckTest',
		'unit.check.PreferBindCheckTest',
		'unit.check.PreferCaseGuardCheckTest',
		'unit.check.PreferCaseGuardOracleE2ETest',
		'unit.check.PreferCaseWildcardCheckTest',
		'unit.check.PreferComprehensionCheckTest',
		'unit.check.PreferComprehensionFinalTest',
		'unit.check.PreferDocCommentCheckTest',
		'unit.check.PreferEnumAbstractCheckTest',
		'unit.check.PreferExistsCheckTest',
		'unit.check.PreferFinalAbstractMethodCheckTest',
		'unit.check.PreferFinalCheckTest',
		'unit.check.PreferFinalClassCheckTest',
		'unit.check.PreferFinalFieldCheckTest',
		'unit.check.PreferFinalPublicFieldCheckTest',
		'unit.check.PreferFinalPublicFieldStructuralTest',
		'unit.check.PreferFindCheckTest',
		'unit.check.PreferForInCheckTest',
		'unit.check.PreferForeachCheckTest',
		'unit.check.PreferIfExpressionAssignmentCheckTest',
		'unit.check.PreferIfExpressionChainCheckTest',
		'unit.check.PreferIfExpressionReturnCheckTest',
		'unit.check.PreferIndexAccessCheckTest',
		'unit.check.PreferInlineCheckTest',
		'unit.check.PreferInlineOracleTest',
		'unit.check.PreferInterpolationCheckTest',
		'unit.check.PreferKeyValueLoopCheckTest',
		'unit.check.PreferLambdaExpressionBodyCheckTest',
		'unit.check.PreferLineCommentCheckTest',
		'unit.check.PreferLocalFunctionCheckTest',
		'unit.check.PreferLpadCheckTest',
		'unit.check.PreferMapLiteralCheckTest',
		'unit.check.PreferMapTypeCheckTest',
		'unit.check.PreferNullCoalescingCheckTest',
		'unit.check.PreferNullCoalescingParensTest',
		'unit.check.PreferRangeLoopCheckTest',
		'unit.check.PreferReadOnlyFieldCheckTest',
		'unit.check.PreferSafeNavCheckTest',
		'unit.check.PreferSafeNavComparisonCheckTest',
		'unit.check.PreferSingleQuotesCheckTest',
		'unit.check.PreferStaticExtensionCheckTest',
		'unit.check.PreferSwitchCheckTest',
		'unit.check.PreferSwitchExpressionAssignmentCheckTest',
		'unit.check.PreferSwitchExpressionCheckTest',
		'unit.check.PreferTernaryAssignmentCheckTest',
		'unit.check.PreferTernaryExpressionCheckTest',
		'unit.check.PreferTernaryReturnCheckTest',
		'unit.check.PreferTryExpressionAssignmentCheckTest',
		'unit.check.PreferTryExpressionReturnCheckTest',
		'unit.check.PreferTypedThrowCheckTest',
		'unit.check.RedundantAscriptionTest',
		'unit.check.RedundantBypassAccessorCheckTest',
		'unit.check.RedundantCaseBodyCheckTest',
		'unit.check.RedundantCastCheckTest',
		'unit.check.RedundantCastTypeCheckTest',
		'unit.check.RedundantCondCompParensCheckTest',
		'unit.check.RedundantElseCheckTest',
		'unit.check.RedundantImportCheckTest',
		'unit.check.RedundantIsCheckTest',
		'unit.check.RedundantLambdaWrapperCheckTest',
		'unit.check.RedundantMapExistsCheckTest',
		'unit.check.RedundantMapIterKeyCheckTest',
		'unit.check.RedundantNullCoalescingCheckTest',
		'unit.check.RedundantParensCheckTest',
		'unit.check.RedundantParensOperandArmsTest',
		'unit.check.RedundantParensTierArmsTest',
		'unit.check.RedundantPropertyAccessCheckTest',
		'unit.check.RedundantReplaceLoopCheckTest',
		'unit.check.RedundantThisCheckTest',
		'unit.check.RedundantThisUsingExtensionTest',
		'unit.check.RedundantToStringCheckTest',
		'unit.check.RedundantTrailingCommaCheckTest',
		'unit.check.RedundantUncheckedCastCheckTest',
		'unit.check.RedundantUpcastTest',
		'unit.check.RedundantVoidReturnCheckTest',
		'unit.check.ReificationGateFixPathTest',
		'unit.check.ReificationGateTest',
		'unit.check.ReturnReassignTernaryCheckTest',
		'unit.check.SelfAssignmentCheckTest',
		'unit.check.ShadowingCaseBinderCheckTest',
		'unit.check.ShadowingLocalCheckTest',
		'unit.check.ShadowingParameterCheckTest',
		'unit.check.ShortenTypeRefCheckTest',
		'unit.check.SimplifyBooleanBranchAssignmentCheckTest',
		'unit.check.SimplifyBooleanReturnChainCheckTest',
		'unit.check.SimplifyBooleanTernaryCheckTest',
		'unit.check.SimplifyNegatedCompoundCheckTest',
		'unit.check.SplitVarDeclarationCheckTest',
		'unit.check.StaticConstantCheckTest',
		'unit.check.StringLiteralDupCheckTest',
		'unit.check.SuppressionSliceTest',
		'unit.check.SwallowedExceptionCheckTest',
		'unit.check.TailMergeCheckTest',
		'unit.check.ThreadSafetyCheckTest',
		'unit.check.TrivialGetterCheckTest',
		'unit.check.TrivialGetterIsVarTest',
		'unit.check.TrivialGetterShapeCollapseTest',
		'unit.check.TrivialGetterStaticShadowTest',
		'unit.check.TryCatchNullGuardCheckTest',
		'unit.check.UncheckedNullableTest',
		'unit.check.UnguardedNullableDerefTest',
		'unit.check.UnnecessaryBlockCheckTest',
		'unit.check.UnnecessaryNullCheckCheckTest',
		'unit.check.UnnecessarySafeNavCheckTest',
		'unit.check.UnnecessarySwitchCheckTest',
		'unit.check.UnreachableCatchTest',
		'unit.check.UnusedCaseBinderCheckTest',
		'unit.check.UnusedCaseBinderConstantLanguageTest',
		'unit.check.UnusedLocalShadowTest',
		'unit.check.UnusedParameterCheckTest',
		'unit.check.UnusedPrivateCheckTest',
		'unit.check.UnusedPublicMemberCheckTest',
		'unit.check.UnusedReturnValueTest',
		'unit.check.WhileTrueConditionCheckTest',
		'unit.cli.AddressCliTest',
		'unit.cli.ApqAstTypeRefsCliTest',
		'unit.cli.ApqAtCliTest',
		'unit.cli.ApqCountSummaryCliTest',
		'unit.cli.ApqDxTier2CliTest',
		'unit.cli.ApqDxTier3CliTest',
		'unit.cli.ApqDxTier4CliTest',
		'unit.cli.ApqDxTier5CliTest',
		'unit.cli.ApqExitOnEmptyCliTest',
		'unit.cli.ApqFmtOnePassCliTest',
		'unit.cli.ApqFmtVerifyCliTest',
		'unit.cli.ApqFromFileCliTest',
		'unit.cli.ApqHxqDxV10CliTest',
		'unit.cli.ApqHxqDxV8CliTest',
		'unit.cli.ApqLitCommentsCliTest',
		'unit.cli.ApqLitDirectivesCliTest',
		'unit.cli.ApqMetaCliTest',
		'unit.cli.ApqPrefilterCliTest',
		'unit.cli.ApqProbeCliTest',
		'unit.cli.ApqReconCliTest',
		'unit.cli.ApqSearchCliTest',
		'unit.cli.ApqSourceMetaArgCliTest',
		'unit.cli.ApqStripDryRunCliTest',
		'unit.cli.ApqStripFromClusterCliTest',
		'unit.cli.ApqWriterEqualsCliTest',
		'unit.cli.ApqWriterProbeCliTest',
		'unit.cli.CliCommandSeamTest',
		'unit.cli.CliHelpListingPinTest',
		'unit.cli.ExtractDestinationCollisionCliTest',
		'unit.cli.LintConfigCliTest',
		'unit.cli.LintFailOnCliTest',
		'unit.cli.LintFixFixedPointCliTest',
		'unit.cli.LintListRulesCliTest',
		'unit.cli.LintNoOracleCliTest',
		'unit.cli.LintPerFileConfigCliTest',
		'unit.cli.LintProjectWriteScopeCliTest',
		'unit.cli.RenameMemberInFileCliTest',
		'unit.cli.RenameTypeInFileCliTest',
		'unit.cli.ResolutionScopeCliTest',
		'unit.cli.SafeDeleteFormatConfigCliTest',
		'unit.core.BodyGroupPrefixChargeConsumerTest',
		'unit.core.DocMeasureFirstVisibleTextTest',
		'unit.core.DocRendererTest',
		'unit.core.WriterTrailingWhitespaceTest',
		'unit.format.BraceSymmetrySliceTest',
		'unit.format.CommentInventoryTest',
		'unit.format.DirectiveConditionSpacingTest',
		'unit.format.DocProbeFamilyWalkerTest',
		'unit.format.WhitespaceInvariantTest',
		'unit.format.WrapFlatSourceFixedPointTest',
		'unit.format.WrapProbeRestAwarenessSliceTest',
		'unit.format.WriteOptionsTest',
		'unit.grammar.ArParserTest',
		'unit.grammar.JValueTransformSliceTest',
		'unit.grammar.JsonParserTest',
		'unit.grammar.JsonRoundTripTest',
		'unit.grammar.JsonTypedParserTest',
		'unit.grammar.haxe.AllmanProbe',
		'unit.grammar.haxe.CheckstyleConfigLoaderTest',
		'unit.grammar.haxe.ComplexItemKindsSeamTest',
		'unit.grammar.haxe.CondModProbe',
		'unit.grammar.haxe.ElseSwitchPlacementSliceTest',
		'unit.grammar.haxe.FarthestFailTest',
		'unit.grammar.haxe.HaxeFirstSliceTest',
		'unit.grammar.haxe.HaxeFormatConfigDiagnosticsTest',
		'unit.grammar.haxe.HaxeFormatConfigLoaderTest',
		'unit.grammar.haxe.HaxeModuleSliceTest',
		'unit.grammar.haxe.HaxeWriterRoundTripTest',
		'unit.grammar.haxe.HxAbstractClassSliceTest',
		'unit.grammar.haxe.HxAbstractClauseSpacingTest',
		'unit.grammar.haxe.HxAbstractSliceTest',
		'unit.grammar.haxe.HxAccessorSliceTest',
		'unit.grammar.haxe.HxAfterLeftCurlySliceTest',
		'unit.grammar.haxe.HxAfterPackageSliceTest',
		'unit.grammar.haxe.HxAnonFieldTypeProjectionTest',
		'unit.grammar.haxe.HxAnonFnBodyStmtPositionSliceTest',
		'unit.grammar.haxe.HxAnonFuncEmptyParensInnerSpaceOptionsTest',
		'unit.grammar.haxe.HxAnonFuncParensOptionsTest',
		'unit.grammar.haxe.HxAnonMemberSliceTest',
		'unit.grammar.haxe.HxAnonTypeBracesOptionsTest',
		'unit.grammar.haxe.HxAnonTypeIgnoreReflowTest',
		'unit.grammar.haxe.HxAnonTypeSourceTrailCommaSliceTest',
		'unit.grammar.haxe.HxAnonVarFieldSliceTest',
		'unit.grammar.haxe.HxArrayComprehensionSliceTest',
		'unit.grammar.haxe.HxArrayExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxArrowArraySliceTest',
		'unit.grammar.haxe.HxArrowBlockBodyOpenSliceTest',
		'unit.grammar.haxe.HxArrowBlockIfOverflowSliceTest',
		'unit.grammar.haxe.HxArrowFnExprSliceTest',
		'unit.grammar.haxe.HxArrowFnOldStyleRewriteTest',
		'unit.grammar.haxe.HxArrowFnTypeSliceTest',
		'unit.grammar.haxe.HxArrowParamOptionalNamedSliceTest',
		'unit.grammar.haxe.HxArrowPlainIfOpenSliceTest',
		'unit.grammar.haxe.HxArrowResidualLineWrapSliceTest',
		'unit.grammar.haxe.HxArrowValueIfReflowSliceTest',
		'unit.grammar.haxe.HxAssignChainWrapSliceTest',
		'unit.grammar.haxe.HxAssignSliceTest',
		'unit.grammar.haxe.HxAssignStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxBeforeTrailCommentWriteTest',
		'unit.grammar.haxe.HxBeforeUsingSliceTest',
		'unit.grammar.haxe.HxBinaryChainWrapSliceTest',
		'unit.grammar.haxe.HxBinopGroupWrapSliceTest',
		'unit.grammar.haxe.HxBinopStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxBitwiseSliceTest',
		'unit.grammar.haxe.HxBlankAfterLeadingCommentSliceTest',
		'unit.grammar.haxe.HxBlankAroundMultilineMembersTest',
		'unit.grammar.haxe.HxBlockCommentCloseWriteTest',
		'unit.grammar.haxe.HxBlockExprSliceTest',
		'unit.grammar.haxe.HxBodySliceTest',
		'unit.grammar.haxe.HxBracketExprListTypeSliceTest',
		'unit.grammar.haxe.HxCallArgCommentWriteTest',
		'unit.grammar.haxe.HxCallArgMultilineStringCuddleTest',
		'unit.grammar.haxe.HxCallGroupRestProbeCasePatternTest',
		'unit.grammar.haxe.HxCallGroupRestProbeChainOperandTest',
		'unit.grammar.haxe.HxCallGroupRestProbeNestedArgTest',
		'unit.grammar.haxe.HxCallParamFunctionLambdaSliceTest',
		'unit.grammar.haxe.HxCallParamIfExpressionArgSliceTest',
		'unit.grammar.haxe.HxCallParamNestedArrayHugSliceTest',
		'unit.grammar.haxe.HxCallParamObjectLiteralSliceTest',
		'unit.grammar.haxe.HxCallParamOuterFirstWrapSliceTest',
		'unit.grammar.haxe.HxCaseBodyBlankSliceTest',
		'unit.grammar.haxe.HxCaseBodyControlFlowGlueTest',
		'unit.grammar.haxe.HxCaseBodyFitLineSliceTest',
		'unit.grammar.haxe.HxCaseBodyPolicySliceTest',
		'unit.grammar.haxe.HxCaseBodySameLineSliceTest',
		'unit.grammar.haxe.HxCaseBodyShapeRefusalTest',
		'unit.grammar.haxe.HxCaseBodySymmetrySliceTest',
		'unit.grammar.haxe.HxCaseBodyTrailCommentInlineTest',
		'unit.grammar.haxe.HxCaseCaptureSliceTest',
		'unit.grammar.haxe.HxCaseCommentWriteTest',
		'unit.grammar.haxe.HxCaseExprPositionPropagateTest',
		'unit.grammar.haxe.HxCaseGuardFitSliceTest',
		'unit.grammar.haxe.HxCastSliceTest',
		'unit.grammar.haxe.HxCatchBodySliceTest',
		'unit.grammar.haxe.HxChainFillBoundaryCallOperandTest',
		'unit.grammar.haxe.HxChainOuterOperatorWrapSliceTest',
		'unit.grammar.haxe.HxChainStaircaseSliceTest',
		'unit.grammar.haxe.HxCompareOperandBreakSliceTest',
		'unit.grammar.haxe.HxComplexItemWrapTest',
		'unit.grammar.haxe.HxComprehensionBlockHugSliceTest',
		'unit.grammar.haxe.HxComprehensionBracketPolicyTest',
		'unit.grammar.haxe.HxComprehensionChainIdempotencyTest',
		'unit.grammar.haxe.HxComprehensionCloserSliceTest',
		'unit.grammar.haxe.HxComprehensionCuddledOpenTest',
		'unit.grammar.haxe.HxComprehensionDeclRhsBracketWrapTest',
		'unit.grammar.haxe.HxComprehensionFilterMeasureTest',
		'unit.grammar.haxe.HxComprehensionFitLineNoBreakTest',
		'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest',
		'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest',
		'unit.grammar.haxe.HxCondCommentDirectiveSeamTest',
		'unit.grammar.haxe.HxCondCommentWriteTest',
		'unit.grammar.haxe.HxCondCompStmtTrailOptSliceTest',
		'unit.grammar.haxe.HxCondDeclElseTrailingMetaTest',
		'unit.grammar.haxe.HxCondDeclPrefixKeywordSliceTest',
		'unit.grammar.haxe.HxCondDeclPrefixSliceTest',
		'unit.grammar.haxe.HxCondElseifChainBlankTest',
		'unit.grammar.haxe.HxCondExprValueFixpointSliceTest',
		'unit.grammar.haxe.HxCondForContainerGlueSliceTest',
		'unit.grammar.haxe.HxCondHeritageSliceTest',
		'unit.grammar.haxe.HxCondListSeparatorWriteTest',
		'unit.grammar.haxe.HxCondMemberSlotSliceTest',
		'unit.grammar.haxe.HxCondModSliceTest',
		'unit.grammar.haxe.HxCondParamElseSepSliceTest',
		'unit.grammar.haxe.HxCondPlainCallLeadingBreakSliceTest',
		'unit.grammar.haxe.HxCondSpliceChainWrapSliceTest',
		'unit.grammar.haxe.HxCondSpliceExprSliceTest',
		'unit.grammar.haxe.HxCondSpliceFidelitySliceTest',
		'unit.grammar.haxe.HxCondSpliceOpFillSliceTest',
		'unit.grammar.haxe.HxCondSpliceOwnLineSliceTest',
		'unit.grammar.haxe.HxCondSpliceReturnBlockSliceTest',
		'unit.grammar.haxe.HxCondSpliceScopeSliceTest',
		'unit.grammar.haxe.HxCondTypeSlotSliceTest',
		'unit.grammar.haxe.HxCondUnbalancedRegionSliceTest',
		'unit.grammar.haxe.HxCondVarInitSliceTest',
		'unit.grammar.haxe.HxCondWrapFitLineSliceTest',
		'unit.grammar.haxe.HxConditionalExprFitSliceTest',
		'unit.grammar.haxe.HxConditionalMemberSliceTest',
		'unit.grammar.haxe.HxConditionalObjectFieldSliceTest',
		'unit.grammar.haxe.HxConditionalParamSliceTest',
		'unit.grammar.haxe.HxConditionalSourceBlankSliceTest',
		'unit.grammar.haxe.HxConditionalTypeSliceTest',
		'unit.grammar.haxe.HxConstStringTypeSliceTest',
		'unit.grammar.haxe.HxContainerItemWrapTest',
		'unit.grammar.haxe.HxControlFlowPoliciesOptionsTest',
		'unit.grammar.haxe.HxControlFlowSliceTest',
		'unit.grammar.haxe.HxDeclHeaderEqBreakOverflowTest',
		'unit.grammar.haxe.HxDeclInitMultilineStringCuddleTest',
		'unit.grammar.haxe.HxDoWhileThrowTryCatchSliceTest',
		'unit.grammar.haxe.HxDollarBlockExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxDollarReifSliceTest',
		'unit.grammar.haxe.HxDottedMetaNameSliceTest',
		'unit.grammar.haxe.HxECheckTypeSliceTest',
		'unit.grammar.haxe.HxEllipsisMemberSliceTest',
		'unit.grammar.haxe.HxEllipsisStmtSliceTest',
		'unit.grammar.haxe.HxElseIfBodyBreakTest',
		'unit.grammar.haxe.HxElseIfCommentReflowSliceTest',
		'unit.grammar.haxe.HxElseIfOptionsTest',
		'unit.grammar.haxe.HxElseifTypeSliceTest',
		'unit.grammar.haxe.HxEmptyCurlyOptionsTest',
		'unit.grammar.haxe.HxEnumAbstractSliceTest',
		'unit.grammar.haxe.HxEnumScopeEmptyLinesSliceTest',
		'unit.grammar.haxe.HxExprIdentGuardSliceTest',
		'unit.grammar.haxe.HxExprParenDivOpenBoundaryTest',
		'unit.grammar.haxe.HxExprParenObjectLitGlueTest',
		'unit.grammar.haxe.HxExprSliceTest',
		'unit.grammar.haxe.HxExprStmtTerminatorSliceTest',
		'unit.grammar.haxe.HxFileHeaderCommentSliceTest',
		'unit.grammar.haxe.HxFillAfterCollectionTest',
		'unit.grammar.haxe.HxFillLeadingCommentTest',
		'unit.grammar.haxe.HxFillLinePerGapSepTest',
		'unit.grammar.haxe.HxFinalMemberSliceTest',
		'unit.grammar.haxe.HxFinalUntypedSliceTest',
		'unit.grammar.haxe.HxFitLineBodyGlueSliceTest',
		'unit.grammar.haxe.HxFnExprBodySliceTest',
		'unit.grammar.haxe.HxFnExprSliceTest',
		'unit.grammar.haxe.HxFnMemberTrailSemiSliceTest',
		'unit.grammar.haxe.HxFnReturnBodySliceTest',
		'unit.grammar.haxe.HxFnSigExceedsBoundaryWrapTest',
		'unit.grammar.haxe.HxFnSigFillLastParamBoundaryTest',
		'unit.grammar.haxe.HxFnSigSingleParamWrapIndentTest',
		'unit.grammar.haxe.HxForEnumVoidSliceTest',
		'unit.grammar.haxe.HxForKeyValueSliceTest',
		'unit.grammar.haxe.HxFormatterCorpusTest',
		'unit.grammar.haxe.HxFormatterOffTest',
		'unit.grammar.haxe.HxFunctionBodyPolicySliceTest',
		'unit.grammar.haxe.HxGlueWidthSliceTest',
		'unit.grammar.haxe.HxGroupRestProbeStructStarTest',
		'unit.grammar.haxe.HxGroupTrailCommentWriteTest',
		'unit.grammar.haxe.HxHeadCommentSeamWriteTest',
		'unit.grammar.haxe.HxHeaderWrapLadderSliceTest',
		'unit.grammar.haxe.HxHeritageCommentWriteTest',
		'unit.grammar.haxe.HxHeritageLineWrapSliceTest',
		'unit.grammar.haxe.HxHeritageSliceTest',
		'unit.grammar.haxe.HxIfBodyBlockCaseBarrierTest',
		'unit.grammar.haxe.HxIfExprCondWrapSliceTest',
		'unit.grammar.haxe.HxIfExprTrailSemiSliceTest',
		'unit.grammar.haxe.HxIfPolicyOptionsTest',
		'unit.grammar.haxe.HxIfStmtExprPositionDispatchTest',
		'unit.grammar.haxe.HxImportAliasInSliceTest',
		'unit.grammar.haxe.HxImportAliasSliceTest',
		'unit.grammar.haxe.HxIncrDecrSliceTest',
		'unit.grammar.haxe.HxIndentCaseLabelsOptionsTest',
		'unit.grammar.haxe.HxIndentComplexValueExpressionsOptionsTest',
		'unit.grammar.haxe.HxIndentObjectLiteralOptionsTest',
		'unit.grammar.haxe.HxInfixCommentWriteTest',
		'unit.grammar.haxe.HxInlineBlockCommentGapTest',
		'unit.grammar.haxe.HxInlineBlockCommentWriteTest',
		'unit.grammar.haxe.HxInlineExprSliceTest',
		'unit.grammar.haxe.HxInterMemberBlankLinesOptionsTest',
		'unit.grammar.haxe.HxInterfaceInterMemberBlankLinesOptionsTest',
		'unit.grammar.haxe.HxIntervalPolicySliceTest',
		'unit.grammar.haxe.HxIsSliceTest',
		'unit.grammar.haxe.HxIsStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxLambdaParamDefaultSliceTest',
		'unit.grammar.haxe.HxLambdaParamOptionalSliceTest',
		'unit.grammar.haxe.HxLeftCurlyOptionsTest',
		'unit.grammar.haxe.HxLineCommentIndentSliceTest',
		'unit.grammar.haxe.HxListLiteralEmissionSliceTest',
		'unit.grammar.haxe.HxLocalFnStmtSliceTest',
		'unit.grammar.haxe.HxLocalVarMetaSliceTest',
		'unit.grammar.haxe.HxLoopBodyIfElseSliceTest',
		'unit.grammar.haxe.HxMacroClassSliceTest',
		'unit.grammar.haxe.HxMacroModHexSliceTest',
		'unit.grammar.haxe.HxMacroTypeExprSliceTest',
		'unit.grammar.haxe.HxMaxAnywhereInFileSliceTest',
		'unit.grammar.haxe.HxMeasuredMultilineDeclBlankSliceTest',
		'unit.grammar.haxe.HxMemberVarTrailOptSliceTest',
		'unit.grammar.haxe.HxMetaAllmanObjectLitSliceTest',
		'unit.grammar.haxe.HxMetaCallStmtSpaceTest',
		'unit.grammar.haxe.HxMetaExprSliceTest',
		'unit.grammar.haxe.HxMetaExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxMethodChainAllOrNothingSliceTest',
		'unit.grammar.haxe.HxMethodChainCallParamRestAwareSliceTest',
		'unit.grammar.haxe.HxMethodChainCloseTrailingTest',
		'unit.grammar.haxe.HxMethodChainCuddledLinkTest',
		'unit.grammar.haxe.HxMethodChainDotBreakOverReglueSliceTest',
		'unit.grammar.haxe.HxMethodChainEmitTest',
		'unit.grammar.haxe.HxMethodChainExactLimitBoundaryTest',
		'unit.grammar.haxe.HxMethodChainWrapCapabilityTest',
		'unit.grammar.haxe.HxModifierFlattenSliceTest',
		'unit.grammar.haxe.HxModifierSliceTest',
		'unit.grammar.haxe.HxMultiPatternCaseSliceTest',
		'unit.grammar.haxe.HxMultiVarDeclSliceTest',
		'unit.grammar.haxe.HxMultilineDeclSliceTest',
		'unit.grammar.haxe.HxNamedFnExprSliceTest',
		'unit.grammar.haxe.HxNoBodyAbstractTest',
		'unit.grammar.haxe.HxNumericSeparatorSliceTest',
		'unit.grammar.haxe.HxObjectFieldColonOptionsTest',
		'unit.grammar.haxe.HxObjectLitArrowBodyPadSliceTest',
		'unit.grammar.haxe.HxObjectLitBracesOptionsTest',
		'unit.grammar.haxe.HxObjectLitLeftCurlyOptionsTest',
		'unit.grammar.haxe.HxObjectLitRestProbeTest',
		'unit.grammar.haxe.HxObjectLitSliceTest',
		'unit.grammar.haxe.HxObjectLitSourceTrailCommaSliceTest',
		'unit.grammar.haxe.HxObjectLitStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxObjectLitWrapRulesTest',
		'unit.grammar.haxe.HxOpAddChainOperatorFirstSliceTest',
		'unit.grammar.haxe.HxOpAddParenInnerBreakTest',
		'unit.grammar.haxe.HxOpAddTrailingParenGlueSliceTest',
		'unit.grammar.haxe.HxOpenDelimStashBarrierTest',
		'unit.grammar.haxe.HxOptionalSemicolonSliceTest',
		'unit.grammar.haxe.HxOrphanPrefixDeclSliceTest',
		'unit.grammar.haxe.HxOverloadMetaSliceTest',
		'unit.grammar.haxe.HxPackedOrOnePerLineTest',
		'unit.grammar.haxe.HxParamBodyUntypedSliceTest',
		'unit.grammar.haxe.HxParamCommentWriteTest',
		'unit.grammar.haxe.HxParamSliceTest',
		'unit.grammar.haxe.HxParenSliceTest',
		'unit.grammar.haxe.HxParenTernaryOpenWrapSliceTest',
		'unit.grammar.haxe.HxParenValueIfOpenWrapSliceTest',
		'unit.grammar.haxe.HxParenWrapSourceNewlineSliceTest',
		'unit.grammar.haxe.HxPostfixSliceTest',
		'unit.grammar.haxe.HxPpCondDottedSliceTest',
		'unit.grammar.haxe.HxPrattOpsTest',
		'unit.grammar.haxe.HxPrattSliceTest',
		'unit.grammar.haxe.HxPrefixSliceTest',
		'unit.grammar.haxe.HxRegexLitSliceTest',
		'unit.grammar.haxe.HxReturnBodySliceTest',
		'unit.grammar.haxe.HxReturnCallOpenParenSliceTest',
		'unit.grammar.haxe.HxReturnValueBreaksInsideTest',
		'unit.grammar.haxe.HxRhsCommentWriteTest',
		'unit.grammar.haxe.HxRightCurlyOptionsTest',
		'unit.grammar.haxe.HxSameLineOptionsTest',
		'unit.grammar.haxe.HxSemicolonBeforeElseSliceTest',
		'unit.grammar.haxe.HxSepStarCloseTrailCommentTest',
		'unit.grammar.haxe.HxSharpErrorSliceTest',
		'unit.grammar.haxe.HxSingleStmtBracesSliceTest',
		'unit.grammar.haxe.HxSoleArgGluedCloseDedentTest',
		'unit.grammar.haxe.HxSoleItemCuddledBracketsTest',
		'unit.grammar.haxe.HxSourceBlankPreserveSliceTest',
		'unit.grammar.haxe.HxSpreadSliceTest',
		'unit.grammar.haxe.HxStaticLocalStmtSliceTest',
		'unit.grammar.haxe.HxStmtBeforeCaseNoSemiSliceTest',
		'unit.grammar.haxe.HxStmtBlockEndNoSemiSliceTest',
		'unit.grammar.haxe.HxStringEscapeTest',
		'unit.grammar.haxe.HxStringInterpNoFormatSliceTest',
		'unit.grammar.haxe.HxStringSliceTest',
		'unit.grammar.haxe.HxStructFieldTrailPresentSliceTest',
		'unit.grammar.haxe.HxSwitchAfterParenSpaceSliceTest',
		'unit.grammar.haxe.HxSwitchBareSliceTest',
		'unit.grammar.haxe.HxSwitchGuardSliceTest',
		'unit.grammar.haxe.HxSwitchNewSliceTest',
		'unit.grammar.haxe.HxSwitchSubjectParensStripSliceTest',
		'unit.grammar.haxe.HxTernaryBranchChainIndentTest',
		'unit.grammar.haxe.HxTernaryCallArgRestAwareTest',
		'unit.grammar.haxe.HxTernaryCollectionHugSliceTest',
		'unit.grammar.haxe.HxTernaryCommentWriteTest',
		'unit.grammar.haxe.HxTernaryCuddleProbeShapeTest',
		'unit.grammar.haxe.HxTernaryCuddledBracesTest',
		'unit.grammar.haxe.HxTernaryDeclInitRestAwareTest',
		'unit.grammar.haxe.HxTernarySliceTest',
		'unit.grammar.haxe.HxThinArrowIfElseBreakSliceTest',
		'unit.grammar.haxe.HxThinArrowSliceTest',
		'unit.grammar.haxe.HxThinArrowTrailingLambdaSliceTest',
		'unit.grammar.haxe.HxThrowBodySliceTest',
		'unit.grammar.haxe.HxTopLevelSliceTest',
		'unit.grammar.haxe.HxToplevelImportUsingSliceTest',
		'unit.grammar.haxe.HxToplevelImportWildSliceTest',
		'unit.grammar.haxe.HxToplevelMetaSliceTest',
		'unit.grammar.haxe.HxToplevelPackageSliceTest',
		'unit.grammar.haxe.HxToplevelVarFnSliceTest',
		'unit.grammar.haxe.HxTrailOptSourceTrackSliceTest',
		'unit.grammar.haxe.HxTrailingCommaOptionsTest',
		'unit.grammar.haxe.HxTrailingSepSliceTest',
		'unit.grammar.haxe.HxTransformSliceTest',
		'unit.grammar.haxe.HxTriviaParseTest',
		'unit.grammar.haxe.HxTriviaTypesTest',
		'unit.grammar.haxe.HxTriviaWriteTest',
		'unit.grammar.haxe.HxTryBodyOptionsTest',
		'unit.grammar.haxe.HxTryBraceSymmetrySliceTest',
		'unit.grammar.haxe.HxTryExprSliceTest',
		'unit.grammar.haxe.HxTryPolicyOptionsTest',
		'unit.grammar.haxe.HxTypeAnonSliceTest',
		'unit.grammar.haxe.HxTypeArrowSliceTest',
		'unit.grammar.haxe.HxTypeIntersectionSliceTest',
		'unit.grammar.haxe.HxTypeParamDefaultEqualsOptionsTest',
		'unit.grammar.haxe.HxTypeParamFieldNoWrapSliceTest',
		'unit.grammar.haxe.HxTypeParamSliceTest',
		'unit.grammar.haxe.HxTypeParamSpacingOptionsTest',
		'unit.grammar.haxe.HxTypeParensSliceTest',
		'unit.grammar.haxe.HxTypedefAnonForceMultiTest',
		'unit.grammar.haxe.HxTypedefAssignOptionsTest',
		'unit.grammar.haxe.HxTypedefBetweenBlankTest',
		'unit.grammar.haxe.HxTypedefSemiSliceTest',
		'unit.grammar.haxe.HxUniformStatementBlanksSliceTest',
		'unit.grammar.haxe.HxUntypedBodyPolicySliceTest',
		'unit.grammar.haxe.HxValueIfBracketHugSliceTest',
		'unit.grammar.haxe.HxValueIfFitSliceTest',
		'unit.grammar.haxe.HxVarInitBreakAfterEqOverflowTest',
		'unit.grammar.haxe.HxVarNoTypeSliceTest',
		'unit.grammar.haxe.HxVarStmtTrailOptSliceTest',
		'unit.grammar.haxe.HxVarTrailOptShapeSliceTest',
		'unit.grammar.haxe.HxVarTypeHintAnonIndentTest',
		'unit.grammar.haxe.HxWrapConditionVocabularyTest',
		'unit.grammar.haxe.HxWrapRulesIngestTest',
		'unit.grammar.haxe.PairedConvertersSmokeTest',
		'unit.grammar.haxe.Probe147',
		'unit.grammar.haxe.ProbeIssue344',
		'unit.grammar.haxe.ProbeMetadataLineEnd',
		'unit.grammar.haxe.ProbeTypedefTrivia',
		'unit.grammar.haxe.TriviaScanSliceTest',
		'unit.lowering.FmtFlagOwnershipTest',
		'unit.lowering.GeneratedLexicalScanSecondGrammarTest',
		'unit.lowering.RegexFirstBytesTest',
		'unit.lowering.StarBlockEndedTest',
		'unit.lowering.StarSepStartsElementTest',
		'unit.lowering.WriterFamilyCtxBundleTest',
		'unit.query.AddElementSliceTest',
		'unit.query.AddImportSliceTest',
		'unit.query.AddMemberSliceTest',
		'unit.query.AddMetaSliceTest',
		'unit.query.AddParamSliceTest',
		'unit.query.AddressTest',
		'unit.query.ApqAstChildCountTest',
		'unit.query.ApqAstIntegrationTest',
		'unit.query.ApqAstSelectFuzzyTest',
		'unit.query.ApqAstWriterOutputPlainTest',
		'unit.query.ApqDepthSemanticsTest',
		'unit.query.ApqDocSourceTest',
		'unit.query.ApqDottedAccessNudgeTest',
		'unit.query.ApqHxtestSection1ConfigTest',
		'unit.query.ApqIfStmtChildOrderTest',
		'unit.query.ApqJsonSchemaProbe',
		'unit.query.ApqMatcherTest',
		'unit.query.ApqMetaAnonFieldSliceTest',
		'unit.query.ApqMetaEnumCtorSliceTest',
		'unit.query.ApqMetaTest',
		'unit.query.ApqRefsIncrDecrSliceTest',
		'unit.query.ApqRefsTest',
		'unit.query.ApqSelectorTest',
		'unit.query.ApqSkipParseLocusTest',
		'unit.query.ApqSourceDedentTest',
		'unit.query.ApqSourceSelectTest',
		'unit.query.ApqSpanFlowTest',
		'unit.query.ApqTestSummaryTinkTest',
		'unit.query.ApqTextRenderTest',
		'unit.query.ApqUsesTest',
		'unit.query.BodySlotGuardSliceTest',
		'unit.query.CachingGrammarPluginTest',
		'unit.query.CallGraphTest',
		'unit.query.ChangeSigSliceTest',
		'unit.query.ClassifyOccurrencesTest',
		'unit.query.CliAtomicWriteSliceTest',
		'unit.query.ClustersTest',
		'unit.query.CommentOwnerGuardSliceTest',
		'unit.query.CommentRewriteSliceTest',
		'unit.query.CondBranchSplitTest',
		'unit.query.CrossRenameMemberSliceTest',
		'unit.query.CrossRenameSliceTest',
		'unit.query.DeleteBlankLineSliceTest',
		'unit.query.DocOwnerGuardSliceTest',
		'unit.query.EncapsulateFieldSliceTest',
		'unit.query.ExtractConstantSliceTest',
		'unit.query.ExtractInterfaceSliceTest',
		'unit.query.ExtractMethodSliceTest',
		'unit.query.ExtractSuperclassSliceTest',
		'unit.query.ExtractVarSliceTest',
		'unit.query.FieldRefScanTest',
		'unit.query.FieldRenameTest',
		'unit.query.FmtSliceTest',
		'unit.query.FormatConfigDiscoveryTest',
		'unit.query.GlobExpandTest',
		'unit.query.HaxelibResolverTest',
		'unit.query.ImplicitStdScopeTest',
		'unit.query.InheritanceMoveSliceTest',
		'unit.query.InlineMethodSliceTest',
		'unit.query.InlineSliceTest',
		'unit.query.InnermostScopeSpanParityTest',
		'unit.query.IntroduceParameterObjectSliceTest',
		'unit.query.JsonSpanCoordinatesTest',
		'unit.query.LexicalRegionsSeamTest',
		'unit.query.LexicalRegionsTest',
		'unit.query.LintDiffTest',
		'unit.query.LintFixSafePassRevertTest',
		'unit.query.LocalTypeAnnotationProjectionTest',
		'unit.query.MakeFinalSliceTest',
		'unit.query.MetaElementSpanSliceTest',
		'unit.query.ModifierKindSeamTest',
		'unit.query.MoveCanonicalOutputSliceTest',
		'unit.query.MoveExtractDocCensusTest',
		'unit.query.MoveFamilyCaptureTest',
		'unit.query.MoveGuardedImportCarryTest',
		'unit.query.MoveMemberSliceTest',
		'unit.query.MoveSymbolSliceTest',
		'unit.query.MutationVerdictTest',
		'unit.query.NameMentionScanTest',
		'unit.query.NewFileSliceTest',
		'unit.query.ParenGuardSliceTest',
		'unit.query.ParseFailureLocusTest',
		'unit.query.PatchSliceTest',
		'unit.query.PatternParseProbe',
		'unit.query.RefsCacheTest',
		'unit.query.RemoveElementSliceTest',
		'unit.query.RemoveImportSliceTest',
		'unit.query.RemoveMemberDocSliceTest',
		'unit.query.RemoveMemberSliceTest',
		'unit.query.RemoveParamSliceTest',
		'unit.query.RenameSliceTest',
		'unit.query.ReplaceNodeSliceTest',
		'unit.query.ResolutionLibraryCacheTest',
		'unit.query.ResolutionProjectFilesTest',
		'unit.query.RewriteSliceTest',
		'unit.query.SafeDeleteSliceTest',
		'unit.query.SetCommentSliceTest',
		'unit.query.SetDocSliceTest',
		'unit.query.SetModifierSliceTest',
		'unit.query.ShardPlanTest',
		'unit.query.SpanTypeInfoPinTest',
		'unit.query.StdResolverReturnTypeTest',
		'unit.query.StdResolverTest',
		'unit.query.StdlibDifferentialTest',
		'unit.query.StdlibDupScanTest',
		'unit.query.StructuralMembershipTest',
		'unit.query.SymbolIndexAliasSliceTest',
		'unit.query.SymbolIndexLayerSeamTest',
		'unit.query.SymbolIndexRunMemoSliceTest',
		'unit.query.SymbolIndexSliceTest',
		'unit.query.SymbolQuerySliceTest',
		'unit.query.ThinArrowParamBindingSliceTest',
		'unit.query.TypeRefPrinterTest',
		'unit.query.TypeResolverSliceTest',
		'unit.runtime.InputTest',
		'unit.runtime.ParseErrorTest',
		'unit.runtime.SpanTest'
	];

	public function testDiscoveryRegistersExactlyTheCensusedClasses(): Void {
		final registered: Array<String> = TestRegistry.classNames().copy();
		registered.sort(Reflect.compare);
		Assert.same(REGISTERED_CLASSES, registered, 'add or remove the class in REGISTERED_CLASSES when you add or remove a test class');
	}

	/** `Runner.addITest` throws "Cannot add the same test twice" — this fails first, and says why. */
	public function testNoClassIsRegisteredTwice(): Void {
		final names: Array<String> = TestRegistry.classNames();
		final seen: Array<String> = [];
		for (name in names) if (!seen.contains(name)) seen.push(name);
		Assert.equals(names.length, seen.length, 'a duplicate registration makes utest throw at run start');
	}

	/**
	 * The generated names have to be the spelling `Type.getClassName` produces:
	 * that is what the `APQ_TEST` filter matches on and what
	 * `apq shard-plan --classes` deals.
	 */
	public function testEveryRegisteredNameResolvesToARealClass(): Void {
		final unresolved: Array<String> = TestRegistry.classNames().filter(name -> Type.resolveClass(name) == null);
		Assert.same([], unresolved, 'every registered name resolves at runtime');
	}

	/** The whole point, stated once: a class no hand-written line names still runs. */
	public function testTheDiscoveryOnlyFixtureIsRegistered(): Void {
		Assert.isTrue(
			TestRegistry.classNames().contains('unit.DiscoveryOnlyProbeTest'),
			'unit.DiscoveryOnlyProbeTest carries no hand-written registration anywhere, on purpose'
		);
	}

	/**
	 * A fixture-named method utest will never run — `static function testX`,
	 * or one on a class that does not implement `utest.ITest`. The tree has
	 * none today; this pin is what makes the first one arrive loudly instead
	 * of joining the 167 dead methods S48 found.
	 */
	public function testTheDeadFixtureCensusIsEmpty(): Void {
		Assert.same([], TestRegistry.deadTests(), 'no fixture-named method is unreachable to utest');
	}

	/**
	 * The metadata pilot, read back through the macro that validates it.
	 *
	 * `@:pin` names what a fixture is FOR and `@:killer` the mutation arm that
	 * must break it; `testkit.TestDiscovery` refuses to build a `control`
	 * naming no arm, which is a compile error and therefore has no fixture of
	 * its own — this is the runtime half, and it is what keeps the metas from
	 * being dropped in a refactor without anything noticing.
	 *
	 * Two entries, one class, on purpose: the tree is NOT converted.
	 */
	public function testThePilotPinsReachTheGeneratedRegistry(): Void {
		Assert.same([
			'unit.grammar.haxe.ComplexItemKindsSeamTest#testTheGeneratedPredicateAnswersTheClassifier :: control :: M-KINDS',
			'unit.grammar.haxe.ComplexItemKindsSeamTest#testTheTriviaFamilyCarriesTheSameEntry :: seam :: ',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testFitLineMovesANonFlatBodyOffTheHeadLine :: control '
			+ ':: M-FIRST-LINE-FIT',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testFitLinePullsUpABodyThatFits :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testKeepReadsTheSourceBreak :: control :: M-ALWAYS-SAME',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testNextLayoutIsIdempotent :: control :: M-ALWAYS-SAME',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testNextPutsTheBodyOnItsOwnLine :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testSameKeepsAFlatBodyOnTheHeadLine :: control :: M-ALWAYS-NEXT',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testSamePullsTheBodyUpOntoTheHeadLine :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testTheSpecificKeyOutranksTheExpressionIfFanout :: control '
			+ ':: M-FANOUT-FIRST',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testFilterIfWithoutElseStillCuddles :: control :: M-CUDDLE-OFF',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyCuddles :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyCuddlesWithTightBrackets :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyUnderFitLineLeavesTheHeadLine :: control '
			+ ':: M-FIRST-LINE-FIT',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testNestedComprehensionsChooseTheSameLayout :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testNestedComprehensionsUnderFitLineStaircase :: control '
			+ ':: M-FIRST-LINE-FIT'
		], TestRegistry.pins(), 'the pilot annotations, with their roles and killing arms');
	}

	public function testFixturelessSubclassesAreReportedRatherThanRegistered(): Void {
		Assert.same(EXPECTED_BASE_CLASSES, TestRegistry.baseClasses(), 'the reported no-fixture subclasses');
		final registered: Array<String> = TestRegistry.classNames();
		for (name in EXPECTED_BASE_CLASSES)
			Assert.isFalse(registered.contains(name), '$name carries no fixture, so registering it would be a no-op');
	}

}
