package unit;

import testkit.TestRegistry;
import utest.Assert;
import utest.Test;

using Lambda;

/**
 * Pins the GENERATED registration layer — `testkit.TestRegistry`, built by
 * `testkit.TestDiscovery`.
 *
 * `test/RunTests.hx` used to carry 758 hand-written `addCase(new X())` lines
 * and their 758 imports. The cost was never the typing: a class whose line
 * was never added ran nowhere and said nothing, and no gate had an artifact
 * to compare against. This class is that artifact.
 *
 * THE SHAPE IS T130's — the shrinkage IS the acceptance test. The registered
 * NAMES are pinned, so narrowing the discovery predicate by one class turns the
 * suite red instead of quietly running one fewer, and the failure names the
 * class that vanished. That trades one silent failure for one loud chore:
 * adding a test class now needs its name written into `REGISTERED_CLASSES`,
 * and the failure message says so.
 *
 * What is deliberately NOT pinned here is per-METHOD parity. utest decides
 * what a fixture is (`!isStatic` and a `test`/`spec` name prefix) and
 * `TestDiscovery` asks utest's own question, so the two cannot disagree by
 * construction; the per-class per-method census that proved it across the
 * switch-over is in the slice report, not in a fixture that would have to be
 * regenerated on every test added.
 */
@:nullSafety(Strict)
class TestDiscoveryParityTest extends Test {

	/**
	 * `utest.Test` subclasses carrying no fixture of their own or inherited.
	 *
	 * Registering one would be a no-op — `Runner.addITest` builds no fixture
	 * for it either and stores no entry — so discovery reports them instead
	 * of registering them, and this pin is what keeps "reports" from decaying
	 * into "silently drops".
	 *
	 * Five are shared bases for one check's tests. The sixth,
	 * `unit.grammar.haxe.HxTestHelpers`, reads like the surprise and is not
	 * one: 127 `Hx*` test classes extend it, so its `extends utest.Test` is
	 * what makes each of THEM a `utest.ITest`. It carries parse / round-trip
	 * helpers and no fixture of its own, which is exactly why discovery
	 * reports it rather than registering it.
	 */
	private static final EXPECTED_BASE_CLASSES: Array<String> = [
		'unit.check.ExplicitLocalTypeCheckTestBase',
		'unit.check.FoldStringLiteralsCheckTestBase',
		'unit.check.NamingCheckTestBase',
		'unit.check.RedundantParensOperandArmsTestBase',
		'unit.check.TrivialGetterCheckTestBase',
		'unit.grammar.haxe.HxTestHelpers'
	];

	/**
	 * The fully-qualified name of every class discovery must register, sorted.
	 *
	 * A COUNT was the obvious shape and it is the one representation that merges
	 * silently and wrongly. Measured on 2026-09-04: the base was 768, two slices
	 * each added ONE test class, and each wrote 769. Git took the second 769 as
	 * text already applied — no conflict, both merges clean — and the tree then
	 * claimed 769 while registering 770. A scalar cannot do better: every branch
	 * that increments writes the same token, so a merge has nothing to disagree
	 * about. A floor (`>= N`) merges harmlessly too, but it cannot name what
	 * vanished and does not notice a class removed without a bump; the user chose
	 * the list.
	 *
	 * Two branches that each add a class either merge BOTH lines or conflict
	 * loudly, and the failure message names the missing or surplus class instead
	 * of subtracting two integers. The cost is one line in the diff of every
	 * test-adding slice, which is the point.
	 *
	 * REGENERATE with `node bin/test.js --list-classes | LC_ALL=C sort` — and
	 * REBUILD `bin/test.js` first. The probe reads the binary, not the tree: right
	 * after a merge it answered 769 for a tree that registers 770, so the
	 * verification step itself lied until `haxe test-js.hxml` had run. `LC_ALL=C`
	 * is not decoration either: the assertion sorts the registry with
	 * `Reflect.compare`, which is code-unit order, while a default macOS `sort`
	 * collates by locale and puts a different list in front of you.
	 */
	private static final REGISTERED_CLASSES: Array<String> = [
		'unit.DeadTestGuardTest',
		'unit.DiscoveryOnlyProbeTest',
		'unit.ExtensionMethodsExtractionTest',
		'unit.LexicalRegionAgreementTest',
		'unit.MutationArmAddressTest',
		'unit.MutationArmsTest',
		'unit.ProseClaimCensusTest',
		'unit.SpanModeProbe',
		'unit.TestDiscoveryParityTest',
		'unit.check.AlwaysNullComparisonTest',
		'unit.check.AnonTypeDupCheckTest',
		'unit.check.AssignmentInConditionCheckTest',
		'unit.check.AsymmetricBranchBracesCheckTest',
		'unit.check.AvoidDynamicBagCheckTest',
		'unit.check.AvoidDynamicBagFixTest',
		'unit.check.AvoidDynamicBagOracleE2ETest',
		'unit.check.AvoidDynamicCheckTest',
		'unit.check.AvoidDynamicNarrowFixTest',
		'unit.check.AvoidDynamicRiskyFixE2ETest',
		'unit.check.BuildMacroMetaSeamTest',
		'unit.check.BuiltinFixClassCensusTest',
		'unit.check.CasePatternSeparatorCheckTest',
		'unit.check.CatchDynamicCheckTest',
		'unit.check.CollapseNestedSwitchCheckTest',
		'unit.check.CollapsibleElseIfCheckTest',
		'unit.check.CollapsibleIfCheckTest',
		'unit.check.ComparisonToBooleanCheckTest',
		'unit.check.CompilerOracleE2ETest',
		'unit.check.ComplexityCheckTest',
		'unit.check.CondAssignMergeCheckTest',
		'unit.check.CondRegionLivenessTest',
		'unit.check.CondRegionMergeCheckTest',
		'unit.check.ConstantConditionCheckTest',
		'unit.check.CoreApiConformanceGateTest',
		'unit.check.DeadBinderCounterLoopCheckTest',
		'unit.check.DeadCodeCheckTest',
		'unit.check.DeadNullCoalescingTest',
		'unit.check.DeadNullGuardTest',
		'unit.check.DeadSafeNavTest',
		'unit.check.DeadStoreTest',
		'unit.check.DefaultRepeatedArgumentCheckTest',
		'unit.check.DefiniteAssignmentGuardTest',
		'unit.check.DocCommentContinuationCheckTest',
		'unit.check.DocCoverageCheckTest',
		'unit.check.DoubleNegationCheckTest',
		'unit.check.DuplicateCaseCheckTest',
		'unit.check.DuplicateCaseCondBranchTest',
		'unit.check.DuplicateCodeCheckTest',
		'unit.check.DuplicateCodeCrossFileCheckTest',
		'unit.check.DuplicateTernaryBranchesCheckTest',
		'unit.check.EmptyBlockCheckTest',
		'unit.check.EmptyCaseArmCheckTest',
		'unit.check.EmptyCommentCheckTest',
		'unit.check.EmptyDocTagCheckTest',
		'unit.check.EmptyStatementCheckTest',
		'unit.check.EnglishCommentsCheckTest',
		'unit.check.ExplicitLocalTypeCheckTest',
		'unit.check.ExplicitLocalTypeIndexAccessTest',
		'unit.check.ExplicitLocalTypeOracleAbstainTest',
		'unit.check.ExplicitLocalTypeOracleE2ETest',
		'unit.check.ExplicitLocalTypeOracleTest',
		'unit.check.ExplicitLocalTypeParenInitTest',
		'unit.check.ExplicitLocalTypePrinterTest',
		'unit.check.ExplicitLocalTypeReadFixTest',
		'unit.check.ExplicitTypeCheckTest',
		'unit.check.ExplicitTypeReturnOracleTest',
		'unit.check.ExtractRepeatedExpressionTest',
		'unit.check.FieldInitAtDeclarationCheckTest',
		'unit.check.FieldInitInConstructorCheckTest',
		'unit.check.FieldMutabilityMacroGateTest',
		'unit.check.FieldWriteResolutionScopeTest',
		'unit.check.FixVerifierBisectTest',
		'unit.check.FixVerifierCoverageE2ETest',
		'unit.check.FixVerifierGroupE2ETest',
		'unit.check.FixVerifierGroupTest',
		'unit.check.FixVerifierProbeRefusalE2ETest',
		'unit.check.FixVerifierScopeE2ETest',
		'unit.check.FoldStringLiteralsCandidateGateTest',
		'unit.check.FoldStringLiteralsCheckTest',
		'unit.check.FoldStringLiteralsCondRegionTest',
		'unit.check.FoldStringLiteralsWidthCheckTest',
		'unit.check.FragmentedDocCommentCheckTest',
		'unit.check.FrameworkContractTest',
		'unit.check.GuardContinueCheckTest',
		'unit.check.GuardReturnCheckTest',
		'unit.check.HaxeSpawnTest',
		'unit.check.HoistBranchStringAffixCheckTest',
		'unit.check.HoistEmbeddedAssignmentCheckTest',
		'unit.check.IdenticalOperandsCheckTest',
		'unit.check.IfFalseDeadCodeCheckTest',
		'unit.check.ImportBlockOrderCheckTest',
		'unit.check.ImportOutsideGuardCheckTest',
		'unit.check.ImpossibleCastTest',
		'unit.check.ImpossibleIsCheckTest',
		'unit.check.InlineConstantCheckTest',
		'unit.check.InvertNegatedIfElseCheckTest',
		'unit.check.JoinArrayPushesCheckTest',
		'unit.check.JoinBranchCallCheckTest',
		'unit.check.JoinDeclarationAssignmentCheckTest',
		'unit.check.JoinOverrideChainCheckTest',
		'unit.check.JoinReturnCheckTest',
		'unit.check.JoinSingleUseLocalCheckTest',
		'unit.check.JoinStringAppendCheckTest',
		'unit.check.LambdaBranchingBodyBlockCheckTest',
		'unit.check.LintConfigInheritanceTest',
		'unit.check.LintConfigTest',
		'unit.check.LintFixDeclineWiringSliceTest',
		'unit.check.LintFixFollowUpRoundTest',
		'unit.check.LintLanguageVersionGateTest',
		'unit.check.LintModuleSecondaryTypeSliceTest',
		'unit.check.LintReportChannelSliceTest',
		'unit.check.LintScopeGateTest',
		'unit.check.LintSliceTest',
		'unit.check.LintUnusedImportDottedSliceTest',
		'unit.check.LintUnusedImportResolutionScopeTest',
		'unit.check.LintUsingSubmoduleExtensionTest',
		'unit.check.ListenerSymmetryCheckTest',
		'unit.check.LoopGuardCheckTest',
		'unit.check.MagicNumberCheckTest',
		'unit.check.MapKeysLookupCheckTest',
		'unit.check.MemberOrderCheckTest',
		'unit.check.MemberOrderMessageTest',
		'unit.check.MemberOrderModifierSpanSliceTest',
		'unit.check.MessageMaskTest',
		'unit.check.MisplacedTypeDocCheckTest',
		'unit.check.MisplacedTypeDocGuardedMetaTest',
		'unit.check.MissingVisibilityCheckTest',
		'unit.check.ModifierOrderCheckTest',
		'unit.check.NamingCheckAltSpellingFixTest',
		'unit.check.NamingCheckBranchTwinFixTest',
		'unit.check.NamingCheckCrossFileFixTest',
		'unit.check.NamingCheckHoistFixTest',
		'unit.check.NamingCheckLocalFixTest',
		'unit.check.NamingCheckMemberFixTest',
		'unit.check.NamingCheckTest',
		'unit.check.NarrowLocalScopeCheckTest',
		'unit.check.NoUnderscorePrefixCheckTest',
		'unit.check.NullDereferenceTest',
		'unit.check.NullableSourceResolutionScopeTest',
		'unit.check.NullableSwitchMissingNullCheckTest',
		'unit.check.OperatorOverloadGateTest',
		'unit.check.OptionalParamShorthandCheckTest',
		'unit.check.OracleBatchRevertReasonTest',
		'unit.check.OracleCacheTest',
		'unit.check.OracleCoverageTest',
		'unit.check.OracleFixImportLeakTest',
		'unit.check.OrphanAccessorCheckTest',
		'unit.check.OversizedTypeCheckTest',
		'unit.check.PossibleNullDereferenceTest',
		'unit.check.PreferArrayLiteralCheckTest',
		'unit.check.PreferArrowCallbackCheckTest',
		'unit.check.PreferBindCheckTest',
		'unit.check.PreferCaseGuardCheckTest',
		'unit.check.PreferCaseGuardOracleE2ETest',
		'unit.check.PreferCaseWildcardCheckTest',
		'unit.check.PreferComprehensionCheckTest',
		'unit.check.PreferComprehensionFinalTest',
		'unit.check.PreferDocCommentCheckTest',
		'unit.check.PreferEnumAbstractCheckTest',
		'unit.check.PreferExistsCheckTest',
		'unit.check.PreferFinalAbstractMethodCheckTest',
		'unit.check.PreferFinalCheckTest',
		'unit.check.PreferFinalClassCheckTest',
		'unit.check.PreferFinalFieldCheckTest',
		'unit.check.PreferFinalPublicFieldCheckTest',
		'unit.check.PreferFinalPublicFieldStructuralTest',
		'unit.check.PreferFindCheckTest',
		'unit.check.PreferForInCheckTest',
		'unit.check.PreferForeachCheckTest',
		'unit.check.PreferIfExpressionAssignmentCheckTest',
		'unit.check.PreferIfExpressionChainCheckTest',
		'unit.check.PreferIfExpressionReturnCheckTest',
		'unit.check.PreferIndexAccessCheckTest',
		'unit.check.PreferInlineCheckTest',
		'unit.check.PreferInlineOracleTest',
		'unit.check.PreferInterpolationCheckTest',
		'unit.check.PreferKeyValueLoopCheckTest',
		'unit.check.PreferLambdaExpressionBodyCheckTest',
		'unit.check.PreferLineCommentCheckTest',
		'unit.check.PreferLocalFunctionCheckTest',
		'unit.check.PreferLpadCheckTest',
		'unit.check.PreferMapLiteralCheckTest',
		'unit.check.PreferMapTypeCheckTest',
		'unit.check.PreferNullCoalescingCheckTest',
		'unit.check.PreferNullCoalescingParensTest',
		'unit.check.PreferRangeLoopCheckTest',
		'unit.check.PreferReadOnlyFieldCheckTest',
		'unit.check.PreferSafeNavCheckTest',
		'unit.check.PreferSafeNavComparisonCheckTest',
		'unit.check.PreferSingleQuotesCheckTest',
		'unit.check.PreferStaticExtensionCheckTest',
		'unit.check.PreferSwitchCheckTest',
		'unit.check.PreferSwitchExpressionAssignmentCheckTest',
		'unit.check.PreferSwitchExpressionCheckTest',
		'unit.check.PreferTernaryAssignmentCheckTest',
		'unit.check.PreferTernaryExpressionCheckTest',
		'unit.check.PreferTernaryReturnCheckTest',
		'unit.check.PreferTryExpressionAssignmentCheckTest',
		'unit.check.PreferTryExpressionReturnCheckTest',
		'unit.check.PreferTypedThrowCheckTest',
		'unit.check.RedundantAscriptionTest',
		'unit.check.RedundantBypassAccessorCheckTest',
		'unit.check.RedundantCaseBodyCheckTest',
		'unit.check.RedundantCastCheckTest',
		'unit.check.RedundantCastTypeCheckTest',
		'unit.check.RedundantCondCompParensCheckTest',
		'unit.check.RedundantElseCheckTest',
		'unit.check.RedundantImportCheckTest',
		'unit.check.RedundantIsCheckTest',
		'unit.check.RedundantLambdaWrapperCheckTest',
		'unit.check.RedundantMapExistsCheckTest',
		'unit.check.RedundantMapIterKeyCheckTest',
		'unit.check.RedundantNullCoalescingCheckTest',
		'unit.check.RedundantParensCheckTest',
		'unit.check.RedundantParensOperandArmsTest',
		'unit.check.RedundantParensTierArmsTest',
		'unit.check.RedundantPropertyAccessCheckTest',
		'unit.check.RedundantReplaceLoopCheckTest',
		'unit.check.RedundantThisCheckTest',
		'unit.check.RedundantThisUsingExtensionTest',
		'unit.check.RedundantToStringCheckTest',
		'unit.check.RedundantTrailingCommaCheckTest',
		'unit.check.RedundantUncheckedCastCheckTest',
		'unit.check.RedundantUpcastTest',
		'unit.check.RedundantVoidReturnCheckTest',
		'unit.check.ReificationGateFixPathTest',
		'unit.check.ReificationGateTest',
		'unit.check.ReturnReassignTernaryCheckTest',
		'unit.check.SelfAssignmentCheckTest',
		'unit.check.ShadowingCaseBinderCheckTest',
		'unit.check.ShadowingLocalCheckTest',
		'unit.check.ShadowingParameterCheckTest',
		'unit.check.ShortenTypeRefCheckTest',
		'unit.check.SimplifyBooleanBranchAssignmentCheckTest',
		'unit.check.SimplifyBooleanReturnChainCheckTest',
		'unit.check.SimplifyBooleanTernaryCheckTest',
		'unit.check.SimplifyNegatedCompoundCheckTest',
		'unit.check.SplitVarDeclarationCheckTest',
		'unit.check.StaticConstantCheckTest',
		'unit.check.StringLiteralDupCheckTest',
		'unit.check.StructuralConformanceProofTest',
		'unit.check.SuppressionSliceTest',
		'unit.check.SwallowedExceptionCheckTest',
		'unit.check.TailMergeCheckTest',
		'unit.check.ThreadSafetyCheckTest',
		'unit.check.TrivialGetterCheckTest',
		'unit.check.TrivialGetterIsVarTest',
		'unit.check.TrivialGetterShapeCollapseTest',
		'unit.check.TrivialGetterStaticShadowTest',
		'unit.check.TryCatchNullGuardCheckTest',
		'unit.check.UncheckedNullableTest',
		'unit.check.UnguardedNullableDerefTest',
		'unit.check.UnnecessaryBlockCheckTest',
		'unit.check.UnnecessaryNullCheckCheckTest',
		'unit.check.UnnecessarySafeNavCheckTest',
		'unit.check.UnnecessarySwitchCheckTest',
		'unit.check.UnreachableCatchTest',
		'unit.check.UnusedCaseBinderCheckTest',
		'unit.check.UnusedCaseBinderConstantLanguageTest',
		'unit.check.UnusedLocalShadowTest',
		'unit.check.UnusedParameterCheckTest',
		'unit.check.UnusedPrivateCheckTest',
		'unit.check.UnusedPublicMemberCheckTest',
		'unit.check.UnusedReturnValueTest',
		'unit.check.WhileTrueConditionCheckTest',
		'unit.cli.AddressCliTest',
		'unit.cli.ApqAstTypeRefsCliTest',
		'unit.cli.ApqAtCliTest',
		'unit.cli.ApqCountSummaryCliTest',
		'unit.cli.ApqDxTier2CliTest',
		'unit.cli.ApqDxTier3CliTest',
		'unit.cli.ApqDxTier4CliTest',
		'unit.cli.ApqDxTier5CliTest',
		'unit.cli.ApqExitOnEmptyCliTest',
		'unit.cli.ApqFmtOnePassCliTest',
		'unit.cli.ApqFmtVerifyCliTest',
		'unit.cli.ApqFromFileCliTest',
		'unit.cli.ApqHxqDxV10CliTest',
		'unit.cli.ApqHxqDxV8CliTest',
		'unit.cli.ApqLitCommentsCliTest',
		'unit.cli.ApqLitDirectivesCliTest',
		'unit.cli.ApqMetaCliTest',
		'unit.cli.ApqPrefilterCliTest',
		'unit.cli.ApqProbeCliTest',
		'unit.cli.ApqReconCliTest',
		'unit.cli.ApqSearchCliTest',
		'unit.cli.ApqSourceMetaArgCliTest',
		'unit.cli.ApqStripDryRunCliTest',
		'unit.cli.ApqStripFromClusterCliTest',
		'unit.cli.ApqTestSummaryExitStatusCliTest',
		'unit.cli.ApqWriterEqualsCliTest',
		'unit.cli.ApqWriterProbeCliTest',
		'unit.cli.CliCommandSeamTest',
		'unit.cli.CliHelpListingPinTest',
		'unit.cli.ExtractDestinationCollisionCliTest',
		'unit.cli.LintConfigCliTest',
		'unit.cli.LintFailOnCliTest',
		'unit.cli.LintFixFixedPointCliTest',
		'unit.cli.LintListRulesCliTest',
		'unit.cli.LintNoOracleCliTest',
		'unit.cli.LintPerFileConfigCliTest',
		'unit.cli.LintProjectWriteScopeCliTest',
		'unit.cli.LintRangeCliTest',
		'unit.cli.RenameMemberInFileCliTest',
		'unit.cli.RenameTypeInFileCliTest',
		'unit.cli.ResolutionScopeCliTest',
		'unit.cli.SafeDeleteFormatConfigCliTest',
		'unit.cli.SweepRunCensusCliTest',
		'unit.core.BodyGroupPrefixChargeConsumerTest',
		'unit.core.DocMeasureFirstVisibleTextTest',
		'unit.core.DocRendererTest',
		'unit.core.WriterTrailingWhitespaceTest',
		'unit.format.BraceSymmetrySliceTest',
		'unit.format.CommentInventoryTest',
		'unit.format.DirectiveConditionSpacingTest',
		'unit.format.DocProbeFamilyWalkerTest',
		'unit.format.WhitespaceInvariantTest',
		'unit.format.WrapFlatSourceFixedPointTest',
		'unit.format.WrapProbeRestAwarenessSliceTest',
		'unit.format.WriteOptionsTest',
		'unit.grammar.ArParserTest',
		'unit.grammar.JValueTransformSliceTest',
		'unit.grammar.JsonParserTest',
		'unit.grammar.JsonRoundTripTest',
		'unit.grammar.JsonTypedParserTest',
		'unit.grammar.haxe.AllmanProbe',
		'unit.grammar.haxe.CheckstyleConfigLoaderTest',
		'unit.grammar.haxe.ComplexItemKindsSeamTest',
		'unit.grammar.haxe.CondModProbe',
		'unit.grammar.haxe.ElseSwitchPlacementSliceTest',
		'unit.grammar.haxe.FarthestFailTest',
		'unit.grammar.haxe.HaxeFirstSliceTest',
		'unit.grammar.haxe.HaxeFormatConfigDiagnosticsTest',
		'unit.grammar.haxe.HaxeFormatConfigLoaderTest',
		'unit.grammar.haxe.HaxeModuleSliceTest',
		'unit.grammar.haxe.HaxeWriterRoundTripTest',
		'unit.grammar.haxe.HxAbstractClassSliceTest',
		'unit.grammar.haxe.HxAbstractClauseSpacingTest',
		'unit.grammar.haxe.HxAbstractSliceTest',
		'unit.grammar.haxe.HxAccessorSliceTest',
		'unit.grammar.haxe.HxAfterLeftCurlySliceTest',
		'unit.grammar.haxe.HxAfterPackageSliceTest',
		'unit.grammar.haxe.HxAnonFieldTypeProjectionTest',
		'unit.grammar.haxe.HxAnonFnBodyStmtPositionSliceTest',
		'unit.grammar.haxe.HxAnonFuncEmptyParensInnerSpaceOptionsTest',
		'unit.grammar.haxe.HxAnonFuncParensOptionsTest',
		'unit.grammar.haxe.HxAnonMemberSliceTest',
		'unit.grammar.haxe.HxAnonTypeBracesOptionsTest',
		'unit.grammar.haxe.HxAnonTypeIgnoreReflowTest',
		'unit.grammar.haxe.HxAnonTypeSourceTrailCommaSliceTest',
		'unit.grammar.haxe.HxAnonVarFieldSliceTest',
		'unit.grammar.haxe.HxArrayComprehensionSliceTest',
		'unit.grammar.haxe.HxArrayExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxArrowArraySliceTest',
		'unit.grammar.haxe.HxArrowBlockBodyOpenSliceTest',
		'unit.grammar.haxe.HxArrowBlockIfOverflowSliceTest',
		'unit.grammar.haxe.HxArrowFnExprSliceTest',
		'unit.grammar.haxe.HxArrowFnOldStyleRewriteTest',
		'unit.grammar.haxe.HxArrowFnTypeSliceTest',
		'unit.grammar.haxe.HxArrowParamOptionalNamedSliceTest',
		'unit.grammar.haxe.HxArrowPlainIfOpenSliceTest',
		'unit.grammar.haxe.HxArrowResidualLineWrapSliceTest',
		'unit.grammar.haxe.HxArrowValueIfReflowSliceTest',
		'unit.grammar.haxe.HxAssignChainWrapSliceTest',
		'unit.grammar.haxe.HxAssignSliceTest',
		'unit.grammar.haxe.HxAssignStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxBeforeTrailCommentWriteTest',
		'unit.grammar.haxe.HxBeforeUsingSliceTest',
		'unit.grammar.haxe.HxBinaryChainWrapSliceTest',
		'unit.grammar.haxe.HxBinopGroupWrapSliceTest',
		'unit.grammar.haxe.HxBinopStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxBitwiseSliceTest',
		'unit.grammar.haxe.HxBlankAfterLeadingCommentSliceTest',
		'unit.grammar.haxe.HxBlankAroundMultilineMembersTest',
		'unit.grammar.haxe.HxBlockCommentCloseWriteTest',
		'unit.grammar.haxe.HxBlockExprSliceTest',
		'unit.grammar.haxe.HxBodySliceTest',
		'unit.grammar.haxe.HxBracketExprListTypeSliceTest',
		'unit.grammar.haxe.HxCallArgCommentWriteTest',
		'unit.grammar.haxe.HxCallArgMultilineStringCuddleTest',
		'unit.grammar.haxe.HxCallGroupRestProbeCasePatternTest',
		'unit.grammar.haxe.HxCallGroupRestProbeChainOperandTest',
		'unit.grammar.haxe.HxCallGroupRestProbeNestedArgTest',
		'unit.grammar.haxe.HxCallParamFunctionLambdaSliceTest',
		'unit.grammar.haxe.HxCallParamIfExpressionArgSliceTest',
		'unit.grammar.haxe.HxCallParamNestedArrayHugSliceTest',
		'unit.grammar.haxe.HxCallParamObjectLiteralSliceTest',
		'unit.grammar.haxe.HxCallParamOuterFirstWrapSliceTest',
		'unit.grammar.haxe.HxCaseBodyBlankSliceTest',
		'unit.grammar.haxe.HxCaseBodyControlFlowGlueTest',
		'unit.grammar.haxe.HxCaseBodyFitLineSliceTest',
		'unit.grammar.haxe.HxCaseBodyPolicySliceTest',
		'unit.grammar.haxe.HxCaseBodySameLineSliceTest',
		'unit.grammar.haxe.HxCaseBodyShapeRefusalTest',
		'unit.grammar.haxe.HxCaseBodySymmetrySliceTest',
		'unit.grammar.haxe.HxCaseBodyTrailCommentInlineTest',
		'unit.grammar.haxe.HxCaseCaptureSliceTest',
		'unit.grammar.haxe.HxCaseCommentWriteTest',
		'unit.grammar.haxe.HxCaseExprPositionPropagateTest',
		'unit.grammar.haxe.HxCaseGuardFitSliceTest',
		'unit.grammar.haxe.HxCastSliceTest',
		'unit.grammar.haxe.HxCatchBodySliceTest',
		'unit.grammar.haxe.HxChainFillBoundaryCallOperandTest',
		'unit.grammar.haxe.HxChainOuterOperatorWrapSliceTest',
		'unit.grammar.haxe.HxChainStaircaseSliceTest',
		'unit.grammar.haxe.HxCompareOperandBreakSliceTest',
		'unit.grammar.haxe.HxComplexItemWrapTest',
		'unit.grammar.haxe.HxComprehensionBlockHugSliceTest',
		'unit.grammar.haxe.HxComprehensionBracketPolicyTest',
		'unit.grammar.haxe.HxComprehensionChainIdempotencyTest',
		'unit.grammar.haxe.HxComprehensionCloserSliceTest',
		'unit.grammar.haxe.HxComprehensionCuddledOpenTest',
		'unit.grammar.haxe.HxComprehensionDeclRhsBracketWrapTest',
		'unit.grammar.haxe.HxComprehensionFilterMeasureTest',
		'unit.grammar.haxe.HxComprehensionFitLineNoBreakTest',
		'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest',
		'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest',
		'unit.grammar.haxe.HxCondCommentDirectiveSeamTest',
		'unit.grammar.haxe.HxCondCommentWriteTest',
		'unit.grammar.haxe.HxCondCompStmtTrailOptSliceTest',
		'unit.grammar.haxe.HxCondDeclElseTrailingMetaTest',
		'unit.grammar.haxe.HxCondDeclPrefixKeywordSliceTest',
		'unit.grammar.haxe.HxCondDeclPrefixSliceTest',
		'unit.grammar.haxe.HxCondElseifChainBlankTest',
		'unit.grammar.haxe.HxCondExprValueFixpointSliceTest',
		'unit.grammar.haxe.HxCondForContainerGlueSliceTest',
		'unit.grammar.haxe.HxCondHeritageSliceTest',
		'unit.grammar.haxe.HxCondListSeparatorWriteTest',
		'unit.grammar.haxe.HxCondMemberSlotSliceTest',
		'unit.grammar.haxe.HxCondModSliceTest',
		'unit.grammar.haxe.HxCondParamElseSepSliceTest',
		'unit.grammar.haxe.HxCondPlainCallLeadingBreakSliceTest',
		'unit.grammar.haxe.HxCondSpliceChainWrapSliceTest',
		'unit.grammar.haxe.HxCondSpliceExprSliceTest',
		'unit.grammar.haxe.HxCondSpliceFidelitySliceTest',
		'unit.grammar.haxe.HxCondSpliceOpFillSliceTest',
		'unit.grammar.haxe.HxCondSpliceOwnLineSliceTest',
		'unit.grammar.haxe.HxCondSpliceReturnBlockSliceTest',
		'unit.grammar.haxe.HxCondSpliceScopeSliceTest',
		'unit.grammar.haxe.HxCondTypeSlotSliceTest',
		'unit.grammar.haxe.HxCondUnbalancedRegionSliceTest',
		'unit.grammar.haxe.HxCondVarInitSliceTest',
		'unit.grammar.haxe.HxCondWrapFitLineSliceTest',
		'unit.grammar.haxe.HxConditionalExprFitSliceTest',
		'unit.grammar.haxe.HxConditionalMemberSliceTest',
		'unit.grammar.haxe.HxConditionalObjectFieldSliceTest',
		'unit.grammar.haxe.HxConditionalParamSliceTest',
		'unit.grammar.haxe.HxConditionalSourceBlankSliceTest',
		'unit.grammar.haxe.HxConditionalTypeSliceTest',
		'unit.grammar.haxe.HxConstStringTypeSliceTest',
		'unit.grammar.haxe.HxContainerItemWrapTest',
		'unit.grammar.haxe.HxControlFlowPoliciesOptionsTest',
		'unit.grammar.haxe.HxControlFlowSliceTest',
		'unit.grammar.haxe.HxDeclHeaderEqBreakOverflowTest',
		'unit.grammar.haxe.HxDeclInitMultilineStringCuddleTest',
		'unit.grammar.haxe.HxDoWhileThrowTryCatchSliceTest',
		'unit.grammar.haxe.HxDollarBlockExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxDollarReifSliceTest',
		'unit.grammar.haxe.HxDottedMetaNameSliceTest',
		'unit.grammar.haxe.HxECheckTypeSliceTest',
		'unit.grammar.haxe.HxEllipsisMemberSliceTest',
		'unit.grammar.haxe.HxEllipsisStmtSliceTest',
		'unit.grammar.haxe.HxElseIfBodyBreakTest',
		'unit.grammar.haxe.HxElseIfCommentReflowSliceTest',
		'unit.grammar.haxe.HxElseIfOptionsTest',
		'unit.grammar.haxe.HxElseifTypeSliceTest',
		'unit.grammar.haxe.HxEmptyCurlyOptionsTest',
		'unit.grammar.haxe.HxEnumAbstractSliceTest',
		'unit.grammar.haxe.HxEnumScopeEmptyLinesSliceTest',
		'unit.grammar.haxe.HxExprIdentGuardSliceTest',
		'unit.grammar.haxe.HxExprParenDivOpenBoundaryTest',
		'unit.grammar.haxe.HxExprParenObjectLitGlueTest',
		'unit.grammar.haxe.HxExprSliceTest',
		'unit.grammar.haxe.HxExprStmtTerminatorSliceTest',
		'unit.grammar.haxe.HxFileHeaderCommentSliceTest',
		'unit.grammar.haxe.HxFillAfterCollectionTest',
		'unit.grammar.haxe.HxFillLeadingCommentTest',
		'unit.grammar.haxe.HxFillLinePerGapSepTest',
		'unit.grammar.haxe.HxFinalMemberSliceTest',
		'unit.grammar.haxe.HxFinalUntypedSliceTest',
		'unit.grammar.haxe.HxFitLineBodyGlueSliceTest',
		'unit.grammar.haxe.HxFnExprBodySliceTest',
		'unit.grammar.haxe.HxFnExprSliceTest',
		'unit.grammar.haxe.HxFnMemberTrailSemiSliceTest',
		'unit.grammar.haxe.HxFnReturnBodySliceTest',
		'unit.grammar.haxe.HxFnSigExceedsBoundaryWrapTest',
		'unit.grammar.haxe.HxFnSigFillLastParamBoundaryTest',
		'unit.grammar.haxe.HxFnSigSingleParamWrapIndentTest',
		'unit.grammar.haxe.HxForEnumVoidSliceTest',
		'unit.grammar.haxe.HxForKeyValueSliceTest',
		'unit.grammar.haxe.HxFormatterCorpusTest',
		'unit.grammar.haxe.HxFormatterOffTest',
		'unit.grammar.haxe.HxFunctionBodyPolicySliceTest',
		'unit.grammar.haxe.HxGlueWidthSliceTest',
		'unit.grammar.haxe.HxGroupRestProbeStructStarTest',
		'unit.grammar.haxe.HxGroupTrailCommentWriteTest',
		'unit.grammar.haxe.HxHeadCommentSeamWriteTest',
		'unit.grammar.haxe.HxHeaderWrapLadderSliceTest',
		'unit.grammar.haxe.HxHeritageCommentWriteTest',
		'unit.grammar.haxe.HxHeritageLineWrapSliceTest',
		'unit.grammar.haxe.HxHeritageSliceTest',
		'unit.grammar.haxe.HxIfBodyBlockCaseBarrierTest',
		'unit.grammar.haxe.HxIfExprCondWrapSliceTest',
		'unit.grammar.haxe.HxIfExprTrailSemiSliceTest',
		'unit.grammar.haxe.HxIfPolicyOptionsTest',
		'unit.grammar.haxe.HxIfStmtExprPositionDispatchTest',
		'unit.grammar.haxe.HxImportAliasInSliceTest',
		'unit.grammar.haxe.HxImportAliasSliceTest',
		'unit.grammar.haxe.HxIncrDecrSliceTest',
		'unit.grammar.haxe.HxIndentCaseLabelsOptionsTest',
		'unit.grammar.haxe.HxIndentComplexValueExpressionsOptionsTest',
		'unit.grammar.haxe.HxIndentObjectLiteralOptionsTest',
		'unit.grammar.haxe.HxInfixCommentWriteTest',
		'unit.grammar.haxe.HxInlineBlockCommentGapTest',
		'unit.grammar.haxe.HxInlineBlockCommentWriteTest',
		'unit.grammar.haxe.HxInlineExprSliceTest',
		'unit.grammar.haxe.HxInterMemberBlankLinesOptionsTest',
		'unit.grammar.haxe.HxInterfaceInterMemberBlankLinesOptionsTest',
		'unit.grammar.haxe.HxIntervalPolicySliceTest',
		'unit.grammar.haxe.HxIsSliceTest',
		'unit.grammar.haxe.HxIsStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxLambdaParamDefaultSliceTest',
		'unit.grammar.haxe.HxLambdaParamOptionalSliceTest',
		'unit.grammar.haxe.HxLeftCurlyOptionsTest',
		'unit.grammar.haxe.HxLineCommentIndentSliceTest',
		'unit.grammar.haxe.HxListLiteralEmissionSliceTest',
		'unit.grammar.haxe.HxLocalFnStmtSliceTest',
		'unit.grammar.haxe.HxLocalVarMetaSliceTest',
		'unit.grammar.haxe.HxLoopBodyIfElseSliceTest',
		'unit.grammar.haxe.HxMacroClassSliceTest',
		'unit.grammar.haxe.HxMacroModHexSliceTest',
		'unit.grammar.haxe.HxMacroTypeExprSliceTest',
		'unit.grammar.haxe.HxMaxAnywhereInFileSliceTest',
		'unit.grammar.haxe.HxMeasuredMultilineDeclBlankSliceTest',
		'unit.grammar.haxe.HxMemberVarTrailOptSliceTest',
		'unit.grammar.haxe.HxMetaAllmanObjectLitSliceTest',
		'unit.grammar.haxe.HxMetaCallStmtSpaceTest',
		'unit.grammar.haxe.HxMetaExprSliceTest',
		'unit.grammar.haxe.HxMetaExprStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxMethodChainAllOrNothingSliceTest',
		'unit.grammar.haxe.HxMethodChainCallParamRestAwareSliceTest',
		'unit.grammar.haxe.HxMethodChainCloseTrailingTest',
		'unit.grammar.haxe.HxMethodChainCuddledLinkTest',
		'unit.grammar.haxe.HxMethodChainDotBreakOverReglueSliceTest',
		'unit.grammar.haxe.HxMethodChainEmitTest',
		'unit.grammar.haxe.HxMethodChainExactLimitBoundaryTest',
		'unit.grammar.haxe.HxMethodChainWrapCapabilityTest',
		'unit.grammar.haxe.HxModifierFlattenSliceTest',
		'unit.grammar.haxe.HxModifierSliceTest',
		'unit.grammar.haxe.HxMultiPatternCaseSliceTest',
		'unit.grammar.haxe.HxMultiVarDeclSliceTest',
		'unit.grammar.haxe.HxMultilineDeclSliceTest',
		'unit.grammar.haxe.HxNamedFnExprSliceTest',
		'unit.grammar.haxe.HxNoBodyAbstractTest',
		'unit.grammar.haxe.HxNumericSeparatorSliceTest',
		'unit.grammar.haxe.HxObjectFieldColonOptionsTest',
		'unit.grammar.haxe.HxObjectLitArrowBodyPadSliceTest',
		'unit.grammar.haxe.HxObjectLitBracesOptionsTest',
		'unit.grammar.haxe.HxObjectLitLeftCurlyOptionsTest',
		'unit.grammar.haxe.HxObjectLitRestProbeTest',
		'unit.grammar.haxe.HxObjectLitSliceTest',
		'unit.grammar.haxe.HxObjectLitSourceTrailCommaSliceTest',
		'unit.grammar.haxe.HxObjectLitStmtNoSemiSliceTest',
		'unit.grammar.haxe.HxObjectLitWrapRulesTest',
		'unit.grammar.haxe.HxOpAddChainOperatorFirstSliceTest',
		'unit.grammar.haxe.HxOpAddParenInnerBreakTest',
		'unit.grammar.haxe.HxOpAddTrailingParenGlueSliceTest',
		'unit.grammar.haxe.HxOpenDelimStashBarrierTest',
		'unit.grammar.haxe.HxOptionalSemicolonSliceTest',
		'unit.grammar.haxe.HxOrphanPrefixDeclSliceTest',
		'unit.grammar.haxe.HxOverloadMetaSliceTest',
		'unit.grammar.haxe.HxPackedOrOnePerLineTest',
		'unit.grammar.haxe.HxParamBodyUntypedSliceTest',
		'unit.grammar.haxe.HxParamCommentWriteTest',
		'unit.grammar.haxe.HxParamSliceTest',
		'unit.grammar.haxe.HxParenSliceTest',
		'unit.grammar.haxe.HxParenTernaryOpenWrapSliceTest',
		'unit.grammar.haxe.HxParenValueIfOpenWrapSliceTest',
		'unit.grammar.haxe.HxParenWrapSourceNewlineSliceTest',
		'unit.grammar.haxe.HxPostfixSliceTest',
		'unit.grammar.haxe.HxPpCondDottedSliceTest',
		'unit.grammar.haxe.HxPrattOpsTest',
		'unit.grammar.haxe.HxPrattSliceTest',
		'unit.grammar.haxe.HxPrefixSliceTest',
		'unit.grammar.haxe.HxRegexLitSliceTest',
		'unit.grammar.haxe.HxReturnBodySliceTest',
		'unit.grammar.haxe.HxReturnCallOpenParenSliceTest',
		'unit.grammar.haxe.HxReturnValueBreaksInsideTest',
		'unit.grammar.haxe.HxRhsCommentWriteTest',
		'unit.grammar.haxe.HxRightCurlyOptionsTest',
		'unit.grammar.haxe.HxSameLineOptionsTest',
		'unit.grammar.haxe.HxSemicolonBeforeElseSliceTest',
		'unit.grammar.haxe.HxSepStarCloseTrailCommentTest',
		'unit.grammar.haxe.HxSharpErrorSliceTest',
		'unit.grammar.haxe.HxSingleStmtBracesSliceTest',
		'unit.grammar.haxe.HxSoleArgGluedCloseDedentTest',
		'unit.grammar.haxe.HxSoleItemCuddledBracketsTest',
		'unit.grammar.haxe.HxSourceBlankPreserveSliceTest',
		'unit.grammar.haxe.HxSpreadSliceTest',
		'unit.grammar.haxe.HxStaticLocalStmtSliceTest',
		'unit.grammar.haxe.HxStmtBeforeCaseNoSemiSliceTest',
		'unit.grammar.haxe.HxStmtBlockEndNoSemiSliceTest',
		'unit.grammar.haxe.HxStringEscapeTest',
		'unit.grammar.haxe.HxStringInterpNoFormatSliceTest',
		'unit.grammar.haxe.HxStringSliceTest',
		'unit.grammar.haxe.HxStructFieldTrailPresentSliceTest',
		'unit.grammar.haxe.HxSwitchAfterParenSpaceSliceTest',
		'unit.grammar.haxe.HxSwitchBareSliceTest',
		'unit.grammar.haxe.HxSwitchGuardSliceTest',
		'unit.grammar.haxe.HxSwitchNewSliceTest',
		'unit.grammar.haxe.HxSwitchSubjectParensStripSliceTest',
		'unit.grammar.haxe.HxTernaryBranchChainIndentTest',
		'unit.grammar.haxe.HxTernaryCallArgRestAwareTest',
		'unit.grammar.haxe.HxTernaryCollectionHugSliceTest',
		'unit.grammar.haxe.HxTernaryCommentWriteTest',
		'unit.grammar.haxe.HxTernaryCuddleProbeShapeTest',
		'unit.grammar.haxe.HxTernaryCuddledBracesTest',
		'unit.grammar.haxe.HxTernaryDeclInitRestAwareTest',
		'unit.grammar.haxe.HxTernarySliceTest',
		'unit.grammar.haxe.HxThinArrowIfElseBreakSliceTest',
		'unit.grammar.haxe.HxThinArrowSliceTest',
		'unit.grammar.haxe.HxThinArrowTrailingLambdaSliceTest',
		'unit.grammar.haxe.HxThrowBodySliceTest',
		'unit.grammar.haxe.HxTopLevelSliceTest',
		'unit.grammar.haxe.HxToplevelImportUsingSliceTest',
		'unit.grammar.haxe.HxToplevelImportWildSliceTest',
		'unit.grammar.haxe.HxToplevelMetaSliceTest',
		'unit.grammar.haxe.HxToplevelPackageSliceTest',
		'unit.grammar.haxe.HxToplevelVarFnSliceTest',
		'unit.grammar.haxe.HxTrailOptSourceTrackSliceTest',
		'unit.grammar.haxe.HxTrailingCommaOptionsTest',
		'unit.grammar.haxe.HxTrailingSepSliceTest',
		'unit.grammar.haxe.HxTransformSliceTest',
		'unit.grammar.haxe.HxTriviaParseTest',
		'unit.grammar.haxe.HxTriviaTypesTest',
		'unit.grammar.haxe.HxTriviaWriteTest',
		'unit.grammar.haxe.HxTryBodyOptionsTest',
		'unit.grammar.haxe.HxTryBraceSymmetrySliceTest',
		'unit.grammar.haxe.HxTryExprSliceTest',
		'unit.grammar.haxe.HxTryPolicyOptionsTest',
		'unit.grammar.haxe.HxTypeAnonSliceTest',
		'unit.grammar.haxe.HxTypeArrowSliceTest',
		'unit.grammar.haxe.HxTypeIntersectionSliceTest',
		'unit.grammar.haxe.HxTypeParamDefaultEqualsOptionsTest',
		'unit.grammar.haxe.HxTypeParamFieldNoWrapSliceTest',
		'unit.grammar.haxe.HxTypeParamSliceTest',
		'unit.grammar.haxe.HxTypeParamSpacingOptionsTest',
		'unit.grammar.haxe.HxTypeParensSliceTest',
		'unit.grammar.haxe.HxTypedefAnonForceMultiTest',
		'unit.grammar.haxe.HxTypedefAssignOptionsTest',
		'unit.grammar.haxe.HxTypedefBetweenBlankTest',
		'unit.grammar.haxe.HxTypedefSemiSliceTest',
		'unit.grammar.haxe.HxUniformStatementBlanksSliceTest',
		'unit.grammar.haxe.HxUntypedBodyPolicySliceTest',
		'unit.grammar.haxe.HxValueIfBracketHugSliceTest',
		'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest',
		'unit.grammar.haxe.HxValueIfFitSliceTest',
		'unit.grammar.haxe.HxVarInitBreakAfterEqOverflowTest',
		'unit.grammar.haxe.HxVarNoTypeSliceTest',
		'unit.grammar.haxe.HxVarStmtTrailOptSliceTest',
		'unit.grammar.haxe.HxVarTrailOptShapeSliceTest',
		'unit.grammar.haxe.HxVarTypeHintAnonIndentTest',
		'unit.grammar.haxe.HxWrapConditionVocabularyTest',
		'unit.grammar.haxe.HxWrapRulesIngestTest',
		'unit.grammar.haxe.PairedConvertersSmokeTest',
		'unit.grammar.haxe.Probe147',
		'unit.grammar.haxe.ProbeIssue344',
		'unit.grammar.haxe.ProbeMetadataLineEnd',
		'unit.grammar.haxe.ProbeTypedefTrivia',
		'unit.grammar.haxe.TriviaScanSliceTest',
		'unit.lowering.BeforeLeadingCommentSlotTest',
		'unit.lowering.FmtFlagOwnershipTest',
		'unit.lowering.GeneratedLexicalScanSecondGrammarTest',
		'unit.lowering.RegexFirstBytesTest',
		'unit.lowering.StarBlockEndedTest',
		'unit.lowering.StarBlockEndedWsRewindSitesTest',
		'unit.lowering.StarBlockEndedWsRewindTest',
		'unit.lowering.StarSepStartsElementTest',
		'unit.lowering.WriterFamilyCtxBundleTest',
		'unit.query.AddElementSliceTest',
		'unit.query.AddImportSliceTest',
		'unit.query.AddMemberSliceTest',
		'unit.query.AddMetaSliceTest',
		'unit.query.AddParamSliceTest',
		'unit.query.AddressTest',
		'unit.query.ApqAstChildCountTest',
		'unit.query.ApqAstIntegrationTest',
		'unit.query.ApqAstSelectFuzzyTest',
		'unit.query.ApqAstWriterOutputPlainTest',
		'unit.query.ApqDepthSemanticsTest',
		'unit.query.ApqDocSourceTest',
		'unit.query.ApqDottedAccessNudgeTest',
		'unit.query.ApqHxtestSection1ConfigTest',
		'unit.query.ApqIfStmtChildOrderTest',
		'unit.query.ApqJsonSchemaProbe',
		'unit.query.ApqMatcherTest',
		'unit.query.ApqMetaAnonFieldSliceTest',
		'unit.query.ApqMetaEnumCtorSliceTest',
		'unit.query.ApqMetaTest',
		'unit.query.ApqRefsIncrDecrSliceTest',
		'unit.query.ApqRefsTest',
		'unit.query.ApqSelectorTest',
		'unit.query.ApqSkipParseLocusTest',
		'unit.query.ApqSourceDedentTest',
		'unit.query.ApqSourceSelectTest',
		'unit.query.ApqSpanFlowTest',
		'unit.query.ApqTestSummaryTinkTest',
		'unit.query.ApqTextRenderTest',
		'unit.query.ApqUsesTest',
		'unit.query.BodySlotGuardSliceTest',
		'unit.query.BuildFailureTest',
		'unit.query.CachingGrammarPluginTest',
		'unit.query.CallGraphTest',
		'unit.query.ChangeSigSliceTest',
		'unit.query.ClassifyOccurrencesTest',
		'unit.query.CliAtomicWriteSliceTest',
		'unit.query.ClustersTest',
		'unit.query.CommentOwnerGuardSliceTest',
		'unit.query.CommentRewriteSliceTest',
		'unit.query.CommentWeldDeletionSliceTest',
		'unit.query.CondBranchSplitTest',
		'unit.query.CrossRenameMemberSliceTest',
		'unit.query.CrossRenameSliceTest',
		'unit.query.DeleteBlankLineSliceTest',
		'unit.query.DocOwnerGuardSliceTest',
		'unit.query.EncapsulateFieldSliceTest',
		'unit.query.ExtractConstantSliceTest',
		'unit.query.ExtractInterfaceSliceTest',
		'unit.query.ExtractMethodSliceTest',
		'unit.query.ExtractSuperclassSliceTest',
		'unit.query.ExtractVarSliceTest',
		'unit.query.FieldRefScanTest',
		'unit.query.FieldRenameTest',
		'unit.query.FmtSliceTest',
		'unit.query.FormatConfigDiscoveryTest',
		'unit.query.GlobExpandTest',
		'unit.query.HaxelibResolverTest',
		'unit.query.ImplicitStdScopeTest',
		'unit.query.InheritanceMoveSliceTest',
		'unit.query.InlineMethodSliceTest',
		'unit.query.InlineSliceTest',
		'unit.query.InnermostScopeSpanParityTest',
		'unit.query.IntroduceParameterObjectSliceTest',
		'unit.query.JsonSpanCoordinatesTest',
		'unit.query.LexicalRegionsSeamTest',
		'unit.query.LexicalRegionsTest',
		'unit.query.LintDiffTest',
		'unit.query.LintFixSafePassRevertTest',
		'unit.query.LocalTypeAnnotationProjectionTest',
		'unit.query.MakeFinalSliceTest',
		'unit.query.MetaElementSpanSliceTest',
		'unit.query.ModifierKindSeamTest',
		'unit.query.MoveCanonicalOutputSliceTest',
		'unit.query.MoveExtractDocCensusTest',
		'unit.query.MoveFamilyCaptureTest',
		'unit.query.MoveGuardedImportCarryTest',
		'unit.query.MoveMemberSliceTest',
		'unit.query.MoveSymbolSliceTest',
		'unit.query.MutationVerdictTest',
		'unit.query.NameMentionScanTest',
		'unit.query.NewFileSliceTest',
		'unit.query.OpaqueCondRegionScanTest',
		'unit.query.ParenGuardSliceTest',
		'unit.query.ParseFailureLocusTest',
		'unit.query.PatchSliceTest',
		'unit.query.PatternParseProbe',
		'unit.query.RefsCacheTest',
		'unit.query.RemoveElementSliceTest',
		'unit.query.RemoveImportSliceTest',
		'unit.query.RemoveMemberDocSliceTest',
		'unit.query.RemoveMemberSliceTest',
		'unit.query.RemoveParamSliceTest',
		'unit.query.RenameSliceTest',
		'unit.query.ReplaceNodeSliceTest',
		'unit.query.ResolutionLibraryCacheTest',
		'unit.query.ResolutionProjectFilesTest',
		'unit.query.RewriteSliceTest',
		'unit.query.SafeDeleteSliceTest',
		'unit.query.SetCommentSliceTest',
		'unit.query.SetDocSliceTest',
		'unit.query.SetModifierSliceTest',
		'unit.query.ShardPlanTest',
		'unit.query.SpanTypeInfoPinTest',
		'unit.query.StdResolverReturnTypeTest',
		'unit.query.StdResolverTest',
		'unit.query.StdlibDifferentialTest',
		'unit.query.StdlibDupScanTest',
		'unit.query.StructuralMembershipTest',
		'unit.query.SymbolIndexAliasSliceTest',
		'unit.query.SymbolIndexLayerSeamTest',
		'unit.query.SymbolIndexRunMemoSliceTest',
		'unit.query.SymbolIndexSliceTest',
		'unit.query.SymbolQuerySliceTest',
		'unit.query.ThinArrowParamBindingSliceTest',
		'unit.query.TypeRefPrinterTest',
		'unit.query.TypeResolverSliceTest',
		'unit.runtime.InputTest',
		'unit.runtime.ParseErrorTest',
		'unit.runtime.SpanTest'
	];

	public function testDiscoveryRegistersExactlyTheCensusedClasses(): Void {
		final registered: Array<String> = TestRegistry.classNames().copy();
		registered.sort(Reflect.compare);
		Assert.same(REGISTERED_CLASSES, registered, 'add or remove the class in REGISTERED_CLASSES when you add or remove a test class');
	}

	/** `Runner.addITest` throws "Cannot add the same test twice" — this fails first, and says why. */
	public function testNoClassIsRegisteredTwice(): Void {
		final names: Array<String> = TestRegistry.classNames();
		final seen: Array<String> = [];
		for (name in names) if (!seen.contains(name)) seen.push(name);
		Assert.equals(names.length, seen.length, 'a duplicate registration makes utest throw at run start');
	}

	/**
	 * The generated names have to be the spelling `Type.getClassName` produces:
	 * that is what the `APQ_TEST` filter matches on and what
	 * `apq shard-plan --classes` deals.
	 */
	public function testEveryRegisteredNameResolvesToARealClass(): Void {
		final unresolved: Array<String> = TestRegistry.classNames().filter(name -> Type.resolveClass(name) == null);
		Assert.same([], unresolved, 'every registered name resolves at runtime');
	}

	/** The whole point, stated once: a class no hand-written line names still runs. */
	public function testTheDiscoveryOnlyFixtureIsRegistered(): Void {
		Assert.isTrue(
			TestRegistry.classNames().contains('unit.DiscoveryOnlyProbeTest'),
			'unit.DiscoveryOnlyProbeTest carries no hand-written registration anywhere, on purpose'
		);
	}

	/**
	 * A fixture-named method utest will never run — `static function testX`,
	 * or one on a class that does not implement `utest.ITest`. The tree has
	 * none today; this pin is what makes the first one arrive loudly instead
	 * of joining the 167 dead methods S48 found.
	 */
	public function testTheDeadFixtureCensusIsEmpty(): Void {
		Assert.same([], TestRegistry.deadTests(), 'no fixture-named method is unreachable to utest');
	}

	/**
	 * The metadata pilot, read back through the macro that validates it.
	 *
	 * `@:pin` names what a fixture is FOR and `@:killer` the mutation arm that
	 * must break it; `testkit.TestDiscovery` refuses to build a `control`
	 * naming no arm, which is a compile error and therefore has no fixture of
	 * its own — this is the runtime half, and it is what keeps the metas from
	 * being dropped in a refactor without anything noticing.
	 *
	 * Two hundred and sixty-three entries over sixty-nine classes, and still not a conversion of the
	 * tree: sixteen are the seam coverage for the fourteen rules S73 touched
	 * that its deciding arm cannot reach (docs/testing.md § "The fourteen rules S73 touched that its own arm cannot reach"),
	 * where the arm name is the whole point — it is the only record that the fixture reaches the
	 * moved code, and deleting the fixture now fails HERE rather than silently.
	 */
	public function testThePilotPinsReachTheGeneratedRegistry(): Void {
		Assert.same([
			'unit.MutationArmAddressTest#testEveryDeclaredArmAddressesALiveMember :: control :: M-ARM-PATH-FLAT,M-ARM-KIND-UNSPELLED',
			'unit.MutationArmAddressTest#testEveryFragmentArmStillCutsItsNode :: control :: M-ARM-FRAGMENT-NONE',
			'unit.MutationArmAddressTest#testTheDeferredArmsAreTheOnesTheWalkAnswersFor :: control :: M-ARM-PATH-FLAT',
			'unit.MutationArmsTest#testADuplicateArmNameIsRefused :: guard :: ',
			'unit.MutationArmsTest#testAForcedCutWithANonDefaultKindIsRefused :: control :: M-ARM-ROW-OK',
			'unit.MutationArmsTest#testAKindedArmSpellsItsKindInTheAddress :: control :: M-ARM-KIND-UNSPELLED',
			'unit.MutationArmsTest#testAModulePathBecomesTheTwoCandidateFiles :: control :: M-ARM-PATH-FLAT',
			'unit.MutationArmsTest#testANonJsonTableIsOneComplaint :: guard :: ',
			'unit.MutationArmsTest#testARowDeclaringBothCutsIsRefused :: control :: M-ARM-ROW-OK',
			'unit.MutationArmsTest#testARowDeclaringNeitherCutIsRefused :: control :: M-ARM-ROW-OK,M-ARM-ANYNAME',
			'unit.MutationArmsTest#testAWellFormedTableAnswersByName :: control :: M-ARM-ANYNAME',
			'unit.MutationArmsTest#testAnUndeclaredNameResolvesToNoArm :: control :: M-ARM-ANYNAME',
			'unit.MutationArmsTest#testRenderNamesTheMemberAndTheCut :: guard :: ',
			'unit.ProseClaimCensusTest#testAControlClaimNeedsTheControlRole :: control :: M-CLAIM-ALL-RECORDED',
			'unit.ProseClaimCensusTest#testANegatedArmSentenceClaimsNothing :: control :: M-CLAIM-NEG-BLIND',
			'unit.ProseClaimCensusTest#testAWrappedClaimSurvivesTheLineBreak :: control :: M-CLAIM-RAW-DOC',
			'unit.ProseClaimCensusTest#testAnAnnotationRetiresOnlyTheClaimItRecords :: control :: M-CLAIM-ALL-RECORDED',
			'unit.ProseClaimCensusTest#testAnArmSentenceIsReadAsAnArmClaim :: control :: M-CLAIM-NOKINDS',
			'unit.ProseClaimCensusTest#testTheCodeSenseOfControlIsNotAControlClaim :: control :: M-CLAIM-CODE-BLIND',
			'unit.ProseClaimCensusTest#testTheTwoUnrecordableKindsStayOnTheList :: control :: M-CLAIM-NOKINDS',
			'unit.check.ComparisonToBooleanCheckTest#testFieldAccessBoolMemberFlagged :: control :: M-PATHWALK-NULL',
			'unit.check.DeadBinderCounterLoopCheckTest#testFixRewritesMapLoopAndInsertsUsing :: control :: M-SHADOWEXT-TRUE',
			'unit.check.DuplicateCodeCheckTest#testALiteralInteriorDifferenceIsNotACloneWhileItsLayoutTwinIs :: control :: '
			+ 'M-DUP-CODE-NORM-KEY',
			'unit.check.ExtractRepeatedExpressionTest#testALiteralInteriorDifferenceSplitsTheGroup :: control :: '
			+ 'M-EXTRACT-REPEAT-RENDER-SPLIT',
			'unit.check.FieldInitInConstructorCheckTest#testConstantLandsInTheConstantsRank :: control :: M-LACKSMEMBER-FALSE',
			'unit.check.FieldWriteResolutionScopeTest#testLibraryStructureVetoesOnceStructuralJoins :: control :: '
			+ 'M-CHECKINDEX-PROJECT-FINAL',
			'unit.check.FieldWriteResolutionScopeTest#testOutOfScopePlainClassKeepsTheUnresolvedWritePoison :: control :: '
			+ 'M-PLAINCLASS-SCOPEBLIND',
			'unit.check.FieldWriteResolutionScopeTest#testProjectRootUnresolvedWriteVetoes :: control :: M-ROOTS-THIRDPARTY',
			'unit.check.FieldWriteResolutionScopeTest#testResolvableLibraryInterfaceStopsVetoing :: control :: M-CHECKINDEX-PROJECT-FINAL',
			'unit.check.FieldWriteResolutionScopeTest#testResolvableLibraryInterfaceStopsVetoingWriteRestriction :: control :: '
			+ 'M-CHECKINDEX-PROJECT-READONLY',
			'unit.check.FieldWriteResolutionScopeTest#testSameSimpleNameThirdPartyTypeDoesNotVeto :: control :: M-DECLSITE-SCOPEWIDE',
			'unit.check.FieldWriteResolutionScopeTest#testSkipParsingLibrarySourceDoesNotVetoProjectCandidate :: control :: '
			+ 'M-SKIPSCAN-SCOPEWIDE',
			'unit.check.FieldWriteResolutionScopeTest#testThirdPartySubtypeWriteVetoesFinal :: control :: M-WRITEINDEX-PROJECT-FINAL',
			'unit.check.FieldWriteResolutionScopeTest#testThirdPartySubtypeWriteVetoesReadOnly :: control :: M-WRITEINDEX-PROJECT-READONLY',
			'unit.check.FieldWriteResolutionScopeTest#testThirdPartyUnresolvedWriteDoesNotVeto :: control :: M-ADMITS-TRUE',
			'unit.check.ImpossibleCastTest#testUnrelatedClassesFlagged :: control :: M-UNRELATED-FALSE',
			'unit.check.ImpossibleIsCheckTest#testUnrelatedClassesFlagged :: control :: M-UNRELATED-FALSE',
			'unit.check.JoinSingleUseLocalCheckTest#testAnnotationRestatesSourceFlagged :: control :: M-JSUL-ANNOTATION-NEVER-NEUTRAL',
			'unit.check.JoinSingleUseLocalCheckTest#testCommentBetweenStatementsStillFlagged :: control :: M-JSUL-COMMENT-ANY-IN-FILE',
			'unit.check.JoinSingleUseLocalCheckTest#testConditionalBareIdentStillFlagged :: control :: M-JSUL-BARE-IDENT-NOT-SAFE',
			'unit.check.JoinSingleUseLocalCheckTest#testConditionalRegionWithoutStrayReadStillFlagged :: control :: '
			+ 'M-JSUL-UNINDEXED-NAME-ALWAYS',
			'unit.check.JoinSingleUseLocalCheckTest#testImmutableLocalCaptureStillFlagged :: control :: M-JSUL-LOCAL-CAPTURE-ANY',
			'unit.check.JoinSingleUseLocalCheckTest#testInitIdentNotReboundStillFlagged :: control :: M-JSUL-INIT-IDENT-ALWAYS-REBOUND',
			'unit.check.JoinSingleUseLocalCheckTest#testTrailingStatementWithoutInterpolationStillFlagged :: control :: '
			+ 'M-JSUL-UNINDEXED-NAME-ALWAYS',
			'unit.check.JoinSingleUseLocalCheckTest#testUnconditionalFieldChainStillFlagged :: control :: M-JSUL-PATH-ALWAYS-CONDITIONAL',
			'unit.check.LintFixDeclineWiringSliceTest#testAnAcceptedFileIsWrittenAndBlamesNobody :: control :: M-LINTFIX-ACCEPTED-BLAMED',
			'unit.check.NamingCheckCrossFileFixTest#testCrossFileRenameAsksTheResolutionScopeForUnreadableFiles :: control :: '
			+ 'M-NAMING-SKIPSCAN-REPORT-INDEX,M-SKIPSCAN-SCOPEWIDE',
			'unit.check.NullableSourceResolutionScopeTest#testExcludedArrayPopStaysUnseeded :: control :: M-NULLABLE-INDEX-EXCLUSION',
			'unit.check.NullableSourceResolutionScopeTest#testLibraryReturnBindingSeeded :: control :: M-NULLABLE-FLOW-REPORT-INDEX',
			'unit.check.NullableSourceResolutionScopeTest#testLibraryReturnDerefFlagged :: control :: M-NULLABLE-REPORT-INDEX',
			'unit.check.NullableSourceResolutionScopeTest#testLibraryStaticReturnDerefFlagged :: control :: M-NULLABLE-REPORT-INDEX',
			'unit.check.OrphanAccessorCheckTest#testTheUnresolvedSupertypeArmAlsoSaysWhyNoEditFollows :: control :: '
			+ 'M-ORPHAN-ARMS-SHARE-REASON',
			'unit.check.PossibleNullDereferenceTest#testCallReturnPopFlagged :: control :: M-NULLABLE-NO-CHAIN',
			'unit.check.PossibleNullDereferenceTest#testExistsGuardedEarlyReturnNotFlagged :: control :: M-EXISTS-GUARD-BLIND',
			'unit.check.PossibleNullDereferenceTest#testExistsGuardedThenArmNotFlagged :: control :: M-EXISTS-GUARD-BLIND',
			'unit.check.PossibleNullDereferenceTest#testFieldPathMapExistsGuardedNotFlagged :: control :: M-EXISTS-GUARD-BLIND',
			'unit.check.PossibleNullDereferenceTest#testFieldPathMapReceiverFlagged :: control :: M-NULLABLE-NO-CHAIN',
			'unit.check.PossibleNullDereferenceTest#testNullWrappedMapFlagged :: control :: M-NULLABLE-WRAPPER-OPAQUE',
			'unit.check.PreferCaseGuardCheckTest#testInScopeEnumNotFlagged :: control :: M-DECLARINGFILES-EMPTY',
			'unit.check.PreferEnumAbstractCheckTest#testFixRefusesAnRttiHomonym :: control :: M-RTTI-FALSE',
			'unit.check.PreferEnumAbstractCheckTest#testFixRefusesSubtypedContainer :: control :: M-HASSUBTYPE-FALSE',
			'unit.check.PreferFinalAbstractMethodCheckTest#testAbstractFieldNoCallStillFlagged :: control :: M-PFF-CALLSCAN-ALWAYS',
			'unit.check.PreferFinalAbstractMethodCheckTest#testClassTypedFieldMethodCallStillFlagged :: control :: M-PFF-REBIND-UNRESOLVED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testCtorOnlyAbstractFieldFlagged :: control :: M-PFF-REBIND-UNRESOLVED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testCtorOnlyAbstractLocalFlagged :: control :: M-PFF-REBIND-UNRESOLVED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testForwardToAliasedUnderlyingWhitelistedNameFlagged :: control :: '
			+ 'M-PFF-STDLIB-SAFE-NONE',
			'unit.check.PreferFinalAbstractMethodCheckTest#testForwardToAliasedUnderlyingWhitelistedNameLocalFlagged :: control :: '
			+ 'M-PFF-STDLIB-SAFE-NONE',
			'unit.check.PreferFinalAbstractMethodCheckTest#testForwardToClassAbstractFieldFlagged :: control :: M-PFF-REBIND-UNRESOLVED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testPlainFieldStillFlagged :: control :: M-PFF-CALLSCAN-ALWAYS',
			'unit.check.PreferFinalAbstractMethodCheckTest#testPlainLocalStillFlagged :: control :: M-PFF-CALLSCAN-ALWAYS',
			'unit.check.PreferFinalAbstractMethodCheckTest#testPrivateCtorOnlyNoMetaStillFlagged :: control :: M-PFF-REBIND-UNRESOLVED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testResolutionScopeResolvesLibraryType :: control :: M-SCOPE-LIBRARY-DROPPED',
			'unit.check.PreferFinalAbstractMethodCheckTest#testStdlibArrayFieldMethodCallStillFlagged :: control :: M-PFF-STDLIB-SAFE-NONE',
			'unit.check.PreferFinalAbstractMethodCheckTest#testStdlibStringFieldMethodCallStillFlagged :: control :: '
			+ 'M-PFF-STDLIB-SAFE-NONE',
			'unit.check.PreferIfExpressionAssignmentCheckTest#testFlatTwoBranchStillNotFlagged :: control :: M-TERMINAL-RUNGS-ANY',
			'unit.check.PreferIfExpressionChainCheckTest#testBooleanReducibleUnfoldedRungStillConverts :: control :: '
			+ 'M-PIEC-SPINE-CLAIM-ANY',
			'unit.check.PreferIfExpressionChainCheckTest#testChainWithNoBooleanLeafStillFlagged :: control :: M-PIEC-SPINE-CLAIM-ANY',
			'unit.check.PreferIndexAccessCheckTest#testObjectLiteralSetValueNotFlagged :: control :: M-PIA-OBJLIT-SET-FLAGGED',
			'unit.check.PreferStaticExtensionCheckTest#testMessageKeepsATwoSpaceLiteral :: control :: M-RENDER-SPAN-TOKENS',
			'unit.check.PreferStaticExtensionCheckTest#testMessageQuotesLiteralWhitespaceExactlyAsTheFixWritesIt :: control :: '
			+ 'M-RENDER-SPAN-TOKENS',
			'unit.check.PreferTernaryReturnCheckTest#testOwnLineCommentInACascadeDefersTheTail :: control :: '
			+ 'M-PTR-RIDES-NEVER,M-PTR-CASCADE-NEVER-STRANDS',
			'unit.check.PreferTernaryReturnCheckTest#testTheRunOfOneHoistIsRefusedAtTheSeam :: control :: M-COMMENT-HOIST-BLIND',
			'unit.check.RedundantImportCheckTest#testSubTypeImportBesideItsModuleImportIsRedundant :: control :: M-DECLARINGFILES-EMPTY',
			'unit.check.RedundantReplaceLoopCheckTest#testEmptyLiteralReplacementBoundsTheRedundancyToOneCharacter :: control :: '
			+ 'M-EMPTY-B-ANY-NONEMPTY',
			'unit.check.RedundantReplaceLoopCheckTest#testMultiCharSearchWithEmptyReplacementNotFlagged :: control :: M-SEAM-BLIND',
			'unit.check.RedundantReplaceLoopCheckTest#testReplacementInsideSearchNotFlagged :: control :: M-SEAM-BLIND',
			'unit.check.RedundantReplaceLoopCheckTest#testSeamReformingLiteralPairNotFlagged :: control :: M-SEAM-BLIND',
			'unit.check.RedundantReplaceLoopCheckTest#testSeamReformingLiteralPairSurvivesTheFix :: control :: M-SEAM-BLIND',
			'unit.check.RedundantReplaceLoopCheckTest#testSearchEndingWithTheReplacementHeadNotFlagged :: control :: M-SEAM-BLIND',
			'unit.check.RedundantThisCheckTest#testInheritedFromOtherFileBaseFlagged :: control :: M-INHERITS-FALSE',
			'unit.check.RedundantUpcastTest#testUpcastFlagged :: control :: M-ISSUBTYPE-FALSE',
			'unit.check.ShortenTypeRefCheckTest#testASingleSurvivingOccurrenceEarnsNoImport :: control :: M-SHORTEN-IMPORT-THRESHOLD-ONE',
			'unit.check.StaticConstantCheckTest#testScalarInstanceFinalFlagged :: control :: M-BUILDMACRO-TRUE',
			'unit.check.StructuralConformanceProofTest#testAliasedStructureMemberTypeStillPins :: control :: M-STRUCT-ALIAS-OPAQUE',
			'unit.check.StructuralConformanceProofTest#testAnonStructureNominalStillPins :: control :: M-STRUCT-ANON-CLOSED',
			'unit.check.StructuralConformanceProofTest#testDifferentDeclaredTypeDoesNotPin :: control :: M-STRUCT-NOMINAL-OPEN',
			'unit.check.StructuralConformanceProofTest#testDynamicStructureMemberStillPins :: control :: M-STRUCT-DYNAMIC-CLOSED',
			'unit.check.StructuralConformanceProofTest#testExplicitVarFormStructureRefutesToo :: control :: M-STRUCT-ANON-VAR-KEY',
			'unit.check.StructuralConformanceProofTest#testNullWrappedStructureMemberTypeStillPins :: control :: M-STRUCT-NULL-OPAQUE',
			'unit.check.StructuralConformanceProofTest#testTypeParameterStructureMemberStillPins :: control :: M-STRUCT-TYPEPARAM-CLOSED',
			'unit.check.StructuralConformanceProofTest#testUnresolvableStructureMemberTypeRefutes :: control :: M-STRUCT-UNRESOLVED-OPEN',
			'unit.check.StructuralConformanceProofTest#testUnresolvableSupertypeSuppliesNoMember :: control :: M-STRUCT-DECLARES-LOOSE',
			'unit.check.TailMergeCheckTest#testStructuralIdentityHalfNeeded :: control :: M-TAILMERGE-NORM-ONLY',
			'unit.check.TailMergeCheckTest#testSwitchCaseOutOfScope :: control :: M-TAILMERGE-FALL-KEPT',
			'unit.check.TrivialGetterCheckTest#testBasicBlockBodyFlagged :: control :: M-SUBOVERRIDE-TRUE',
			'unit.check.TrivialGetterShapeCollapseTest#testForeignHierarchyBackingNameStaysAccountedFor :: control :: '
			+ 'M-SUPERDECLARES-FALSE',
			'unit.check.UnguardedNullableDerefTest#testDeclaredNullableFromANullableFieldStillFlagged :: control :: '
			+ 'M-DECL-INIT-RECEIVER-MODE-NOMINAL',
			'unit.check.UnguardedNullableDerefTest#testDeclaredNullableLocalFlagged :: control :: M-DECL-NULLABLE-BLIND',
			'unit.check.UnguardedNullableDerefTest#testDeclaredNullableTernaryWithANullableArmStillFlagged :: control :: '
			+ 'M-DECL-INIT-TERNARY-ANY-ARM',
			'unit.check.UnguardedNullableDerefTest#testDeclaredNullableUnderExistsGuardNotFlagged :: control :: '
			+ 'M-DECL-NULLABLE-OVERRIDES-EXISTS',
			'unit.check.UnguardedNullableDerefTest#testDeclaredNullableWithProvablyNonNullInitializerNotFlagged :: control :: '
			+ 'M-DECL-INIT-NONNULL-BLIND,M-DECL-INIT-LITERAL-BLIND',
			'unit.check.UnguardedNullableDerefTest#testExistsGuardEarlyReturnPathKeySuppressed :: control :: M-EXISTS-GUARD-BLIND',
			'unit.check.UnguardedNullableDerefTest#testFieldPathMapSeedFlagged :: control :: M-NULLABLE-NO-CHAIN',
			'unit.check.UnguardedNullableDerefTest#testReflectCopyBindingNotFlagged :: control :: M-NULLABLE-FLOW-EXCLUDE-NONE',
			'unit.check.UnguardedNullableDerefTest#testSafeNavGuardNarrowsRoot :: control :: M-SAFENAV-NO-NARROW',
			'unit.check.UnreachableCatchTest#testSubtypeAfterSupertypeFlagged :: control :: M-ISSUBTYPE-FALSE',
			'unit.check.UnusedPublicMemberCheckTest#testInterpolationEscapeKeepsTheMember :: control :: M-NAMEOUTSIDE-TRUE',
			'unit.cli.AddressCliTest#testRemoveElementReportFollowsKeepDoc :: control :: M-REMOVE-CUT-ANNOTATIONS-NONE',
			'unit.cli.AddressCliTest#testRemoveElementReportNamesWhatTheCutTook :: control :: M-REMOVE-CUT-ANNOTATIONS-NONE',
			'unit.cli.AddressCliTest#testRemoveElementReportOnAModifierPositionNamesTheDeclaration :: control :: M-REMOVE-CUT-SUBJECT-RAW',
			'unit.cli.ApqTestSummaryExitStatusCliTest#testTruncatedTranscriptDisagreesWithANonZeroExit :: control :: M-EXIT-STATUS-AGREES',
			'unit.cli.CliCommandSeamTest#testTheRegistryHandsOutAFreshCommandPerCall :: control :: M-CLI-COMMANDS-MEMOISED',
			'unit.cli.CliCommandSeamTest#testTheRequireMatchFlagDoesNotSurviveItsRun :: control :: M-CLI-REQUIREMATCH-STATIC',
			'unit.cli.LintRangeCliTest#testWriteFixLeavesAStandingFindingOutsideTheWindow :: control :: M-LINT-RANGE-INERT',
			'unit.format.BraceSymmetrySliceTest#testAWrappedValueThenBranchDropsItsSourceSemicolon :: control :: M-SSB-VALUE-WRAP-OFF',
			'unit.format.BraceSymmetrySliceTest#testTheSameTryOutsideAMacroIsStillBraced :: control :: '
			+ 'M-TRY-BODY-SYM-OFF,M-SSB-TRY-SUBST-OFF',
			'unit.format.BraceSymmetrySliceTest#testTheSemicolonDropAlsoHoldsUnderExpressionIfNext :: control :: M-SSB-VALUE-WRAP-OFF',
			'unit.format.BraceSymmetrySliceTest#testTheStatementAndValueSkipListsAgree :: control :: M-SSB-VALUE-WRAP-OFF',
			'unit.format.BraceSymmetrySliceTest#testThenBareElseBracedGainsBraces :: control :: M-SSB-SYMMETRY-ONLY-BLIND',
			'unit.format.BraceSymmetrySliceTest#testThenBracedElseBareGainsBraces :: control :: M-SSB-SYMMETRY-ONLY-BLIND',
			'unit.grammar.haxe.ComplexItemKindsSeamTest#testTheGeneratedPredicateAnswersTheClassifier :: control :: M-KINDS',
			'unit.grammar.haxe.ComplexItemKindsSeamTest#testTheTriviaFamilyCarriesTheSameEntry :: seam :: ',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testACommentBeforeTheThenSwitchDeclinesBothSeams :: control :: '
			+ 'M-ELSE-SWITCH-CLOSE-COMMENT',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testACommentBetweenElseAndSwitchDeclinesTheGlue :: control :: '
			+ 'M-ELSE-SWITCH-COMMENT-GLUE',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testAnElseIfChainEndingInElseSwitch :: control :: M-ELSE-SWITCH-TESTS-NONE',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testSameGluesTheThenSwitchToItsIfHeadToo :: control :: '
			+ 'M-ELSE-SWITCH-CLOSE-NONE',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testSamePlacesTheSwitchOnTheElseLine :: control :: M-ELSE-SWITCH-TESTS-NONE',
			'unit.grammar.haxe.ElseSwitchPlacementSliceTest#testTheValueIfThenBranchGluesAsWell :: control :: M-ELSE-SWITCH-TESTS-NONE',
			'unit.grammar.haxe.HxArrowBlockIfOverflowSliceTest#testOverflowingBlockIfBreaksAfterArrow :: control :: '
			+ 'M-ARROW-HEAD-WIDTH-NONE',
			'unit.grammar.haxe.HxBlankAroundMultilineMembersTest#testBlankAppearsBeforeAMultilineMember :: control :: '
			+ 'M-BLANK-MULTILINE-OFF',
			'unit.grammar.haxe.HxBlankAroundMultilineMembersTest#testBlankAppearsBetweenMultilineAndSingleLine :: control :: '
			+ 'M-BLANK-MULTILINE-OFF',
			'unit.grammar.haxe.HxCallGroupRestProbeCasePatternTest#testCasePatternCtorInsideACollectionStaysGlued :: control :: '
			+ 'M-PATTERN-RESTPROBE-UNSET',
			'unit.grammar.haxe.HxChainStaircaseSliceTest#testFiveLinkChainStaircasesAsOneShape :: control :: M-CHAIN-STAIRCASE-OFF',
			'unit.grammar.haxe.HxChainStaircaseSliceTest#testIsIdempotentAcrossThreePasses :: control :: M-CHAIN-STAIRCASE-OFF',
			'unit.grammar.haxe.HxChainStaircaseSliceTest#testTornConditionParenIsGone :: control :: M-CHAIN-STAIRCASE-OFF',
			'unit.grammar.haxe.HxChainStaircaseSliceTest#testWholeChainOverTheLimitStaircases :: control :: M-CHAIN-STAIRCASE-OFF',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testFitLineMovesANonFlatBodyOffTheHeadLine :: control :: '
			+ 'M-FIRST-LINE-FIT',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testFitLinePullsUpABodyThatFits :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testKeepReadsTheSourceBreak :: control :: M-ALWAYS-SAME',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testNextLayoutIsIdempotent :: control :: M-ALWAYS-SAME',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testNextPutsTheBodyOnItsOwnLine :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testSameKeepsAFlatBodyOnTheHeadLine :: control :: M-ALWAYS-NEXT',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testSamePullsTheBodyUpOntoTheHeadLine :: control :: M-NO-WIRE',
			'unit.grammar.haxe.HxComprehensionForBodyPolicySliceTest#testTheSpecificKeyOutranksTheExpressionIfFanout :: control :: '
			+ 'M-FANOUT-FIRST',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testFilterIfWithoutElseStillCuddles :: control :: M-CUDDLE-OFF',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyCuddles :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyCuddlesWithTightBrackets :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testIfElseBodyUnderFitLineLeavesTheHeadLine :: control :: '
			+ 'M-FIRST-LINE-FIT',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testNestedComprehensionsChooseTheSameLayout :: control :: M-ELSE-GATE',
			'unit.grammar.haxe.HxComprehensionIfElseBodySliceTest#testNestedComprehensionsUnderFitLineStaircase :: control :: '
			+ 'M-FIRST-LINE-FIT',
			'unit.grammar.haxe.HxCondSpliceOwnLineSliceTest#testOwnLineStatementConditionalAfterMetaBlockStaysStructured :: control :: '
			+ 'M-WORDOP-NO-RESTORE',
			'unit.grammar.haxe.HxCondUnbalancedRegionSliceTest#testBlockTailRegionCollapsesEmptyCatchBody :: control :: '
			+ 'M-COND-BLOCK-TAIL-NEVER',
			'unit.grammar.haxe.HxCondUnbalancedRegionSliceTest#testBlockTailRegionKeepsHeadRawAndBodyStructural :: control :: '
			+ 'M-COND-BLOCK-TAIL-NEVER',
			'unit.grammar.haxe.HxCondUnbalancedRegionSliceTest#testOpenerCloserPairKeepsOpenerACondSpliceStmt :: control :: '
			+ 'M-COND-BLOCK-TAIL-NEVER',
			'unit.grammar.haxe.HxConditionalExprFitSliceTest#testOverwideGluedBreaksAtDirectiveSeams :: control :: M-NEWLINE-SIGNALS-NONE',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testBareBodyElseIfTrailsCommentAfterCondition :: control :: '
			+ 'M-EICR-AFTERCOND-RESET',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testBracedElseIfGluesAndTrailsCommentAfterOpenCurly :: control :: '
			+ 'M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testChainReflowsEveryLinkIndependently :: control :: M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testCommentWithOpenDelimitersIsSafe :: control :: M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testConditionWrapPolicySeesTheRelocatedComment :: control :: '
			+ 'M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testDeepRefusedChainStaysCorrect :: control :: M-EICR-HEADTEXT-ANY',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testDefaultOptionsAreByteInert :: control :: M-KEEP-ELSEIF-ALWAYS-GLUED',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testEmptyThenBodyDoesNotMigrateTheComment :: control :: M-EICR-HEADTEXT-ANY',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testExistingHeadTrailingCommentRefusesReflow :: control :: '
			+ 'M-EICR-HEADTEXT-ANY',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testInlineBodyPolicyLeavesNoAnchorAndRefuses :: control :: '
			+ 'M-EICR-HEADTEXT-ANY',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testKeepElsePolicyDisablesTheReflow :: control :: M-KEEP-ELSEIF-ALWAYS-GLUED',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testKnobOffKeepsEveryPreKnobLayout :: control :: M-EICR-KNOB-IGNORED',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testOverLongGluedHeadLineIsAccepted :: control :: M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testProbeShapedBodyRefusesReflow :: control :: M-EICR-SOFTLINE-ANCHOR',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testReflowedFormsAreIdempotent :: control :: M-EICR-BOUNDARY-SKIP',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testSingleStatementBraceRemovalAndReflowLandInOnePass :: control :: '
			+ 'M-EICR-KNOB-IGNORED',
			'unit.grammar.haxe.HxElseIfCommentReflowSliceTest#testWrappedConditionAnchorsAfterTheOpenCurly :: control :: '
			+ 'M-EICR-BOUNDARY-SKIP,M-EICR-KNOB-IGNORED',
			'unit.grammar.haxe.HxElseIfOptionsTest#testElseIfNextMovesNestedIfToNextLine :: control :: M-KEEP-ELSEIF-NEXT-OFF',
			'unit.grammar.haxe.HxElseIfOptionsTest#testElseIfNextOnlyLastLevelKeepsFirstLevelInline :: control :: M-KEEP-ELSEIF-NEXT-OFF',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testDocOnSecondDeclIsNotAFileHeader :: control :: M-FILEHEADER-ANY-DECL',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testFileHeaderBlankBeforeConditionalImportBlock :: control :: '
			+ 'M-FILEHEADER-COND-OPAQUE',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testFileHeaderBlankBeforeLeadingImport :: control :: M-FILEHEADER-HEAD-NOT-PIU',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testFileHeaderBlankBeforePackage :: control :: M-FILEHEADER-HEAD-NOT-PIU',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testHeaderSeparatedFromDocButDocKeepsItsType :: control :: '
			+ 'M-FILEHEADER-NO-TWO-COMMENT-ARM,M-FILEHEADER-ANY-COMMENT',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testLineCommentHeaderLeavesDocAttached :: control :: '
			+ 'M-FILEHEADER-ANY-COMMENT-KIND,M-FILEHEADER-ANY-COMMENT',
			'unit.grammar.haxe.HxFileHeaderCommentSliceTest#testNoFileHeaderBlankWithoutImports :: control :: M-FILEHEADER-HEAD-ALWAYS-PIU',
			'unit.grammar.haxe.HxFitLineBodyGlueSliceTest#testArrowLambdaBodyGluesAfterTheArrow :: control :: M-PAREN-PIN-NONE',
			'unit.grammar.haxe.HxFitLineBodyGlueSliceTest#testComprehensionFilterBodyGluesToTheIfHead :: control :: M-PAREN-PIN-NONE',
			'unit.grammar.haxe.HxFitLineBodyGlueSliceTest#testGluedBodyIsIdempotent :: control :: M-PAREN-PIN-NONE',
			'unit.grammar.haxe.HxGlueWidthSliceTest#testBreakIsTakenWhenItJustFixesTheOverflow :: control :: M-GLUE-NEVER-BREAKS',
			'unit.grammar.haxe.HxGlueWidthSliceTest#testCaseBodyGlueInheritsTheSameAnswer :: control :: M-GLUE-NEVER-BREAKS',
			'unit.grammar.haxe.HxGlueWidthSliceTest#testGlueTurnedBreakIsNotASiblingSymmetryTrigger :: control :: M-GLUE-NEVER-BREAKS',
			'unit.grammar.haxe.HxGlueWidthSliceTest#testOverWideGluedHeaderBreaksTheBody :: control :: M-GLUE-NEVER-BREAKS',
			'unit.grammar.haxe.HxGlueWidthSliceTest#testReturnBodyGlueInheritsTheSameAnswer :: control :: M-GLUE-NEVER-BREAKS',
			'unit.grammar.haxe.HxGroupRestProbeStructStarTest#testCasePatternTypeParamsDeclineTheRestProbe :: control :: '
			+ 'M-PATTERN-RESTPROBE-UNSET,M-SEPSTAR-RESTPROBE-UNGATED',
			'unit.grammar.haxe.HxGroupRestProbeStructStarTest#testObjectLiteralPatternDeclinesTheRestProbeInBothWriters :: control :: '
			+ 'M-PATTERN-RESTPROBE-UNSET,M-TRIVIASEP-RESTPROBE-UNGATED,M-SEPSTAR-RESTPROBE-UNGATED',
			'unit.grammar.haxe.HxIfExprCondWrapSliceTest#testArrowBodyIfOverflowChainExplodesCond :: control :: M-ARROW-HEAD-WIDTH-NONE',
			'unit.grammar.haxe.HxIfExprCondWrapSliceTest#testExplodedSourceIsIdempotent :: control :: M-ARROW-HEAD-WIDTH-NONE',
			'unit.grammar.haxe.HxIfStmtExprPositionDispatchTest#testElseBodyDualFlagDispatchesAtExpressionPosition :: control :: '
			+ 'M-ELSE-SEP-EXPR-BLIND',
			'unit.grammar.haxe.HxLoopBodyIfElseSliceTest#testBrokenShapeIsIdempotent :: control :: M-LOOPIF-NEVER',
			'unit.grammar.haxe.HxLoopBodyIfElseSliceTest#testForIfElseBreaksUnderHeader :: control :: M-LOOPIF-NEVER',
			'unit.grammar.haxe.HxLoopBodyIfElseSliceTest#testGuardIfWithoutElseStaysGlued :: control :: M-LOOPIF-ALWAYS',
			'unit.grammar.haxe.HxLoopBodyIfElseSliceTest#testNonLoopAndNonIfBodiesUnchanged :: control :: M-LOOPIF-ALWAYS',
			'unit.grammar.haxe.HxLoopBodyIfElseSliceTest#testWhileIfElseBreaksUnderHeader :: control :: M-LOOPIF-NEVER',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testBareThenIfGetsBracesAdded :: control :: M-SSB-WRAP-DIRECTION',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testBareThenOppositeBracedElseGetsBraces :: control :: M-SSB-CHAIN-TAIL-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testBracedCatchBodySealsTryCatchBeforeElse :: control :: '
			+ 'M-SSB-FRAME-OFF,M-SSB-DANGLING-NONE,M-SSB-TAIL-SEALED-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testBracedThenBodySealsNestedGuardLoop :: control :: M-SSB-FRAME-BLANKET',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testChainKeeperForcesBracesOnEveryBareBranch :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testDanglingElseThroughLoopBodyKeepsBraces :: control :: '
			+ 'M-SSB-FRAME-OFF,M-SSB-DANGLING-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testDeepMixedElseIfChainKeepsAllBraced :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testDoWhileBodyUnbraced :: control :: M-SSB-DOBODY-KEEP',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testElseBlockSingleIfCollapsesToElseIf :: control :: M-SSB-GATE8-ANY-POSITION',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testElseIfChainLaterBranchForcesEarlierBraces :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testElseIfChainLinkNotWrapped :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testForBodyBlockSealsThenBodyAndKeepsItsOwnBraces :: control :: '
			+ 'M-SSB-FRAME-OFF,M-SSB-DANGLING-NONE,M-SSB-TAIL-SEALED-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testIfElseAsymmetryKeepsBothBraced :: control :: M-SSB-CHAIN-TAIL-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testIfElseIfChainKeepsBracesWhenAnyBranchMulti :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testLoopBodyLoneIfStillUnbraces :: control :: M-SSB-GATE8-ANY-POSITION',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testOpenTrailingCommentTravelsWithTheStatement :: control :: '
			+ 'M-SSB-OPEN-TRAIL-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testSealedInnerIfDeBracesUnderTrailingElse :: control :: M-SSB-TAIL-SEALED-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testSuppressFrameDoBodyStillUnwraps :: control :: M-SSB-DOBODY-KEEP',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testSuppressedFrameChainBracesEveryBranch :: control :: M-SSB-CHAIN-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testSwitchSealedInnerIfDeBraces :: control :: M-SSB-TAIL-SEALED-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingCommentElseBodyDeBraces :: control :: M-SSB-ELEM-TRAIL-COMMENT-NONE',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingCommentForBodyDeBraces :: control :: M-SSB-TRAIL-COMMENT-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingCommentIfBodyDeBraces :: control :: M-SSB-TRAIL-COMMENT-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingCommentWhileBodyDeBraces :: control :: M-SSB-TRAIL-COMMENT-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingEmptyStmtAfterForDropsSemiAndDeBraces :: control :: '
			+ 'M-SSB-TRAILOPT-REEMIT',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingEmptyStmtAfterIfDropsSemiAndDeBraces :: control :: '
			+ 'M-SSB-TRAILOPT-REEMIT',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingIfWithOwnElseDeBraces :: control :: M-SSB-ELSE-SPINE-STOP',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testTrailingSemiTerminalElseIfDropsSemiAndDeBraces :: control :: '
			+ 'M-SSB-TRAILOPT-REEMIT',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testValueIfBareElseGainsBraces :: control :: M-SSB-VALUE-WRAP-OFF',
			'unit.grammar.haxe.HxSingleStmtBracesSliceTest#testValueIfBareThenGainsBraces :: control :: M-SSB-VALUE-WRAP-OFF',
			'unit.grammar.haxe.HxSoleArgGluedCloseDedentTest#testSoleArgClosingOnContentKeepsTheGluedClose :: control :: '
			+ 'M-ELSE-SEP-EXPR-BLIND',
			'unit.grammar.haxe.HxTriviaWriteTest#testMultipleOwnLineCommentsBetweenBraceAndElseRoundTrip :: control :: '
			+ 'M-BEFORE-KW-LEADING-DROP',
			'unit.grammar.haxe.HxTriviaWriteTest#testOwnLineCommentBetweenBraceAndElseRoundTrip :: control :: M-BEFORE-KW-LEADING-DROP',
			'unit.grammar.haxe.HxTriviaWriteTest#testSameLineCommentBeforeElseAfterStmtRoundTrip :: control :: M-BEFORE-KW-TRAILING-DROP',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testBareCatchDeBracesWithoutAWrapPass :: control :: '
			+ 'M-SSB-BARE-ILLEGAL,M-SSB-TRY-DEBRACE-NONE,M-SSB-TRY-SUBST-OFF',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testBracedGroupDeBraces :: control :: '
			+ 'M-SSB-TRY-DEBRACE-NONE,M-SSB-TRY-SUBST-OFF',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testDanglingElseKeepsBraces :: control :: M-SSB-FRAME-OFF,M-SSB-DANGLING-NONE',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testMultiStatementCatchBracesTheBareTry :: control :: M-SSB-TRY-SUBST-OFF',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testOnlyTheLastCatchKeepsItsTerminator :: control :: '
			+ 'M-TRY-CATCHES-SYM-OFF,M-SSB-TRY-SUBST-OFF,M-SSB-TRY-DEBRACE-NONE',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testOverflowBreaksAtTheSeamNotInsideTheCall :: control :: '
			+ 'M-SSB-TRY-DEBRACE-NONE,M-SSB-TRY-SUBST-OFF',
			'unit.grammar.haxe.HxTryBraceSymmetrySliceTest#testValueTryBracesTheBareBody :: control :: '
			+ 'M-TRY-BODY-SYM-OFF,M-SSB-TRY-SUBST-OFF',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testAnArrayLiteralBranchHugsTheHead :: control :: M-BRACKET-GLUE-NONE',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testTheReportedComprehensionReachesTheTargetLayout :: control :: '
			+ 'M-BRACKET-GLUE-NONE',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testTheSemicolonClosedSourceReachesTheTargetLayout :: control :: '
			+ 'M-BRACKET-GLUE-NONE',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testTheSplitCloserCuddlesTheElseWithNoSemicolonToDrop :: control :: '
			+ 'M-BRACKET-GLUE-NONE',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testTheTargetLayoutIsIdempotent :: control :: M-BRACKET-GLUE-NONE',
			'unit.grammar.haxe.HxValueIfBracketHugSliceTest#testWithoutTheKeyTheSemicolonAndTheBreakBothSurvive :: control :: '
			+ 'M-NONCURLY-SAME-DROP',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testABracketBranchKeepsTheSourceBreak :: control :: '
			+ 'M-EXPR-ELSE-PLAIN-SAME,M-NONCURLY-SAME-DROP',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testAnElseLessValueIfKeepsItsTerminator :: control :: M-SBE-UNGATED',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testAnObjectLiteralBranchKeepsItsOwnLine :: control :: M-ELSE-BODY-SAME',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testKeepStillPreservesTheSourceBreak :: control :: M-KEEP-JOINS',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testTheJoinedLayoutIsIdempotent :: control :: M-CURLY-CTORS-NONE',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testTheReportedValueIfJoinsItsElseToTheCurlyClose :: control :: '
			+ 'M-EXPR-ELSE-KEEP',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testTheSemicolonBeforeElseGoesWithTheJoin :: control :: '
			+ 'M-EXPR-ELSE-KEEP,M-EXPR-ELSE-PLAIN-SAME',
			'unit.grammar.haxe.HxValueIfCurlyElseJoinSliceTest#testTheStatementTwinKeepsTheLayoutItAlwaysHad :: guard :: ',
			'unit.lowering.BeforeLeadingCommentSlotTest#testAMemberWithNoGapCommentIsUnchanged :: guard :: ',
			'unit.lowering.BeforeLeadingCommentSlotTest#testAMultilineGapCommentReachesTheOutput :: control :: '
			+ 'M-BEFORE-LEADING-COMMENT-DROP',
			'unit.lowering.BeforeLeadingCommentSlotTest#testAOneLineGapCommentIsCarriedUpstream :: guard :: ',
			'unit.lowering.StarBlockEndedWsRewindSitesTest#testAConditionalBodyKeepsTheStatementAfterASwallowedTerminator :: control :: '
			+ 'M-PEB-WS-REWIND-TRYPARSE-OFF',
			'unit.lowering.StarBlockEndedWsRewindSitesTest#testAConditionalBodyWithAnOrdinaryTerminatorNeedsNoRewind :: guard :: ',
			'unit.lowering.StarBlockEndedWsRewindSitesTest#testANestedBlockKeepsTheStatementAfterASwallowedTerminator :: control :: '
			+ 'M-PEB-WS-REWIND-SEPSTARTS-OFF',
			'unit.lowering.StarBlockEndedWsRewindSitesTest#testANestedBlockWithAnOrdinaryTerminatorNeedsNoRewind :: guard :: ',
			'unit.lowering.StarBlockEndedWsRewindTest#testASwallowedTerminatorBehindTrailingWhitespaceStillEndsTheStatement :: control '
			+ ':: M-PEB-WS-REWIND-OFF',
			'unit.lowering.StarBlockEndedWsRewindTest#testAnOrdinaryTerminatorNeedsNoRewind :: guard :: ',
			'unit.lowering.StarBlockEndedWsRewindTest#testTheShapeThePredicateAnswersForNeedsNoRewind :: guard :: ',
			'unit.query.AddMetaSliceTest#testCliWritesTheEntry :: control :: M-ADDMETA-CLI-UNROUTED',
			'unit.query.AddMetaSliceTest#testFinalClassWrapperIsLifted :: control :: M-ADDMETA-NO-WRAPPER-CLIMB',
			'unit.query.AddMetaSliceTest#testGuardedTypeKeepsTheEntryInsideTheGuard :: control :: M-ADDMETA-LOOSE-WRAPPER-CLIMB',
			'unit.query.AddMetaSliceTest#testTypeEntryLandsBelowTheDoc :: control :: M-ADDMETA-ZERO-WIDTH-INSERT',
			'unit.query.ApqUsesTest#testQualifiedIsOptInSoRewritersKeepTheExactAnswer :: control :: M-USES-QUALIFIED-DEFAULT',
			'unit.query.ApqUsesTest#testQualifiedSpellingsAcrossTypePositions :: control :: M-USES-EXACT-ONLY',
			'unit.query.ApqUsesTest#testQualifiedSubModuleTypeIsFoundBySimpleName :: control :: M-USES-EXACT-ONLY',
			'unit.query.ApqUsesTest#testQualifiedTailMatchesOnlyOnASegmentBoundary :: control :: M-USES-TAIL-SUBSTRING',
			'unit.query.BodySlotGuardSliceTest#testAllowsAuthoredBodyThatTakesInTheNextStatement :: control :: M-BODYSLOT-AUTHORED-NEVER',
			'unit.query.BodySlotGuardSliceTest#testAllowsHeaderRewriteOfBracelessConstruct :: control :: M-BODYSLOT-LIMIT-EDIT-END',
			'unit.query.BodySlotGuardSliceTest#testAllowsSoleCatchClauseRemoval :: control :: M-BODYSLOT-LEAD-KEPT',
			'unit.query.BodySlotGuardSliceTest#testAllowsSoleCatchClauseRemovalWithATrailingComment :: control :: M-BODYSLOT-TRIM-WS-ONLY',
			'unit.query.BodySlotGuardSliceTest#testAllowsWholeElseBranchRemoval :: control :: M-BODYSLOT-LEAD-KEPT',
			'unit.query.CommentOwnerGuardSliceTest#testACarryDeclarationThatDoesNotHoldIsNotARefusal :: control :: M-COMMENT-CARRY-REFUSES',
			'unit.query.CommentOwnerGuardSliceTest#testACommentThatKeepsItsPlaceUnderACarryIsAccepted :: control :: '
			+ 'M-CARRY-CROSSING-ANY-SIDE',
			'unit.query.CommentOwnerGuardSliceTest#testHoistingACommentPastSurvivingCodeIsRefused :: control :: M-COMMENT-WELD-BLIND',
			'unit.query.CommentOwnerGuardSliceTest#testHoistingAcrossADeclaredCarryIsRefused :: guard :: M-COMMENT-HOIST-BLIND',
			'unit.query.CommentOwnerGuardSliceTest#testWeldingTwoCommentBlocksIsRefused :: control :: M-COMMENT-WELD-BLIND',
			'unit.query.CommentRewriteSliceTest#testLeadingBreakSpaceKeepsTheLineBreak :: control :: M-COMMENT-BOUNDARY-BREAK-KEPT',
			'unit.query.CommentRewriteSliceTest#testLeadingBreakSpaceWithGutterlessReplacement :: control :: M-COMMENT-BOUNDARY-BREAK-KEPT',
			'unit.query.CommentRewriteSliceTest#testParagraphBreakSurvivesALeadingBreakSpaceFind :: control :: '
			+ 'M-COMMENT-BOUNDARY-BREAK-KEPT',
			'unit.query.CommentRewriteSliceTest#testTrailingBreakSpaceKeepsTheLineBreak :: control :: M-COMMENT-BOUNDARY-TRAIL-INDEX',
			'unit.query.CommentWeldDeletionSliceTest#testHoistingInsideAReplacementIsStillRefused :: control :: M-COMMENT-WELD-BLIND',
			'unit.query.CommentWeldDeletionSliceTest#testWeldingAcrossTheRepeatedSeparatorIsStillRefused :: control :: '
			+ 'M-COMMENT-WELD-BLIND',
			'unit.query.DocOwnerGuardSliceTest#testAppendBeforeAClosingBraceIsAccepted :: control :: M-DOCSPLIT-OWNER-ANY',
			'unit.query.DocOwnerGuardSliceTest#testBannerCommentIsNotGuarded :: control :: M-DOCSPAN-BANNER-IS-DOC',
			'unit.query.DocOwnerGuardSliceTest#testModifierInsertOnTheOwnersLineIsAccepted :: control :: M-DOCSPLIT-BREAKLESS-TOO',
			'unit.query.DocOwnerGuardSliceTest#testReplacementStartingAtTheOwnerIsAccepted :: control :: M-DOCSPLIT-COVERING-TOO',
			'unit.query.ExtractInterfaceSliceTest#testAlreadyImplementsRefused :: control :: M-EI-DUP-IMPL-ALLOWED',
			'unit.query.ExtractInterfaceSliceTest#testGuardedImplementsRefused :: control :: M-EI-DUP-IMPL-ALLOWED,M-EI-GUARD-FLAT-SCAN',
			'unit.query.ExtractInterfaceSliceTest#testQualifiedSameNameDoesNotBlock :: control :: M-EI-IMPL-ANY-REFUSED',
			'unit.query.ExtractInterfaceSliceTest#testSecondInterfaceStillExtracts :: control :: M-EI-IMPL-ANY-REFUSED',
			'unit.query.MakeFinalSliceTest#testHalfIteratorShapeStillFinal :: control :: M-STRUCT-BUILTIN-BY-NAME',
			'unit.query.MetaElementSpanSliceTest#testRemoveConditionalModifierRegionStillTakesTheMember :: control :: '
			+ 'M-META-ELEMENT-ANY-COND-REGION',
			'unit.query.MetaElementSpanSliceTest#testRemoveModifierStillTakesTheMemberDoc :: control :: M-CUT-DOC-KEPT-BY-ANY-PREFIX',
			'unit.query.MoveCanonicalOutputSliceTest#testMoveLeavesANonCanonicalSourceUnformatted :: control :: M-MOVE-CANONICALISE-ALWAYS',
			'unit.query.MoveFamilyCaptureTest#testABareWildcardCallerIsRepointedByteIdentically :: control :: M-WILDCARD-REPOINT-NONE',
			'unit.query.MoveFamilyCaptureTest#testALocalShadowKeepsItsBareReadByteIdentically :: control :: M-WILDCARD-BINDING-BLIND',
			'unit.query.MoveFamilyCaptureTest#testARivalWildcardKeepsItsBareCallerByteIdentically :: control :: '
			+ 'M-WILDCARD-RIVAL-ORDER-BLIND',
			'unit.query.MoveFamilyCaptureTest#testASubModuleMoveRepointsNoWildcardCallerByteIdentically :: control :: '
			+ 'M-WILDCARD-BINDS-BLIND',
			'unit.query.MoveSymbolSliceTest#testACommentOnlyFullyQualifiedMentionDoesNotRefuseTheMove :: control :: '
			+ 'M-MOVE-FQN-COMMENT-MASK-NONE',
			'unit.query.MoveSymbolSliceTest#testACommentOnlyMentionIsNotAReference :: control :: M-MOVE-NAMESCAN-COMMENT-COUNTED',
			'unit.query.MoveSymbolSliceTest#testACommentsTrailingPeriodDoesNotHideTheReferenceOwedARepairImport :: control :: '
			+ 'M-MOVE-NAMESCAN-FULLSTOP-BLIND',
			'unit.query.MoveSymbolSliceTest#testACutBeforeATrailingCommentKeepsOneSeparator :: control :: M-MOVE-CUT-TAKES-BOTH-RUNS',
			'unit.query.MoveSymbolSliceTest#testAMiddleDeclarationWithOneBlankSideKeepsIt :: control :: M-MOVE-SIBLINGS-FALSE',
			'unit.query.MoveSymbolSliceTest#testASiblingPackageIsNotAnAncestorSoItIsLeftAlone :: control :: M-MOVE-PACKAGE-CHAIN-ANY',
			'unit.query.MoveSymbolSliceTest#testAValuePositionIsStillNotPriced :: control :: M-MOVE-RECEIVER-ANY-IDENT',
			'unit.query.MoveSymbolSliceTest#testAliasDependencyIsCarriedIntoTheDestination :: control :: M-MOVE-ALIAS-SUFFIX-DROPPED',
			'unit.query.MoveSymbolSliceTest#testAliasImporterRepointedKeepingItsBinding :: control :: M-MOVE-ALIAS-SUFFIX-DROPPED',
			'unit.query.MoveSymbolSliceTest#testBareSamePackageDependencyIsPricedToo :: control :: M-MOVE-PACKAGE-CHAIN-ANY',
			'unit.query.MoveSymbolSliceTest#testCrossPackageAliasImporterNotMistakenForAnFqnReference :: control :: M-MOVE-FQN-ALIAS-RAW',
			'unit.query.MoveSymbolSliceTest#testCuttingAMiddleDeclarationLeavesExactlyOneSeparator :: control :: M-MOVE-BLANKRUN-END-NOOP',
			'unit.query.MoveSymbolSliceTest#testCuttingTheLastDeclarationOfAModuleTakesItsSeparator :: control :: M-MOVE-SIBLINGS-TRUE',
			'unit.query.MoveSymbolSliceTest#testDestinationModuleImportGainsNothingForASecondaryMove :: control :: '
			+ 'M-MOVE-USING-MIRROR-ANY-KIND',
			'unit.query.MoveSymbolSliceTest#testPrivateSiblingMainTypeIsNotABinding :: control :: M-MOVE-PRIVATE-SIBLING-BINDS',
			'unit.query.MoveSymbolSliceTest#testTheDestinationCollisionScanReadsTheDestinationsOwnComments :: control :: '
			+ 'M-MOVE-NAMESCAN-FULLSTOP-BLIND',
			'unit.query.NameMentionScanTest#testACommentOnlyDestinationMentionDoesNotContestTheCarry :: control :: '
			+ 'M-MOVE-NAMESCAN-COMMENT-COUNTED',
			'unit.query.NameMentionScanTest#testAStringSpellingTheQualifiedPathStillRefusesWhileACommentDoesNot :: control :: '
			+ 'M-QUALPATH-COMMENT-COUNTED',
			'unit.query.NewFileSliceTest#testImportsSectionRefusesABareKeyword :: control :: M-NEWFILE-BARE-KEYWORD-WRAPPED',
			'unit.query.NewFileSliceTest#testImportsSectionRefusesAnUnusableLine :: control :: M-NEWFILE-IMPORT-ANY-LINE',
			'unit.query.NewFileSliceTest#testImportsSectionTakesStatements :: control :: M-NEWFILE-IMPORT-DOUBLED',
			'unit.query.OpaqueCondRegionScanTest#testACommentAfterTheEndStaysOutOfTheQuote :: control :: M-OPAQUE-REGION-TRIVIA-KEPT',
			'unit.query.OpaqueCondRegionScanTest#testAPartlyRawRegionSaysSoAndQuotesOnlyItsRawBytes :: control :: M-REGION-INSIDE-NONE',
			'unit.query.OpaqueCondRegionScanTest#testAWhitespaceGapDoesNotDragTheSharedBodyIntoTheQuote :: control :: '
			+ 'M-OPAQUE-REGION-WS-GAP',
			'unit.query.OpaqueCondRegionScanTest#testAnExplicitListBuildsNoNotes :: control :: M-REGION-NOTES-ALWAYS',
			'unit.query.OpaqueCondRegionScanTest#testDanglingElseIsOpaqueWhileItsBraceIdenticalTwinIsNot :: control :: '
			+ 'M-OPAQUE-REGION-NONE',
			'unit.query.OpaqueCondRegionScanTest#testTheNoteNamesTheLineTheRegionAndTheReason :: control :: M-OPAQUE-REGION-NONE',
			'unit.query.OpaqueCondRegionScanTest#testTheQuoteStartsAtTheIfEvenWhenTheNodeBeginsBeforeIt :: control :: '
			+ 'M-OPAQUE-REGION-NODE-SPAN',
			'unit.query.OpaqueCondRegionScanTest#testTheSplitTryReportsBothOfItsRegions :: control :: M-OPAQUE-REGION-NONE',
			'unit.query.PatchSliceTest#testDocCodeSampleIndentationSurvives :: control :: M-PATCH-COMMENT-SHAPE-CHECKED',
			'unit.query.PatchSliceTest#testDocPayloadWithASpaceGutterApplies :: control :: M-PATCH-COMMENT-SHAPE-CHECKED',
			'unit.query.PatchSliceTest#testStringLiteralPerLineIndentStillRefused :: control :: M-PATCH-SHAPE-ALWAYS-SURVIVES',
			'unit.query.ResolutionProjectFilesTest#testDerivedIndexesAreMemoised :: control :: M-MEMO-OFF',
			'unit.query.ResolutionProjectFilesTest#testSetResolutionIndexExpiresDerivedIndexes :: control :: M-NO-INVALIDATE',
			'unit.query.SetModifierSliceTest#testAConditionalRegionOutsideTheKeywordRunIsStillServed :: control :: '
			+ 'M-SETMOD-GUARDED-ANY-VISIBILITY',
			'unit.query.SetModifierSliceTest#testAnEnumAbstractMemberStillTakesPublic :: control :: M-SETMOD-MODULE-BY-TYPE-KINDS',
			'unit.query.SymbolIndexRunMemoSliceTest#testConfinementGateReadsTheIndexGrantSlot :: control :: M-GRANT-SLOT-UNREAD',
			'unit.query.SymbolIndexRunMemoSliceTest#testSupertypeNameUnionIsBuiltOncePerIndex :: control :: M-SUPERTYPE-UNION-NOMEMO'
		], TestRegistry.pins(), 'the pin annotations, with their roles and killing arms');
	}

	/**
	 * The arm registry reaches the generated registry, by NAME.
	 *
	 * Same trade as `REGISTERED_CLASSES` above and no stronger: this is derived
	 * from the very table `TestDiscovery` validated, so it cannot catch a WRONG
	 * arm — only a silently vanished or renamed one, which is the failure a
	 * `@:killer` cannot report because the build would have stopped first. The
	 * names are pinned rather than the rendered lines: an arm's note is prose, and
	 * rewording it should not be a test edit.
	 */
	public function testTheArmRegistryReachesTheGeneratedRegistry(): Void {
		Assert.same([
			'M-ADMITS-TRUE',
			'M-ALWAYS-NEXT',
			'M-ALWAYS-SAME',
			'M-ARM-ANYNAME',
			'M-ARM-ROW-OK',
			'M-BUILDMACRO-TRUE',
			'M-CLAIM-ALL-RECORDED',
			'M-CLAIM-CODE-BLIND',
			'M-CLAIM-NEG-BLIND',
			'M-CLAIM-NOKINDS',
			'M-CLAIM-RAW-DOC',
			'M-CUDDLE-OFF',
			'M-DECLARINGFILES-EMPTY',
			'M-DECLSITE-SCOPEWIDE',
			'M-ELSE-GATE',
			'M-EMPTY-B-ANY-NONEMPTY',
			'M-FANOUT-FIRST',
			'M-FIRST-LINE-FIT',
			'M-HASSUBTYPE-FALSE',
			'M-INHERITS-FALSE',
			'M-ISSUBTYPE-FALSE',
			'M-KINDS',
			'M-LACKSMEMBER-FALSE',
			'M-MEMO-OFF',
			'M-NAMEOUTSIDE-TRUE',
			'M-NO-INVALIDATE',
			'M-NO-WIRE',
			'M-PATHWALK-NULL',
			'M-ROOTS-THIRDPARTY',
			'M-RTTI-FALSE',
			'M-SEAM-BLIND',
			'M-SHADOWEXT-TRUE',
			'M-SUBOVERRIDE-TRUE',
			'M-SUPERDECLARES-FALSE',
			'M-UNRELATED-FALSE',
			'M-WRITEINDEX-PROJECT-FINAL',
			'M-WRITEINDEX-PROJECT-READONLY',
			'M-EXPR-ELSE-KEEP',
			'M-EXPR-ELSE-PLAIN-SAME',
			'M-KEEP-JOINS',
			'M-ELSE-BODY-SAME',
			'M-ARM-PATH-FLAT',
			'M-CURLY-CTORS-NONE',
			'M-SBE-UNGATED',
			'M-SKIPSCAN-SCOPEWIDE',
			'M-CHECKINDEX-PROJECT-FINAL',
			'M-CHECKINDEX-PROJECT-READONLY',
			'M-PLAINCLASS-SCOPEBLIND',
			'M-TRY-BODY-SYM-OFF',
			'M-TRY-CATCHES-SYM-OFF',
			'M-NONCURLY-SAME-DROP',
			'M-NEWLINE-SIGNALS-NONE',
			'M-WORDOP-NO-RESTORE',
			'M-BLANK-MULTILINE-OFF',
			'M-SSB-WRAP-DIRECTION',
			'M-SSB-TRAIL-COMMENT-OFF',
			'M-SSB-FRAME-OFF',
			'M-SSB-CHAIN-OFF',
			'M-SSB-TAIL-SEALED-NONE',
			'M-SSB-OPEN-TRAIL-NONE',
			'M-SSB-DANGLING-NONE',
			'M-EICR-BOUNDARY-SKIP',
			'M-EICR-HEADTEXT-ANY',
			'M-EICR-SOFTLINE-ANCHOR',
			'M-EICR-KNOB-IGNORED',
			'M-SSB-DOBODY-KEEP',
			'M-LOOPIF-NEVER',
			'M-LOOPIF-ALWAYS',
			'M-SSB-TRY-SUBST-OFF',
			'M-SSB-TRY-DEBRACE-NONE',
			'M-SSB-BARE-ILLEGAL',
			'M-SSB-VALUE-WRAP-OFF',
			'M-STRUCT-DECLARES-LOOSE',
			'M-STRUCT-NOMINAL-OPEN',
			'M-STRUCT-ALIAS-OPAQUE',
			'M-STRUCT-NULL-OPAQUE',
			'M-STRUCT-TYPEPARAM-CLOSED',
			'M-STRUCT-DYNAMIC-CLOSED',
			'M-STRUCT-ANON-VAR-KEY',
			'M-STRUCT-UNRESOLVED-OPEN',
			'M-STRUCT-ANON-CLOSED',
			'M-NULLABLE-FLOW-REPORT-INDEX',
			'M-NULLABLE-INDEX-EXCLUSION',
			'M-NULLABLE-REPORT-INDEX',
			'M-DECL-NULLABLE-OVERRIDES-EXISTS',
			'M-DECL-NULLABLE-BLIND',
			'M-NULLABLE-NO-CHAIN',
			'M-NULLABLE-WRAPPER-OPAQUE',
			'M-SAFENAV-NO-NARROW',
			'M-OPAQUE-REGION-NONE',
			'M-OPAQUE-REGION-NODE-SPAN',
			'M-OPAQUE-REGION-WS-GAP',
			'M-PEB-WS-REWIND-OFF',
			'M-BRACKET-GLUE-NONE',
			'M-ELSE-SWITCH-COMMENT-GLUE',
			'M-ELSE-SWITCH-TESTS-NONE',
			'M-ELSE-SWITCH-CLOSE-NONE',
			'M-ELSE-SWITCH-CLOSE-COMMENT',
			'M-RENDER-SPAN-TOKENS',
			'M-DUP-CODE-NORM-KEY',
			'M-EXTRACT-REPEAT-RENDER-SPLIT',
			'M-OPAQUE-REGION-TRIVIA-KEPT',
			'M-PEB-WS-REWIND-TRYPARSE-OFF',
			'M-PEB-WS-REWIND-SEPSTARTS-OFF',
			'M-COND-BLOCK-TAIL-NEVER',
			'M-ARM-KIND-UNSPELLED',
			'M-REGION-INSIDE-NONE',
			'M-REGION-NOTES-ALWAYS',
			'M-NULLABLE-FLOW-EXCLUDE-NONE',
			'M-DOCSPLIT-COVERING-TOO',
			'M-DOCSPLIT-BREAKLESS-TOO',
			'M-DOCSPLIT-OWNER-ANY',
			'M-DOCSPAN-BANNER-IS-DOC',
			'M-BODYSLOT-AUTHORED-NEVER',
			'M-BODYSLOT-LIMIT-EDIT-END',
			'M-BODYSLOT-LEAD-KEPT',
			'M-COMMENT-HOIST-BLIND',
			'M-COMMENT-CARRY-REFUSES',
			'M-BODYSLOT-TRIM-WS-ONLY',
			'M-ARM-FRAGMENT-NONE',
			'M-SUPERTYPE-UNION-NOMEMO',
			'M-GRANT-SLOT-UNREAD',
			'M-EI-DUP-IMPL-ALLOWED',
			'M-EI-GUARD-FLAT-SCAN',
			'M-EI-IMPL-ANY-REFUSED',
			'M-WILDCARD-REPOINT-NONE',
			'M-WILDCARD-BINDING-BLIND',
			'M-WILDCARD-RIVAL-ORDER-BLIND',
			'M-WILDCARD-BINDS-BLIND',
			'M-NEWFILE-IMPORT-DOUBLED',
			'M-NEWFILE-IMPORT-ANY-LINE',
			'M-NEWFILE-BARE-KEYWORD-WRAPPED',
			'M-PATCH-COMMENT-SHAPE-CHECKED',
			'M-PATCH-SHAPE-ALWAYS-SURVIVES',
			'M-ADDMETA-NO-WRAPPER-CLIMB',
			'M-ADDMETA-ZERO-WIDTH-INSERT',
			'M-ADDMETA-CLI-UNROUTED',
			'M-CLI-COMMANDS-MEMOISED',
			'M-LINT-RANGE-INERT',
			'M-CLI-REQUIREMATCH-STATIC',
			'M-PTR-RIDES-NEVER',
			'M-PTR-CASCADE-NEVER-STRANDS',
			'M-TERMINAL-RUNGS-ANY',
			'M-PIEC-SPINE-CLAIM-ANY',
			'M-ORPHAN-ARMS-SHARE-REASON',
			'M-LINTFIX-ACCEPTED-BLAMED',
			'M-ADDMETA-LOOSE-WRAPPER-CLIMB',
			'M-EXIT-STATUS-AGREES',
			'M-COMMENT-WELD-BLIND',
			'M-PATTERN-RESTPROBE-UNSET',
			'M-SEPSTAR-RESTPROBE-UNGATED',
			'M-TRIVIASEP-RESTPROBE-UNGATED',
			'M-FILEHEADER-HEAD-NOT-PIU',
			'M-FILEHEADER-HEAD-ALWAYS-PIU',
			'M-FILEHEADER-ANY-DECL',
			'M-FILEHEADER-ANY-COMMENT',
			'M-FILEHEADER-ANY-COMMENT-KIND',
			'M-FILEHEADER-NO-TWO-COMMENT-ARM',
			'M-FILEHEADER-COND-OPAQUE',
			'M-JSUL-ANNOTATION-NEVER-NEUTRAL',
			'M-JSUL-COMMENT-ANY-IN-FILE',
			'M-JSUL-PATH-ALWAYS-CONDITIONAL',
			'M-JSUL-BARE-IDENT-NOT-SAFE',
			'M-JSUL-LOCAL-CAPTURE-ANY',
			'M-JSUL-UNINDEXED-NAME-ALWAYS',
			'M-JSUL-INIT-IDENT-ALWAYS-REBOUND',
			'M-COMMENT-BOUNDARY-BREAK-KEPT',
			'M-COMMENT-BOUNDARY-TRAIL-INDEX',
			'M-MOVE-SIBLINGS-FALSE',
			'M-MOVE-SIBLINGS-TRUE',
			'M-MOVE-CUT-TAKES-BOTH-RUNS',
			'M-MOVE-BLANKRUN-END-NOOP',
			'M-MOVE-FQN-COMMENT-MASK-NONE',
			'M-MOVE-FQN-ALIAS-RAW',
			'M-MOVE-ALIAS-SUFFIX-DROPPED',
			'M-MOVE-PRIVATE-SIBLING-BINDS',
			'M-MOVE-NAMESCAN-COMMENT-COUNTED',
			'M-MOVE-NAMESCAN-FULLSTOP-BLIND',
			'M-MOVE-USING-MIRROR-ANY-KIND',
			'M-MOVE-PACKAGE-CHAIN-ANY',
			'M-MOVE-RECEIVER-ANY-IDENT',
			'M-SSB-CHAIN-TAIL-OFF',
			'M-SSB-ELEM-TRAIL-COMMENT-NONE',
			'M-SSB-SYMMETRY-ONLY-BLIND',
			'M-CHAIN-STAIRCASE-OFF',
			'M-PAREN-PIN-NONE',
			'M-ARROW-HEAD-WIDTH-NONE',
			'M-GLUE-NEVER-BREAKS',
			'M-SSB-TRAILOPT-REEMIT',
			'M-SSB-ELSE-SPINE-STOP',
			'M-SSB-FRAME-BLANKET',
			'M-EICR-AFTERCOND-RESET',
			'M-ELSE-SEP-EXPR-BLIND',
			'M-REMOVE-CUT-ANNOTATIONS-NONE',
			'M-REMOVE-CUT-SUBJECT-RAW',
			'M-PFF-CALLSCAN-ALWAYS',
			'M-PFF-STDLIB-SAFE-NONE',
			'M-PFF-REBIND-UNRESOLVED',
			'M-SCOPE-LIBRARY-DROPPED',
			'M-SSB-GATE8-ANY-POSITION',
			'M-KEEP-ELSEIF-NEXT-OFF',
			'M-KEEP-ELSEIF-ALWAYS-GLUED',
			'M-BEFORE-KW-TRAILING-DROP',
			'M-BEFORE-KW-LEADING-DROP',
			'M-BEFORE-LEADING-COMMENT-DROP',
			'M-SETMOD-MODULE-BY-TYPE-KINDS',
			'M-SETMOD-GUARDED-ANY-VISIBILITY',
			'M-META-ELEMENT-ANY-COND-REGION',
			'M-CUT-DOC-KEPT-BY-ANY-PREFIX',
			'M-MOVE-CANONICALISE-ALWAYS',
			'M-QUALPATH-COMMENT-COUNTED',
			'M-CARRY-CROSSING-ANY-SIDE',
			'M-STRUCT-BUILTIN-BY-NAME',
			'M-PIA-OBJLIT-SET-FLAGGED',
			'M-TAILMERGE-NORM-ONLY',
			'M-TAILMERGE-FALL-KEPT',
			'M-NAMING-SKIPSCAN-REPORT-INDEX',
			'M-EXISTS-GUARD-BLIND',
			'M-USES-EXACT-ONLY',
			'M-USES-TAIL-SUBSTRING',
			'M-USES-QUALIFIED-DEFAULT',
			'M-DECL-INIT-NONNULL-BLIND',
			'M-DECL-INIT-TERNARY-ANY-ARM',
			'M-DECL-INIT-LITERAL-BLIND',
			'M-DECL-INIT-RECEIVER-MODE-NOMINAL',
			'M-SHORTEN-IMPORT-THRESHOLD-ONE'
		], [for (line in TestRegistry.arms()) line.split(' :: ')[0]], 'the arms every @:killer resolves into');
	}

	/**
	 * The arms whose type the typer could not see, and the reason the registry can
	 * declare them at all.
	 *
	 * `anyparse/macro/*` is behind `#if macro`, so a non-macro build types none of it and
	 * `Context.getModule` answers `ok, 0 type(s)` rather than throwing. Until S102 that
	 * answer was collapsed with a module the classpath does not carry, and the whole
	 * macro-time half of the engine was unaddressable by an arm. This census is the build
	 * macro naming what it handed on; `unit.MutationArmAddressTest` is what answers it,
	 * out of the parser rather than the typer.
	 */
	public function testTheDeferredArmCensusNamesTheMacroModuleArms(): Void {
		Assert.same([
			'M-CURLY-CTORS-NONE :: anyparse.macro.WriterCtorPatternLowering#collectCurlyBlockCtorPatterns',
			'M-SBE-UNGATED :: anyparse.macro.WriterRefFieldLowering#semicolonBeforeSiblingWrap',
			'M-TRY-BODY-SYM-OFF :: anyparse.macro.WriterBraceSymmetryLowering#tryBraceSymmetryWrap',
			'M-TRY-CATCHES-SYM-OFF :: anyparse.macro.WriterBraceSymmetryLowering#tryCatchesSymmetryWrap',
			'M-NONCURLY-SAME-DROP :: anyparse.macro.WriterPolicyLowering#sameLineNonCurlyBlockPolicySwitch',
			'M-NEWLINE-SIGNALS-NONE :: anyparse.macro.WriterTriviaSlotLowering#collectFollowingNewlineSignals',
			'M-WORDOP-NO-RESTORE :: anyparse.macro.OperatorLoopLowering#buildWordOpRestoreExpr',
			'M-BLANK-MULTILINE-OFF :: anyparse.macro.WriterBlankLowering#blankAroundMultilineExprs',
			'M-SSB-WRAP-DIRECTION :: anyparse.macro.WriterBraceSymmetryLowering#deBraceBodyAccess',
			'M-SSB-TRAIL-COMMENT-OFF :: anyparse.macro.WriterBraceSymmetryLowering#deBraceBodyAccess',
			'M-SSB-FRAME-OFF :: anyparse.macro.WriterBraceSymmetryLowering#deBraceBodyAccess',
			'M-SSB-CHAIN-OFF :: anyparse.macro.WriterBraceSymmetryLowering#deBraceBodyAccess',
			'M-EICR-KNOB-IGNORED :: anyparse.macro.WriterBodyPolicyLowering#buildElseIfCommentReflowLayout',
			'M-PEB-WS-REWIND-OFF :: anyparse.macro.StarLoopLowering#buildBlockEndedByteCheck',
			'M-BRACKET-GLUE-NONE :: anyparse.macro.WriterCtorPatternLowering#buildBracketBodyGlueTest',
			'M-ELSE-SWITCH-COMMENT-GLUE :: anyparse.macro.WriterBodyPolicyLowering#buildElseSwitchCases',
			'M-ELSE-SWITCH-TESTS-NONE :: anyparse.macro.WriterBodyPolicyLowering#buildElseSwitchTests',
			'M-ELSE-SWITCH-CLOSE-NONE :: anyparse.macro.WriterCtorPatternLowering#buildElseSwitchGlueTest',
			'M-ELSE-SWITCH-CLOSE-COMMENT :: anyparse.macro.WriterRefFieldLowering#emitBodyPolicyBareRef',
			'M-PEB-WS-REWIND-TRYPARSE-OFF :: anyparse.macro.StarLoopLowering#buildTryparseSepLoop',
			'M-PEB-WS-REWIND-SEPSTARTS-OFF :: anyparse.macro.StarFieldLowering#lowerStarBlockEndedSepStarts',
			'M-COND-BLOCK-TAIL-NEVER :: anyparse.grammar.haxe.HxCondBlockTailRaw#MetaCall:@:re',
			'M-CLI-COMMANDS-MEMOISED :: anyparse.query.cli.CliRegistry#ClassDecl:CliRegistry',
			'M-CLI-REQUIREMATCH-STATIC :: anyparse.query.cli.CliContext#ClassDecl:CliContext',
			'M-PATTERN-RESTPROBE-UNSET :: anyparse.grammar.haxe.HxCasePattern#MetaCall:@:fmt',
			'M-SEPSTAR-RESTPROBE-UNGATED :: anyparse.macro.WriterStarEmitLowering#emitSepStarList',
			'M-TRIVIASEP-RESTPROBE-UNGATED :: anyparse.macro.TriviaSepLowering#triviaSepNoTriviaBranch',
			'M-FILEHEADER-HEAD-NOT-PIU :: anyparse.macro.TriviaEofLowering#triviaEofHeadIsPiuExpr',
			'M-FILEHEADER-HEAD-ALWAYS-PIU :: anyparse.macro.TriviaEofLowering#triviaEofHeadIsPiuExpr',
			'M-FILEHEADER-ANY-DECL :: anyparse.macro.TriviaEofLowering#triviaEofFileheaderBlanksExpr',
			'M-FILEHEADER-ANY-COMMENT :: anyparse.macro.TriviaEofLowering#triviaEofFileheaderBlanksExpr',
			'M-FILEHEADER-ANY-COMMENT-KIND :: anyparse.macro.TriviaEofLowering#triviaEofFileheaderBlanksExpr',
			'M-FILEHEADER-NO-TWO-COMMENT-ARM :: anyparse.macro.TriviaEofLowering#triviaEofFileheaderBlanksExpr',
			'M-FILEHEADER-COND-OPAQUE :: anyparse.macro.TriviaEofLowering#triviaEofHeadIsPiuExpr',
			'M-SSB-TRAILOPT-REEMIT :: anyparse.macro.WriterRefFieldLowering#emitMandatoryRefTrail',
			'M-SSB-FRAME-BLANKET :: anyparse.macro.WriterBraceSymmetryLowering#deBraceBodyAccess',
			'M-ELSE-SEP-EXPR-BLIND :: anyparse.macro.WriterFieldSepLowering#sameLineSeparatorShapeAware',
			'M-KEEP-ELSEIF-NEXT-OFF :: anyparse.macro.WriterBodyPolicyLowering#buildBodyKeepLayout',
			'M-KEEP-ELSEIF-ALWAYS-GLUED :: anyparse.macro.WriterBodyPolicyLowering#buildBodyKeepLayout',
			'M-BEFORE-KW-TRAILING-DROP :: anyparse.macro.WriterFieldSepLowering#beforeKwSeparator',
			'M-BEFORE-KW-LEADING-DROP :: anyparse.macro.WriterFieldSepLowering#beforeKwSeparator',
			'M-BEFORE-LEADING-COMMENT-DROP :: anyparse.macro.WriterTriviaSlotLowering#buildBeforeLeadingSep',
			'M-SHORTEN-IMPORT-THRESHOLD-ONE :: anyparse.check.ShortenTypeRef#FinalMember:IMPORT_THRESHOLD'
		], TestRegistry.deferredArms(), 'the arms the typer could not answer for');
	}

	public function testFixturelessSubclassesAreReportedRatherThanRegistered(): Void {
		Assert.same(EXPECTED_BASE_CLASSES, TestRegistry.baseClasses(), 'the reported no-fixture subclasses');
		final registered: Array<String> = TestRegistry.classNames();
		for (name in EXPECTED_BASE_CLASSES)
			Assert.isFalse(registered.contains(name), '$name carries no fixture, so registering it would be a no-op');
	}

}
